//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScienceBuddy.Teacher
{


    public partial class Dashboard
    {

        /// <summary>
        /// pnlPending control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlPending;

        /// <summary>
        /// pnlRejected control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlRejected;

        /// <summary>
        /// pnlDenied control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlDenied;

        /// <summary>
        /// pnlDashboard control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlDashboard;

        /// <summary>
        /// litTeacherName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litTeacherName;

        /// <summary>
        /// litTotalLessons control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litTotalLessons;

        /// <summary>
        /// litTotalQuizzes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litTotalQuizzes;

        /// <summary>
        /// litUpcomingSessions control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litUpcomingSessions;

        /// <summary>
        /// litTotalStudents control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litTotalStudents;

        /// <summary>
        /// pnlPQCards control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlPQCards;

        /// <summary>
        /// rptPracticeQuizCards control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rptPracticeQuizCards;

        /// <summary>
        /// pnlPQEmpty control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlPQEmpty;

        // ── New dashboard cards ──
        protected global::System.Web.UI.WebControls.Panel pnlTimelineSessions;
        protected global::System.Web.UI.WebControls.Repeater rptTimelineSessions;
        protected global::System.Web.UI.WebControls.Panel pnlTimelineEmpty;
        protected global::System.Web.UI.WebControls.Panel pnlDashNotifs;
        protected global::System.Web.UI.WebControls.Repeater rptDashNotifs;
        protected global::System.Web.UI.WebControls.Panel pnlDashNotifsEmpty;

        // ── Quiz Contribution ──
        protected global::System.Web.UI.WebControls.Literal litUnitPct;
        protected global::System.Web.UI.WebControls.Literal litUnitCount;
        protected global::System.Web.UI.WebControls.Literal litUnitMyCount;
        protected global::System.Web.UI.WebControls.Literal litUnitTotal;
        protected global::System.Web.UI.WebControls.Literal litLevelPct;
        protected global::System.Web.UI.WebControls.Literal litLevelCount;
        protected global::System.Web.UI.WebControls.Literal litLevelMyCount;
        protected global::System.Web.UI.WebControls.Literal litLevelTotal;
        protected global::System.Web.UI.WebControls.HiddenField hidUnitPct;
        protected global::System.Web.UI.WebControls.HiddenField hidLevelPct;
    }
}
