//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ScienceBuddy.Teacher
{
    public partial class ForumReply
    {
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Literal litErrMsg;
        protected global::System.Web.UI.WebControls.Panel pnlMain;
        protected global::System.Web.UI.WebControls.Literal litInitials;
        protected global::System.Web.UI.WebControls.Literal litCreatorName;
        protected global::System.Web.UI.WebControls.Literal litRoleBadge;
        protected global::System.Web.UI.WebControls.Literal litPostDate;
        protected global::System.Web.UI.WebControls.Literal litTitle;
        protected global::System.Web.UI.WebControls.Literal litMessage;
        protected global::System.Web.UI.WebControls.Literal litReplyCount;
        protected global::System.Web.UI.WebControls.LinkButton btnLike;
        protected global::System.Web.UI.WebControls.TextBox txtReply;
        protected global::System.Web.UI.WebControls.Panel pnlReplyVal;
        protected global::System.Web.UI.WebControls.Literal litReplyVal;
        protected global::System.Web.UI.WebControls.Button btnPostReply;
        protected global::System.Web.UI.WebControls.Literal litRepliesBadge;
        protected global::System.Web.UI.WebControls.Panel pnlReplies;
        protected global::System.Web.UI.WebControls.Repeater rptReplies;
        protected global::System.Web.UI.WebControls.Panel pnlRepliesEmpty;
        protected global::System.Web.UI.WebControls.Panel pnlMoreDiscussions;
        protected global::System.Web.UI.WebControls.Repeater rptMore;
        protected global::System.Web.UI.WebControls.HiddenField hidToast;
        protected global::System.Web.UI.WebControls.HiddenField hidForumId;
    }
}
