//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScienceBuddy.Teacher
{
    public partial class Forum
    {
        // ── Toolbar ──────────────────────────────────────────────────
        protected global::System.Web.UI.WebControls.TextBox     txtSearch;
        protected global::System.Web.UI.WebControls.Button      btnSearch;

        // ── Empty-state panels ───────────────────────────────────────
        protected global::System.Web.UI.WebControls.Panel       pnlDbEmpty;
        protected global::System.Web.UI.WebControls.Panel       pnlSearchEmpty;
        protected global::System.Web.UI.WebControls.Button      btnReset;

        // ── Post list ────────────────────────────────────────────────
        protected global::System.Web.UI.WebControls.Panel       pnlList;
        protected global::System.Web.UI.WebControls.Repeater    rptPosts;

        // ── New Post Modal ───────────────────────────────────────────
        protected global::System.Web.UI.WebControls.TextBox     txtTitle;
        protected global::System.Web.UI.WebControls.TextBox     txtMessage;
        protected global::System.Web.UI.WebControls.Panel       pnlModalVal;
        protected global::System.Web.UI.WebControls.Literal     litModalVal;
        protected global::System.Web.UI.WebControls.Button      btnPost;

        // ── Hidden fields ────────────────────────────────────────────
        protected global::System.Web.UI.WebControls.HiddenField hidToast;
        protected global::System.Web.UI.WebControls.HiddenField hidShowModal;
    }
}
