//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ScienceBuddy.Teacher
{
    public partial class liveSession
    {
        protected global::System.Web.UI.WebControls.Literal litMonth;
        protected global::System.Web.UI.WebControls.Button btnPrevMonth;
        protected global::System.Web.UI.WebControls.Button btnNextMonth;
        protected global::System.Web.UI.WebControls.Literal litCalendar;
        protected global::System.Web.UI.WebControls.Panel pnlSessions;
        protected global::System.Web.UI.WebControls.Repeater rptSessions;
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
        protected global::System.Web.UI.WebControls.TextBox txtTitle;
        protected global::System.Web.UI.WebControls.TextBox txtDate;
        protected global::System.Web.UI.WebControls.TextBox txtStart;
        protected global::System.Web.UI.WebControls.TextBox txtEnd;
        protected global::System.Web.UI.WebControls.DropDownList ddlSubtopic;
        protected global::System.Web.UI.WebControls.TextBox txtLink;
        protected global::System.Web.UI.WebControls.TextBox txtDesc;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Literal litError;
        protected global::System.Web.UI.WebControls.Button btnSchedule;
        protected global::System.Web.UI.WebControls.HiddenField hidToast;
        protected global::System.Web.UI.WebControls.HiddenField hidShowModal;
        protected global::System.Web.UI.WebControls.HiddenField hidCalMonth;
    }
}
