//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScienceBuddy.Teacher
{
    public partial class manageMaterials
    {
        protected global::System.Web.UI.WebControls.Panel pnlPending;
        protected global::System.Web.UI.WebControls.Panel pnlDenied;
        protected global::System.Web.UI.WebControls.Panel pnlMain;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.DropDownList ddlFilterLevel;
        protected global::System.Web.UI.WebControls.DropDownList ddlFilterUnit;
        protected global::System.Web.UI.WebControls.DropDownList ddlFilterType;
        protected global::System.Web.UI.WebControls.DropDownList ddlFilterStatus;
        protected global::System.Web.UI.WebControls.Button btnSearch;
        protected global::System.Web.UI.WebControls.Panel pnlMaterials;
        protected global::System.Web.UI.WebControls.Repeater rptMaterials;
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
        protected global::System.Web.UI.WebControls.Literal litFormTitle;
        protected global::System.Web.UI.WebControls.HiddenField hidMaterialId;
        protected global::System.Web.UI.WebControls.TextBox txtTitle;
        protected global::System.Web.UI.WebControls.DropDownList ddlLanguage;
        protected global::System.Web.UI.WebControls.TextBox txtDescription;
        protected global::System.Web.UI.WebControls.DropDownList ddlLevel;
        protected global::System.Web.UI.WebControls.DropDownList ddlUnit;
        protected global::System.Web.UI.WebControls.DropDownList ddlSubtopic;
        protected global::System.Web.UI.WebControls.FileUpload fuFile;
        protected global::System.Web.UI.WebControls.Panel pnlCurrentFile;
        protected global::System.Web.UI.WebControls.Literal litCurrentFile;
        protected global::System.Web.UI.WebControls.Literal litSaveBtnText;
        protected global::System.Web.UI.WebControls.Button btnSave;
        protected global::System.Web.UI.WebControls.Button btnConfirmDelete;
        protected global::System.Web.UI.WebControls.HiddenField hidDeleteId;
        protected global::System.Web.UI.WebControls.HiddenField hidShowEditModal;
        protected global::System.Web.UI.WebControls.HiddenField hidToast;
    }
}
