//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ScienceBuddy.Teacher
{
    public partial class Notifications
    {
        protected global::System.Web.UI.WebControls.LinkButton btnTabAll;
        protected global::System.Web.UI.WebControls.Literal litCountAll;
        protected global::System.Web.UI.WebControls.LinkButton btnTabUnread;
        protected global::System.Web.UI.WebControls.Literal litCountUnread;
        protected global::System.Web.UI.WebControls.LinkButton btnTabRead;
        protected global::System.Web.UI.WebControls.Literal litCountRead;
        protected global::System.Web.UI.WebControls.Panel pnlList;
        protected global::System.Web.UI.WebControls.Repeater rptNotifs;
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
        protected global::System.Web.UI.WebControls.HiddenField hidToast;
    }
}
