//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ScienceBuddy.Teacher
{
    public partial class studentProgress
    {
        protected global::System.Web.UI.WebControls.Panel pnlPending;
        protected global::System.Web.UI.WebControls.Panel pnlContent;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.DropDownList ddlSort;
        protected global::System.Web.UI.WebControls.Panel pnlPodium;
        protected global::System.Web.UI.WebControls.Repeater rptPodium;
        protected global::System.Web.UI.WebControls.Panel pnlRankingEmpty;
        protected global::System.Web.UI.WebControls.Panel pnlTable;
        protected global::System.Web.UI.WebControls.Repeater rptRanking;
    }
}
