//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ScienceBuddy – Login.aspx designer declarations
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScienceBuddy
{
    public partial class Login
    {
        // ── Error / success panels ────────────────────────────────────
        /// <summary>Panel shown when a server-side error message exists.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlError;

        /// <summary>Literal inside the error panel.</summary>
        protected global::System.Web.UI.WebControls.Literal litError;

        /// <summary>Panel shown for success messages (e.g. after password reset).</summary>
        protected global::System.Web.UI.WebControls.Panel pnlSuccess;

        /// <summary>Literal inside the success panel.</summary>
        protected global::System.Web.UI.WebControls.Literal litSuccess;

        // ── Form inputs ───────────────────────────────────────────────
        /// <summary>Username / email text box.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtUsername;

        /// <summary>Password text box.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtPassword;

        /// <summary>Remember-me checkbox.</summary>
        protected global::System.Web.UI.WebControls.CheckBox chkRemember;

        // ── Validators ────────────────────────────────────────────────
        /// <summary>Required field validator for txtUsername.</summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvUsername;

        /// <summary>Required field validator for txtPassword.</summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvPassword;

        // ── Buttons ───────────────────────────────────────────────────
        /// <summary>Login submit button.</summary>
        protected global::System.Web.UI.WebControls.Button btnLogin;
    }
}
