//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ScienceBuddy - Site.Master designer declarations
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScienceBuddy
{
    public partial class SiteMaster
    {
        // ── ScriptManager ────────────────────────────────────────────
        /// <summary>ScriptManager1 control.</summary>
        protected global::System.Web.UI.ScriptManager ScriptManager1;

        // ── Layout Panels ────────────────────────────────────────────
        /// <summary>Top-nav-only layout panel (Guest / Dashboard pages).</summary>
        protected global::System.Web.UI.WebControls.Panel pnlTopNavLayout;

        /// <summary>Sidebar layout panel (logged-in non-dashboard pages).</summary>
        protected global::System.Web.UI.WebControls.Panel pnlSidebarLayout;

        // ── Breadcrumb panel ─────────────────────────────────────────
        /// <summary>Breadcrumb bar panel (sidebar layout).</summary>
        protected global::System.Web.UI.WebControls.Panel pnlBreadcrumb;

        // ── Notification dot ─────────────────────────────────────────
        /// <summary>Red dot indicator on the notification bell.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlNotifDot;

        // ── User avatar / info (sidebar header) ──────────────────────
        /// <summary>User avatar image (sidebar top header).</summary>
        protected global::System.Web.UI.WebControls.Image imgUserAvatar;

        /// <summary>User initials rendered inside the avatar circle.</summary>
        protected global::System.Web.UI.WebControls.Literal litUserInitials;

        /// <summary>User display name in the top header.</summary>
        protected global::System.Web.UI.WebControls.Literal litUserName;

        /// <summary>User role label in the top header.</summary>
        protected global::System.Web.UI.WebControls.Literal litUserRole;

        // ── ContentPlaceHolders ──────────────────────────────────────
        /// <summary>HeadContent – extra &lt;head&gt; tags (styles, meta).</summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadContent;

        /// <summary>TopNavLinks – nav link items in the top navigation bar.</summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder TopNavLinks;

        /// <summary>TopNavActions – right-side action area in the top nav (login buttons, etc.).</summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder TopNavActions;

        /// <summary>MainContent – main body content for top-nav layout pages.</summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;

        /// <summary>SidebarMenu – left sidebar navigation items.</summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder SidebarMenu;

        /// <summary>SidebarFooter – bottom of the sidebar (user profile / logout).</summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder SidebarFooter;

        /// <summary>PageTitle – page title shown in the top header bar.</summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder PageTitle;

        /// <summary>UserDropdownMenu – items inside the user avatar dropdown.</summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder UserDropdownMenu;

        /// <summary>BreadcrumbContent – breadcrumb trail items.</summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder BreadcrumbContent;

        /// <summary>MainContentSidebar – main body content for sidebar layout pages.</summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContentSidebar;

        /// <summary>ScriptsContent – page-level scripts injected before &lt;/body&gt;.</summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder ScriptsContent;

        // ── Language Toggle buttons ──────────────────────────────────
        /// <summary>EN button in top-nav layout.</summary>
        protected global::System.Web.UI.WebControls.LinkButton btnLangEN_Top;

        /// <summary>BM button in top-nav layout.</summary>
        protected global::System.Web.UI.WebControls.LinkButton btnLangBM_Top;

        /// <summary>EN button in sidebar-header layout.</summary>
        protected global::System.Web.UI.WebControls.LinkButton btnLangEN_Header;

        /// <summary>BM button in sidebar-header layout.</summary>
        protected global::System.Web.UI.WebControls.LinkButton btnLangBM_Header;
    }
}
