//------------------------------------------------------------------------------
// <auto-generated>ScienceBuddy – Labs/CircuitLab.aspx</auto-generated>
//------------------------------------------------------------------------------
namespace ScienceBuddy.Student.Labs
{
    public partial class CircuitLab
    {
        protected global::System.Web.UI.WebControls.Literal litPageTitle;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Literal litErrorTitle;
        protected global::System.Web.UI.WebControls.Literal litErrorDesc;
        protected global::System.Web.UI.WebControls.Literal litErrorBtn;
        protected global::System.Web.UI.WebControls.Panel pnlMain;
        protected global::System.Web.UI.WebControls.Literal litBack;
        protected global::System.Web.UI.WebControls.Literal litLabTitle;
        protected global::System.Web.UI.WebControls.Literal litLabDesc;
        protected global::System.Web.UI.WebControls.Literal litDiff;
        protected global::System.Web.UI.WebControls.Literal litModeTitle;
        protected global::System.Web.UI.WebControls.Literal litModeInst;
        protected global::System.Web.UI.WebControls.Literal litSeries;
        protected global::System.Web.UI.WebControls.Literal litParallel;
        protected global::System.Web.UI.WebControls.Literal litBuildTitle;
        protected global::System.Web.UI.WebControls.Literal litBuildInst;
        protected global::System.Web.UI.WebControls.Literal litBattery;
        protected global::System.Web.UI.WebControls.Literal litWire1;
        protected global::System.Web.UI.WebControls.Literal litSwitch;
        protected global::System.Web.UI.WebControls.Literal litBulb1;
        protected global::System.Web.UI.WebControls.Literal litBulb2;
        protected global::System.Web.UI.WebControls.Literal litCompareTitle;
        protected global::System.Web.UI.WebControls.Button btnComplete;
        protected global::System.Web.UI.WebControls.Panel pnlSuccess;
        protected global::System.Web.UI.WebControls.Literal litSuccess;
        protected global::System.Web.UI.WebControls.HiddenField hfScore;
        protected global::System.Web.UI.WebControls.HiddenField hfStars;
    }
}
