//------------------------------------------------------------------------------
// <auto-generated>ScienceBuddy – Labs/JourneyOfSandwich.aspx</auto-generated>
//------------------------------------------------------------------------------
namespace ScienceBuddy.Student.Labs
{
    public partial class JourneyOfSandwich
    {
        protected global::System.Web.UI.WebControls.Literal litPageTitle;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Literal litErrorTitle;
        protected global::System.Web.UI.WebControls.Literal litErrorDesc;
        protected global::System.Web.UI.WebControls.Literal litErrorBtn;
        protected global::System.Web.UI.WebControls.Panel pnlMain;
        protected global::System.Web.UI.WebControls.Literal litBack;
        protected global::System.Web.UI.WebControls.Literal litLabTitle;
        protected global::System.Web.UI.WebControls.Literal litLabDesc;
        protected global::System.Web.UI.WebControls.Literal litDiff;
        protected global::System.Web.UI.WebControls.Literal litStep1Title;
        protected global::System.Web.UI.WebControls.Literal litStep1Inst;
        protected global::System.Web.UI.WebControls.Literal litStep2Title;
        protected global::System.Web.UI.WebControls.Literal litStep2Inst;
        protected global::System.Web.UI.WebControls.Literal litStage0;
        protected global::System.Web.UI.WebControls.Literal litStage1;
        protected global::System.Web.UI.WebControls.Literal litStage2;
        protected global::System.Web.UI.WebControls.Literal litStage3;
        protected global::System.Web.UI.WebControls.Literal litStage4;
        protected global::System.Web.UI.WebControls.Literal litStage5;
        protected global::System.Web.UI.WebControls.Literal litNextBtn;
        protected global::System.Web.UI.WebControls.Button btnComplete;
        protected global::System.Web.UI.WebControls.Panel pnlSuccess;
        protected global::System.Web.UI.WebControls.Literal litSuccess;
        protected global::System.Web.UI.WebControls.HiddenField hfScore;
        protected global::System.Web.UI.WebControls.HiddenField hfStars;
    }
}
