//------------------------------------------------------------------------------
// <auto-generated>ScienceBuddy – Labs/MatterStateChanger.aspx</auto-generated>
//------------------------------------------------------------------------------
namespace ScienceBuddy.Student.Labs
{
    public partial class MatterStateChanger
    {
        protected global::System.Web.UI.WebControls.Literal litPageTitle;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Literal litErrorTitle;
        protected global::System.Web.UI.WebControls.Literal litErrorDesc;
        protected global::System.Web.UI.WebControls.Literal litErrorBtn;
        protected global::System.Web.UI.WebControls.Panel pnlMain;
        protected global::System.Web.UI.WebControls.Literal litBack;
        protected global::System.Web.UI.WebControls.Literal litLabTitle;
        protected global::System.Web.UI.WebControls.Literal litLabDesc;
        protected global::System.Web.UI.WebControls.Literal litDiff;
        protected global::System.Web.UI.WebControls.Literal litStep1Title;
        protected global::System.Web.UI.WebControls.Literal litStep1Inst;
        protected global::System.Web.UI.WebControls.Literal litStateSolid;
        protected global::System.Web.UI.WebControls.Literal litHeatBtn;
        protected global::System.Web.UI.WebControls.Literal litCoolBtn;
        protected global::System.Web.UI.WebControls.Literal litStep2Title;
        protected global::System.Web.UI.WebControls.Literal litStep2Inst;
        protected global::System.Web.UI.WebControls.Button btnComplete;
        protected global::System.Web.UI.WebControls.Panel pnlSuccess;
        protected global::System.Web.UI.WebControls.Literal litSuccess;
        protected global::System.Web.UI.WebControls.HiddenField hfScore;
        protected global::System.Web.UI.WebControls.HiddenField hfStars;
    }
}
