-- ScienceBuddy Fixed / Constant Data

INSERT INTO [Level] (levelId, levelNameEN, levelNameBM, levelDescriptionEN, levelDescriptionBM) VALUES
('LV001', 'Beginner', N'Pemula',
N'Suitable for students who are starting to learn basic Science concepts.',
N'Sesuai untuk murid yang baru mula mempelajari konsep asas Sains.'),
('LV002', 'Intermediate', N'Pertengahan',
N'Suitable for students who have basic Science understanding and are ready for more detailed topics.',
N'Sesuai untuk murid yang mempunyai kefahaman asas Sains dan bersedia untuk topik yang lebih terperinci.'),
('LV003', 'Advanced', N'Lanjutan',
N'Suitable for students who are ready to explore more challenging Science concepts and assessments.',
N'Sesuai untuk murid yang bersedia meneroka konsep dan penilaian Sains yang lebih mencabar.');

INSERT INTO Personality (personalityId, personalityNameEN, personalityNameBM, descriptionENG, descriptionBM, avatar, colour, learningStyleEN, learningStyleBM) VALUES
('P001', 'Achiever', N'Pencapai',
N'A goal-oriented learner who enjoys progress, rewards, badges, and completing learning targets.',
N'Murid yang berorientasikan matlamat dan suka melihat kemajuan, ganjaran, lencana serta menyelesaikan sasaran pembelajaran.',
'Images/Avatars/achiever.png', '#F5B041', 'Goal-based learning', N'Pembelajaran berasaskan matlamat'),
('P002', 'Creative', N'Kreatif',
N'A visual and imaginative learner who enjoys colourful notes, flashcards, videos, and virtual lab activities.',
N'Murid yang visual dan imaginatif serta suka nota berwarna, kad imbas, video dan aktiviti makmal maya.',
'Images/Avatars/creative.png', '#9B59B6', 'Visual and interactive learning', N'Pembelajaran visual dan interaktif'),
('P003', 'Thinker', N'Pemikir',
N'A curious learner who enjoys understanding reasons, reviewing explanations, and analysing weak topics.',
N'Murid yang ingin tahu dan suka memahami sebab, menyemak penerangan serta menganalisis topik lemah.',
'Images/Avatars/thinker.png', '#3498DB', 'Explanation-based learning', N'Pembelajaran berasaskan penerangan'),
('P004', 'Go-Getter', N'Bersemangat',
N'An active learner who enjoys challenges, quizzes, leaderboard ranking, and fast progress.',
N'Murid yang aktif dan suka cabaran, kuiz, kedudukan papan markah serta kemajuan yang cepat.',
'Images/Avatars/gogetter.png', '#E74C3C', 'Challenge-based learning', N'Pembelajaran berasaskan cabaran'),
('P005', 'Chill Learner', N'Santai',
N'A calm learner who prefers step-by-step learning, gentle reminders, and stress-free activities.',
N'Murid yang tenang dan lebih suka pembelajaran langkah demi langkah, peringatan lembut dan aktiviti tanpa tekanan.',
'Images/Avatars/chill-learner.png', '#58D68D', 'Step-by-step learning', N'Pembelajaran langkah demi langkah'),
('P006', 'Socializer', N'Sosial',
N'A collaborative learner who enjoys discussions, teacher guidance, live sessions, and learning with others.',
N'Murid yang suka bekerjasama melalui perbincangan, bimbingan guru, sesi langsung dan pembelajaran bersama orang lain.',
'Images/Avatars/socializer.png', '#F39C12', 'Collaborative learning', N'Pembelajaran kolaboratif');

INSERT INTO Badge (badgeId, badgeNameEN, badgeNameBM, badgeType, xpReward, badgeIcon, requirementDescriptionEN, requirementDescriptionBM, badgeDescriptionEN, badgeDescriptionBM) VALUES
('B001', 'First Step Learner', N'Pelajar Langkah Pertama', 'Lesson', 20, 'Images/Badges/first-step.png',
N'Complete the first lesson.', N'Selesaikan pelajaran pertama.',
N'Awarded to students who begin their learning journey by completing their first lesson.',
N'Diberikan kepada murid yang memulakan perjalanan pembelajaran dengan menyelesaikan pelajaran pertama.'),
('B002', 'Lab Explorer', N'Penjelajah Makmal', 'Lab', 30, 'Images/Badges/lab-explorer.png',
N'Complete the first virtual lab.', N'Selesaikan makmal maya pertama.',
N'Awarded to students who complete their first interactive virtual lab activity.',
N'Diberikan kepada murid yang menyelesaikan aktiviti makmal maya interaktif pertama.'),
('B003', 'Quiz Starter', N'Pemula Kuiz', 'Quiz', 20, 'Images/Badges/quiz-starter.png',
N'Attempt the first quiz.', N'Jawab kuiz pertama.',
N'Awarded to students who attempt their first quiz or self-assessment.',
N'Diberikan kepada murid yang menjawab kuiz atau penilaian kendiri pertama.'),
('B004', 'High Scorer', N'Skor Cemerlang', 'Quiz', 40, 'Images/Badges/high-scorer.png',
N'Score 80% or above in any quiz.', N'Mendapat markah 80% ke atas dalam mana-mana kuiz.',
N'Awarded to students who achieve excellent quiz performance.',
N'Diberikan kepada murid yang mencapai prestasi kuiz yang cemerlang.'),
('B005', 'Unit Master', N'Pakar Unit', 'Unit', 50, 'Images/Badges/unit-master.png',
N'Complete all lessons, labs, and unit quiz in one unit.', N'Selesaikan semua pelajaran, makmal dan kuiz unit dalam satu unit.',
N'Awarded to students who successfully complete all required activities in one unit.',
N'Diberikan kepada murid yang berjaya menyelesaikan semua aktiviti wajib dalam satu unit.'),
('B006', 'Beginner Champion', N'Juara Pemula', 'Level', 100, 'Images/Badges/beginner-champion.png',
N'Complete Beginner level requirements.', N'Selesaikan keperluan tahap Pemula.',
N'Awarded to students who complete all required Beginner level learning activities.',
N'Diberikan kepada murid yang menyelesaikan semua aktiviti pembelajaran wajib tahap Pemula.'),
('B007', 'Intermediate Champion', N'Juara Pertengahan', 'Level', 120, 'Images/Badges/intermediate-champion.png',
N'Complete Intermediate level requirements.', N'Selesaikan keperluan tahap Pertengahan.',
N'Awarded to students who complete all required Intermediate level learning activities.',
N'Diberikan kepada murid yang menyelesaikan semua aktiviti pembelajaran wajib tahap Pertengahan.'),
('B008', 'Advanced Champion', N'Juara Lanjutan', 'Level', 150, 'Images/Badges/advanced-champion.png',
N'Complete Advanced level requirements.', N'Selesaikan keperluan tahap Lanjutan.',
N'Awarded to students who complete all required Advanced level learning activities.',
N'Diberikan kepada murid yang menyelesaikan semua aktiviti pembelajaran wajib tahap Lanjutan.'),
('B009', 'Forum Helper', N'Pembantu Forum', 'Forum', 25, 'Images/Badges/forum-helper.png',
N'Post or reply in the public forum.', N'Hantar hantaran atau balasan dalam forum awam.',
N'Awarded to students who actively participate in public learning discussions.',
N'Diberikan kepada murid yang aktif menyertai perbincangan pembelajaran awam.'),
('B010', 'Consistent Learner', N'Pelajar Konsisten', 'Progress', 50, 'Images/Badges/consistent-learner.png',
N'Complete learning activities on multiple days.', N'Selesaikan aktiviti pembelajaran pada beberapa hari berbeza.',
N'Awarded to students who show consistent learning effort over time.',
N'Diberikan kepada murid yang menunjukkan usaha pembelajaran yang konsisten dari semasa ke semasa.');
