//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScienceBuddy.Student
{
    public partial class AIStudyCompanion1
    {
        protected global::System.Web.UI.WebControls.Literal litPageTitle;
        protected global::System.Web.UI.WebControls.Literal litHeroTitle;
        protected global::System.Web.UI.WebControls.Literal litStudentName;
        protected global::System.Web.UI.WebControls.Literal litAIMessage;
        protected global::System.Web.UI.WebControls.Literal litHeroSub;
        protected global::System.Web.UI.WebControls.Panel pnlHealth;
        protected global::System.Web.UI.WebControls.Literal litAvgScoreLbl;
        protected global::System.Web.UI.WebControls.Literal litAvgScore;
        protected global::System.Web.UI.WebControls.Literal litTotalAttemptsLbl;
        protected global::System.Web.UI.WebControls.Literal litTotalAttempts;
        protected global::System.Web.UI.WebControls.Literal litStrongTopicsLbl;
        protected global::System.Web.UI.WebControls.Literal litStrongTopics;
        protected global::System.Web.UI.WebControls.Literal litCurrentLevel;
        protected global::System.Web.UI.WebControls.Literal litPersonality;
        protected global::System.Web.UI.WebControls.Literal litWeakTopics;
        protected global::System.Web.UI.WebControls.Literal litWeakTopicsLbl;
        protected global::System.Web.UI.WebControls.Panel pnlStatusRow;
        protected global::System.Web.UI.WebControls.Literal litHealthTitle;
        protected global::System.Web.UI.WebControls.Literal litStrongTitle;
        protected global::System.Web.UI.WebControls.Panel pnlStrong;
        protected global::System.Web.UI.WebControls.Literal litStrongList;
        protected global::System.Web.UI.WebControls.Panel pnlStrongEmpty;
        protected global::System.Web.UI.WebControls.Literal litStrongEmpty;
        protected global::System.Web.UI.WebControls.Literal litWeakTitle;
        protected global::System.Web.UI.WebControls.Panel pnlWeak;
        protected global::System.Web.UI.WebControls.Literal litWeakList;
        protected global::System.Web.UI.WebControls.Panel pnlWeakEmpty;
        protected global::System.Web.UI.WebControls.Literal litWeakEmpty;
        protected global::System.Web.UI.WebControls.Literal litPersonalityInsightLabel;
        protected global::System.Web.UI.WebControls.Panel pnlPersonalityInsight;
        protected global::System.Web.UI.WebControls.Literal litPersonalityInsightText;
        protected global::System.Web.UI.WebControls.Literal litTopicZoneTitle;
        protected global::System.Web.UI.WebControls.Panel pnlRecommend;
        protected global::System.Web.UI.WebControls.Literal litRecommendTitle;
        protected global::System.Web.UI.WebControls.Repeater rptRecommendations;
        protected global::System.Web.UI.WebControls.Literal litExplanation;
        protected global::System.Web.UI.WebControls.Literal litTipsTitle;
        protected global::System.Web.UI.WebControls.Literal litStrongEmptyTitle;
        protected global::System.Web.UI.WebControls.Literal litTip1;
        protected global::System.Web.UI.WebControls.Literal litTrendBadge;
        protected global::System.Web.UI.WebControls.Literal litTip2;
        protected global::System.Web.UI.WebControls.Literal litConfidenceBadge;
        protected global::System.Web.UI.WebControls.Literal litTip3;
        protected global::System.Web.UI.WebControls.Panel pnlAIChat;
        protected global::System.Web.UI.WebControls.Literal litChatTitle;
        protected global::System.Web.UI.WebControls.Literal litChatSub;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl chatBox;
        protected global::System.Web.UI.WebControls.Literal litChatChip1;
        protected global::System.Web.UI.WebControls.Literal litChatChip2;
        protected global::System.Web.UI.WebControls.Literal litChatChip3;
        protected global::System.Web.UI.WebControls.Literal litChatChip4;
        protected global::System.Web.UI.WebControls.TextBox txtAIMessage;
        protected global::System.Web.UI.WebControls.Button btnAISend;
        protected global::System.Web.UI.WebControls.Literal litChatNote;
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
        protected global::System.Web.UI.WebControls.Literal litEmptyTitle;
        protected global::System.Web.UI.WebControls.Literal litEmptyDesc;
        protected global::System.Web.UI.WebControls.Panel pnlHealthEmpty;
        protected global::System.Web.UI.WebControls.Literal litHealthEmpty;
    }
}
