//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScienceBuddy.Student
{
    public partial class CreateForumPost1
    {
        /// <summary>
        /// litPageTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litPageTitle;

        /// <summary>
        /// divHeader control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divHeader;

        /// <summary>
        /// divHeaderIcon control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divHeaderIcon;

        /// <summary>
        /// litTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTitle;

        /// <summary>
        /// litSubtitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litSubtitle;

        /// <summary>
        /// pnlPrivateInfo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlPrivateInfo;

        /// <summary>
        /// litPrivateInfoTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litPrivateInfoTitle;

        /// <summary>
        /// litPrivateInfoDesc control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litPrivateInfoDesc;

        /// <summary>
        /// pnlNoParent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoParent;

        /// <summary>
        /// litNoParent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litNoParent;

        /// <summary>
        /// pnlError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlError;

        /// <summary>
        /// litError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litError;

        /// <summary>
        /// litTitleLbl control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTitleLbl;

        /// <summary>
        /// txtTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtTitle;

        /// <summary>
        /// pnlTypeDropdown control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlTypeDropdown;

        /// <summary>
        /// litTypeLbl control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTypeLbl;

        /// <summary>
        /// ddlType control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlType;

        /// <summary>
        /// litTypeHint control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTypeHint;

        /// <summary>
        /// pnlTypeLocked control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlTypeLocked;

        /// <summary>
        /// litTypeLockedLbl control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTypeLockedLbl;

        /// <summary>
        /// litTypeLockedVal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTypeLockedVal;

        /// <summary>
        /// litTagLbl control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTagLbl;

        /// <summary>
        /// ddlTag control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlTag;

        /// <summary>
        /// litMsgLbl control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litMsgLbl;

        /// <summary>
        /// txtMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtMessage;

        /// <summary>
        /// btnSubmit control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnSubmit;

        /// <summary>
        /// litSubmitBtn control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litSubmitBtn;

        /// <summary>
        /// litCancelBtn control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litCancelBtn;
    }
}
