//------------------------------------------------------------------------------
// <auto-generated>
//     ScienceBuddy – Student/Dashboard.aspx designer declarations
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScienceBuddy.Student
{
    public partial class Dashboard
    {
        // ── Sidebar ─────────────────────────────────────────────
        protected global::System.Web.UI.WebControls.Panel   pnlNotifBadge;
        protected global::System.Web.UI.WebControls.Literal litNotifCount;

        // ── Hero ────────────────────────────────────────────────
        protected global::System.Web.UI.WebControls.Literal litGreeting;
        protected global::System.Web.UI.WebControls.Literal litMotivation;
        protected global::System.Web.UI.WebControls.Literal litHeroLevel;
        protected global::System.Web.UI.WebControls.Literal litHeroPersonality;
        protected global::System.Web.UI.WebControls.Literal litHeroPersonality2;
        protected global::System.Web.UI.WebControls.Literal litHeroXP;
        protected global::System.Web.UI.WebControls.Image   imgPersonalityAvatar;
        protected global::System.Web.UI.WebControls.Literal litAvatarFallback;

        // ── XP Bar ──────────────────────────────────────────────
        protected global::System.Web.UI.WebControls.Literal litXPBarLabel;
        protected global::System.Web.UI.WebControls.Literal litXPBarHint;
        protected global::System.Web.UI.WebControls.Literal litXPBarPct;

        // ── Stat cards ──────────────────────────────────────────
        protected global::System.Web.UI.WebControls.Literal litStatLevel;
        protected global::System.Web.UI.WebControls.Literal litStatXP;
        protected global::System.Web.UI.WebControls.Literal litStatBadges;
        protected global::System.Web.UI.WebControls.Literal litStatLessons;
        protected global::System.Web.UI.WebControls.Literal litStatLevelLbl;
        protected global::System.Web.UI.WebControls.Literal litStatXPLbl;
        protected global::System.Web.UI.WebControls.Literal litStatBadgesLbl;
        protected global::System.Web.UI.WebControls.Literal litStatLessonsLbl;
        protected global::System.Web.UI.WebControls.Literal litStatLevelSub;
        protected global::System.Web.UI.WebControls.Literal litStatXPSub;
        protected global::System.Web.UI.WebControls.Literal litStatBadgesSub;
        protected global::System.Web.UI.WebControls.Literal litStatLessonsSub;

        // ── Personality-ordered sections ────────────────────────
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl sdSections;
        protected global::System.Web.UI.WebControls.Panel pnlSectionRec;
        protected global::System.Web.UI.WebControls.Panel pnlSectionContinue;
        protected global::System.Web.UI.WebControls.Panel pnlSectionQuick;
        protected global::System.Web.UI.WebControls.Panel pnlSectionSocial;
        protected global::System.Web.UI.WebControls.Panel pnlSectionNotif;

        // ── Recommendation banner ───────────────────────────────
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divRecBanner;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divPersonalityAvatar;
        protected global::System.Web.UI.WebControls.Image   imgPersonalityThumb;
        protected global::System.Web.UI.WebControls.Literal litPersonalityThumbFallback;
        protected global::System.Web.UI.WebControls.Literal litPersonalityName;
        protected global::System.Web.UI.WebControls.Literal litPersonalityRec;
        protected global::System.Web.UI.WebControls.HyperLink lnkPersonalityAction;
        protected global::System.Web.UI.WebControls.Literal litPersonalityAction;

        // ── Continue learning ───────────────────────────────────
        protected global::System.Web.UI.WebControls.Panel   pnlContinue;
        protected global::System.Web.UI.WebControls.Literal litContinueTitle;
        protected global::System.Web.UI.WebControls.Literal litContinueSub;
        protected global::System.Web.UI.WebControls.Panel   pnlContinueEmpty;

        // ── Notifications ───────────────────────────────────────
        protected global::System.Web.UI.WebControls.Panel    pnlUnreadBadge;
        protected global::System.Web.UI.WebControls.Literal  litUnreadCount;
        protected global::System.Web.UI.WebControls.Panel    pnlNotifications;
        protected global::System.Web.UI.WebControls.Repeater rptNotifications;
        protected global::System.Web.UI.WebControls.Panel    pnlNotificationsEmpty;

        // ── Bilingual label Literals ────────────────────────────
        protected global::System.Web.UI.WebControls.Literal litHeroEyebrow;
        protected global::System.Web.UI.WebControls.Literal litHeroCTA1;
        protected global::System.Web.UI.WebControls.Literal litHeroCTA2;
        protected global::System.Web.UI.WebControls.Literal litXPBarProgress;
        protected global::System.Web.UI.WebControls.Literal litRecLabel;
        protected global::System.Web.UI.WebControls.Literal litSecContinue;
        protected global::System.Web.UI.WebControls.Literal litSecQuick;
        protected global::System.Web.UI.WebControls.Literal litSecNotif;
        protected global::System.Web.UI.WebControls.Literal litSecSocial;
        protected global::System.Web.UI.WebControls.Literal litViewAll;
        protected global::System.Web.UI.WebControls.Literal litSeeAll;
        protected global::System.Web.UI.WebControls.Literal litContinueHeader;
        protected global::System.Web.UI.WebControls.Literal litContinueMeta;
        protected global::System.Web.UI.WebControls.Literal litContinueBtn;
        protected global::System.Web.UI.WebControls.Literal litEmptyTitle;
        protected global::System.Web.UI.WebControls.Literal litEmptyDesc;
        protected global::System.Web.UI.WebControls.Literal litEmptyBtn;
        protected global::System.Web.UI.WebControls.Literal litNotifEmpty;
        protected global::System.Web.UI.WebControls.Literal litNotifEmptyDesc;
        protected global::System.Web.UI.WebControls.Literal litQALearn;
        protected global::System.Web.UI.WebControls.Literal litQALearnDesc;
        protected global::System.Web.UI.WebControls.Literal litQAPractice;
        protected global::System.Web.UI.WebControls.Literal litQAPracticeDesc;
        protected global::System.Web.UI.WebControls.Literal litQALab;
        protected global::System.Web.UI.WebControls.Literal litQALabDesc;
        protected global::System.Web.UI.WebControls.Literal litQALive;
        protected global::System.Web.UI.WebControls.Literal litQALiveDesc;
        protected global::System.Web.UI.WebControls.Literal litQAAI;
        protected global::System.Web.UI.WebControls.Literal litQAAIDesc;
        protected global::System.Web.UI.WebControls.Literal litQAProgress;
        protected global::System.Web.UI.WebControls.Literal litQAProgressDesc;
    }
}
