//------------------------------------------------------------------------------
// <auto-generated>
//     ScienceBuddy – Student/Forum.aspx designer declarations
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScienceBuddy.Student
{
    public partial class ForumPage
    {
        // ── Page Header ─────────────────────────────────────────
        protected global::System.Web.UI.WebControls.Literal litPageTitle;
        protected global::System.Web.UI.WebControls.Literal litTitle;
        protected global::System.Web.UI.WebControls.Literal litSubtitle;

        // ── Summary Cards ───────────────────────────────────────
        protected global::System.Web.UI.WebControls.Literal litTotalDisc;
        protected global::System.Web.UI.WebControls.Literal litTotalDiscLbl;
        protected global::System.Web.UI.WebControls.Literal litMyDisc;
        protected global::System.Web.UI.WebControls.Literal litMyDiscLbl;
        protected global::System.Web.UI.WebControls.Literal litTotalReplies;
        protected global::System.Web.UI.WebControls.Literal litTotalRepliesLbl;

        // ── CTA ─────────────────────────────────────────────────
        protected global::System.Web.UI.WebControls.Literal litCTAText;
        protected global::System.Web.UI.WebControls.Literal litCTABtn;

        // ── Filters ─────────────────────────────────────────────
        protected global::System.Web.UI.WebControls.DropDownList ddlTag;
        protected global::System.Web.UI.WebControls.DropDownList ddlSort;
        protected global::System.Web.UI.WebControls.TextBox      txtSearch;
        protected global::System.Web.UI.WebControls.Button       btnFilter;

        // ── Discussion List ─────────────────────────────────────
        protected global::System.Web.UI.WebControls.Panel    pnlList;
        protected global::System.Web.UI.WebControls.Repeater rptDiscussions;

        // ── Empty State ─────────────────────────────────────────
        protected global::System.Web.UI.WebControls.Panel   pnlEmpty;
        protected global::System.Web.UI.WebControls.Literal litEmptyTitle;
        protected global::System.Web.UI.WebControls.Literal litEmptyDesc;
    }
}
