//------------------------------------------------------------------------------
// <auto-generated>
//     ScienceBuddy – Student/LevelDetails.aspx designer declarations
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScienceBuddy.Student
{
    public partial class LevelDetails
    {
        protected global::System.Web.UI.WebControls.Literal litPageTitle;
        protected global::System.Web.UI.WebControls.Panel pnlLocked;
        protected global::System.Web.UI.WebControls.Literal litLockedTitle;
        protected global::System.Web.UI.WebControls.Literal litLockedDesc;
        protected global::System.Web.UI.WebControls.Literal litLockedBtn;
        protected global::System.Web.UI.WebControls.Panel pnlMain;
        protected global::System.Web.UI.WebControls.Literal litBack;
        protected global::System.Web.UI.WebControls.Literal litLevelName;
        protected global::System.Web.UI.WebControls.Literal litLevelDesc;
        protected global::System.Web.UI.WebControls.Literal litHeroBadge;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl heroFill;
        protected global::System.Web.UI.WebControls.Literal litProgressLbl;
        protected global::System.Web.UI.WebControls.Literal litProgressPct;
        protected global::System.Web.UI.WebControls.Literal litStatUnits;
        protected global::System.Web.UI.WebControls.Literal litStatUnitsLbl;
        protected global::System.Web.UI.WebControls.Literal litStatDone;
        protected global::System.Web.UI.WebControls.Literal litStatDoneLbl;
        protected global::System.Web.UI.WebControls.Literal litStatLessons;
        protected global::System.Web.UI.WebControls.Literal litStatLessonsLbl;
        protected global::System.Web.UI.WebControls.Literal litStatQuiz;
        protected global::System.Web.UI.WebControls.Literal litStatQuizLbl;
        protected global::System.Web.UI.WebControls.Panel pnlUnits;
        protected global::System.Web.UI.WebControls.Literal litRoadmap;
        protected global::System.Web.UI.WebControls.Repeater rptUnits;
        protected global::System.Web.UI.WebControls.Panel pnlUnitsEmpty;
        protected global::System.Web.UI.WebControls.Literal litEmptyTitle;
        protected global::System.Web.UI.WebControls.Literal litEmptyDesc;
        protected global::System.Web.UI.WebControls.Panel pnlQuiz;
        protected global::System.Web.UI.WebControls.Literal litQuizHd;
        protected global::System.Web.UI.WebControls.Literal litQuizTitle;
        protected global::System.Web.UI.WebControls.Literal litQuizSub;
        protected global::System.Web.UI.WebControls.Literal litQuizBtn;
        protected global::System.Web.UI.WebControls.Panel pnlQuizNone;
        protected global::System.Web.UI.WebControls.Literal litQuizNone;
    }
}
