//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScienceBuddy.Student
{
    public partial class LiveSessions1
    {
        protected global::System.Web.UI.WebControls.Literal litPageTitle;
        protected global::System.Web.UI.WebControls.Literal litTitle;
        protected global::System.Web.UI.WebControls.Literal litSubtitle;
        protected global::System.Web.UI.WebControls.Literal litUpcoming;
        protected global::System.Web.UI.WebControls.Literal litUpcomingLbl;
        protected global::System.Web.UI.WebControls.Literal litJoined;
        protected global::System.Web.UI.WebControls.Literal litJoinedLbl;
        protected global::System.Web.UI.WebControls.Literal litCompleted;
        protected global::System.Web.UI.WebControls.Literal litCompletedLbl;
        protected global::System.Web.UI.WebControls.LinkButton btnFilterAll;
        protected global::System.Web.UI.WebControls.LinkButton btnFilterUpcoming;
        protected global::System.Web.UI.WebControls.LinkButton btnFilterOngoing;
        protected global::System.Web.UI.WebControls.LinkButton btnFilterCompleted;
        protected global::System.Web.UI.WebControls.HiddenField hfFilter;
        protected global::System.Web.UI.WebControls.Panel pnlGrid;
        protected global::System.Web.UI.WebControls.Repeater rptSessions;
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
        protected global::System.Web.UI.WebControls.Literal litEmptyTitle;
        protected global::System.Web.UI.WebControls.Literal litEmptyDesc;
        protected global::System.Web.UI.WebControls.Literal litEmptyBtn;
    }
}
