//------------------------------------------------------------------------------
// <auto-generated>
//     ScienceBuddy – Student/MyLearning.aspx designer declarations
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScienceBuddy.Student
{
    public partial class MyLearning
    {
        protected global::System.Web.UI.WebControls.Literal litPageTitle;
        protected global::System.Web.UI.WebControls.Literal litTitle;
        protected global::System.Web.UI.WebControls.Literal litSubtitle;
        protected global::System.Web.UI.WebControls.Repeater rptLevels;
        protected global::System.Web.UI.WebControls.Panel pnlUnits;
        protected global::System.Web.UI.WebControls.Literal litUnitsTitle;
        protected global::System.Web.UI.WebControls.Repeater rptUnits;
        protected global::System.Web.UI.WebControls.Panel pnlQuiz;
        protected global::System.Web.UI.WebControls.Literal litQuizTitle;
        protected global::System.Web.UI.WebControls.Literal litQuizSub;
        protected global::System.Web.UI.WebControls.Literal litQuizBtn;
        protected global::System.Web.UI.WebControls.Panel pnlQuizEmpty;
        protected global::System.Web.UI.WebControls.Literal litQuizEmpty;
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
        protected global::System.Web.UI.WebControls.Literal litEmptyTitle;
        protected global::System.Web.UI.WebControls.Literal litEmptyDesc;
    }
}
