//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScienceBuddy.Student
{
    public partial class MyLearning1
    {
        /// <summary>
        /// litPageTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litPageTitle;

        /// <summary>
        /// litTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTitle;

        /// <summary>
        /// litSubtitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litSubtitle;

        /// <summary>
        /// rptLevels control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptLevels;

        /// <summary>
        /// pnlUnits control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlUnits;

        /// <summary>
        /// litUnitsTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litUnitsTitle;

        /// <summary>
        /// rptUnits control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptUnits;

        /// <summary>
        /// pnlQuiz control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlQuiz;

        /// <summary>
        /// litQuizTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litQuizTitle;

        /// <summary>
        /// litQuizSub control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litQuizSub;

        /// <summary>
        /// litQuizBtn control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litQuizBtn;

        /// <summary>
        /// pnlQuizEmpty control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlQuizEmpty;

        /// <summary>
        /// litQuizEmpty control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litQuizEmpty;

        /// <summary>
        /// pnlEmpty control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;

        /// <summary>
        /// litEmptyTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litEmptyTitle;

        /// <summary>
        /// litEmptyDesc control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litEmptyDesc;
    }
}
