//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScienceBuddy.Student
{
    public partial class MyProfile1
    {
        /// <summary>
        /// litPageTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litPageTitle;

        /// <summary>
        /// litHeroInitial control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litHeroInitial;

        /// <summary>
        /// litHeroName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litHeroName;

        /// <summary>
        /// litHeroRole control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litHeroRole;

        /// <summary>
        /// litLevelLbl control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litLevelLbl;

        /// <summary>
        /// litHeroLevel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litHeroLevel;

        /// <summary>
        /// litHeroPersonality control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litHeroPersonality;

        /// <summary>
        /// litXPLbl control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litXPLbl;

        /// <summary>
        /// litHeroXP control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litHeroXP;

        /// <summary>
        /// litParentCodeLbl control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litParentCodeLbl;

        /// <summary>
        /// litHeroParentCode control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litHeroParentCode;

        /// <summary>
        /// litPersonalTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litPersonalTitle;

        /// <summary>
        /// litUsernameLbl control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litUsernameLbl;

        /// <summary>
        /// txtUsername control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtUsername;

        /// <summary>
        /// litNameLbl control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litNameLbl;

        /// <summary>
        /// txtName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtName;

        /// <summary>
        /// litNicknameLbl control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litNicknameLbl;

        /// <summary>
        /// txtNickname control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNickname;

        /// <summary>
        /// litPhoneLbl control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litPhoneLbl;

        /// <summary>
        /// txtPhone control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPhone;

        /// <summary>
        /// litEmailLbl control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litEmailLbl;

        /// <summary>
        /// txtEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        /// <summary>
        /// litLangTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litLangTitle;

        /// <summary>
        /// litLangLbl control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litLangLbl;

        /// <summary>
        /// ddlLanguage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlLanguage;

        /// <summary>
        /// litPersonalityTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litPersonalityTitle;

        /// <summary>
        /// litPersAvatarFallback control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litPersAvatarFallback;

        /// <summary>
        /// litPersName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litPersName;

        /// <summary>
        /// litPersDesc control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litPersDesc;

        /// <summary>
        /// litPersStyleLbl control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litPersStyleLbl;

        /// <summary>
        /// litPersStyle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litPersStyle;

        /// <summary>
        /// litRetakeBtn control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litRetakeBtn;

        /// <summary>
        /// litComingSoon control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litComingSoon;

        /// <summary>
        /// litStatusTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litStatusTitle;

        /// <summary>
        /// litStatusRoleLbl control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litStatusRoleLbl;

        /// <summary>
        /// litStatusRole control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litStatusRole;

        /// <summary>
        /// litStatusStatusLbl control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litStatusStatusLbl;

        /// <summary>
        /// litStatusStatus control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litStatusStatus;

        /// <summary>
        /// litStatusLangLbl control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litStatusLangLbl;

        /// <summary>
        /// litStatusLang control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litStatusLang;

        /// <summary>
        /// btnSave control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSave;

        /// <summary>
        /// litSaveBtn control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litSaveBtn;

        /// <summary>
        /// pnlSuccess control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlSuccess;

        /// <summary>
        /// litSuccess control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litSuccess;

        /// <summary>
        /// pnlSaveError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlSaveError;

        /// <summary>
        /// litSaveError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litSaveError;
    }
}
