//------------------------------------------------------------------------------
// <auto-generated>
//     ScienceBuddy – Student/MyProfile.aspx designer declarations
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScienceBuddy.Student
{
    public partial class MyProfile
    {
        // ── Page Title ──────────────────────────────────────────
        protected global::System.Web.UI.WebControls.Literal litPageTitle;

        // ── Hero Card ───────────────────────────────────────────
        protected global::System.Web.UI.WebControls.Literal litHeroInitial;
        protected global::System.Web.UI.WebControls.Literal litHeroName;
        protected global::System.Web.UI.WebControls.Literal litHeroRole;
        protected global::System.Web.UI.WebControls.Literal litHeroLevel;
        protected global::System.Web.UI.WebControls.Literal litHeroPersonality;
        protected global::System.Web.UI.WebControls.Literal litHeroXP;
        protected global::System.Web.UI.WebControls.Literal litHeroParentCode;

        // ── Personal Information Form ───────────────────────────
        protected global::System.Web.UI.WebControls.Literal litPersonalTitle;
        protected global::System.Web.UI.WebControls.Literal litUsernameLbl;
        protected global::System.Web.UI.WebControls.Literal litNameLbl;
        protected global::System.Web.UI.WebControls.Literal litNicknameLbl;
        protected global::System.Web.UI.WebControls.Literal litPhoneLbl;
        protected global::System.Web.UI.WebControls.Literal litEmailLbl;
        protected global::System.Web.UI.WebControls.TextBox txtUsername;
        protected global::System.Web.UI.WebControls.TextBox txtName;
        protected global::System.Web.UI.WebControls.TextBox txtNickname;
        protected global::System.Web.UI.WebControls.TextBox txtPhone;
        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        // ── Language Preference ─────────────────────────────────
        protected global::System.Web.UI.WebControls.Literal      litLangTitle;
        protected global::System.Web.UI.WebControls.Literal      litLangLbl;
        protected global::System.Web.UI.WebControls.DropDownList  ddlLanguage;

        // ── Personality Section ─────────────────────────────────
        protected global::System.Web.UI.WebControls.Literal litPersonalityTitle;
        protected global::System.Web.UI.WebControls.Literal litPersName;
        protected global::System.Web.UI.WebControls.Literal litPersDesc;
        protected global::System.Web.UI.WebControls.Literal litPersStyle;
        protected global::System.Web.UI.WebControls.Literal litPersStyleLbl;
        protected global::System.Web.UI.WebControls.Literal litPersAvatarFallback;
        protected global::System.Web.UI.WebControls.Literal litRetakeBtn;
        protected global::System.Web.UI.WebControls.Literal litComingSoon;

        // ── Account Status ──────────────────────────────────────
        protected global::System.Web.UI.WebControls.Literal litStatusTitle;
        protected global::System.Web.UI.WebControls.Literal litStatusRoleLbl;
        protected global::System.Web.UI.WebControls.Literal litStatusRole;
        protected global::System.Web.UI.WebControls.Literal litStatusStatusLbl;
        protected global::System.Web.UI.WebControls.Literal litStatusStatus;
        protected global::System.Web.UI.WebControls.Literal litStatusLangLbl;
        protected global::System.Web.UI.WebControls.Literal litStatusLang;

        // ── Save Area ───────────────────────────────────────────
        protected global::System.Web.UI.WebControls.Button  btnSave;
        protected global::System.Web.UI.WebControls.Literal litSaveBtn;
        protected global::System.Web.UI.WebControls.Panel   pnlSuccess;
        protected global::System.Web.UI.WebControls.Literal litSuccess;
        protected global::System.Web.UI.WebControls.Panel   pnlSaveError;
        protected global::System.Web.UI.WebControls.Literal litSaveError;

        // ── Additional bilingual labels ─────────────────────────
        protected global::System.Web.UI.WebControls.Literal litParentCodeLbl;
        protected global::System.Web.UI.WebControls.Literal litLevelLbl;
        protected global::System.Web.UI.WebControls.Literal litXPLbl;
    }
}
