//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScienceBuddy.Student
{
    public partial class Notifications
    {
        protected global::System.Web.UI.WebControls.Literal litPageTitle;
        protected global::System.Web.UI.WebControls.Literal litTitle;
        protected global::System.Web.UI.WebControls.Literal litSubtitle;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.LinkButton btnFilterAll;
        protected global::System.Web.UI.WebControls.Literal litFilterAll;
        protected global::System.Web.UI.WebControls.LinkButton btnFilterUnread;
        protected global::System.Web.UI.WebControls.Literal litFilterUnread;
        protected global::System.Web.UI.WebControls.LinkButton btnFilterRead;
        protected global::System.Web.UI.WebControls.Literal litFilterRead;
        protected global::System.Web.UI.WebControls.LinkButton btnMarkAllRead;
        protected global::System.Web.UI.WebControls.Literal litMarkAll;
        protected global::System.Web.UI.WebControls.Panel pnlList;
        protected global::System.Web.UI.WebControls.Repeater rptNotifications;
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
        protected global::System.Web.UI.WebControls.Literal litEmptyTitle;
        protected global::System.Web.UI.WebControls.Literal litEmptyDesc;
        protected global::System.Web.UI.WebControls.Literal litEmptyBtn;
    }
}
