//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScienceBuddy.Student
{
    public partial class PersonalityTest1
    {
        protected global::System.Web.UI.WebControls.Literal litPageTitle;
        protected global::System.Web.UI.WebControls.Panel pnlQuiz;
        protected global::System.Web.UI.WebControls.Literal litHeroTitle;
        protected global::System.Web.UI.WebControls.Literal litHeroSub;
        protected global::System.Web.UI.WebControls.Image imgMascot;
        protected global::System.Web.UI.WebControls.Literal litBubble;
        protected global::System.Web.UI.WebControls.Literal litPreview;
        protected global::System.Web.UI.WebControls.Literal litS1;
        protected global::System.Web.UI.WebControls.Literal litS1L;
        protected global::System.Web.UI.WebControls.Literal litS1R;
        protected global::System.Web.UI.WebControls.Literal litH1;
        protected global::System.Web.UI.WebControls.Literal litS2;
        protected global::System.Web.UI.WebControls.Literal litS2L;
        protected global::System.Web.UI.WebControls.Literal litS2R;
        protected global::System.Web.UI.WebControls.Literal litH2;
        protected global::System.Web.UI.WebControls.Literal litS3;
        protected global::System.Web.UI.WebControls.Literal litS3L;
        protected global::System.Web.UI.WebControls.Literal litS3R;
        protected global::System.Web.UI.WebControls.Literal litH3;
        protected global::System.Web.UI.WebControls.Literal litS4;
        protected global::System.Web.UI.WebControls.Literal litS4L;
        protected global::System.Web.UI.WebControls.Literal litS4R;
        protected global::System.Web.UI.WebControls.Literal litH4;
        protected global::System.Web.UI.WebControls.Literal litS5;
        protected global::System.Web.UI.WebControls.Literal litS5L;
        protected global::System.Web.UI.WebControls.Literal litS5R;
        protected global::System.Web.UI.WebControls.Literal litH5;
        protected global::System.Web.UI.WebControls.Literal litS6;
        protected global::System.Web.UI.WebControls.Literal litS6L;
        protected global::System.Web.UI.WebControls.Literal litS6R;
        protected global::System.Web.UI.WebControls.Literal litH6;
        protected global::System.Web.UI.WebControls.Button btnDiscover;
        protected global::System.Web.UI.WebControls.Literal litBtnHint;
        protected global::System.Web.UI.WebControls.Panel pnlResult;
        protected global::System.Web.UI.WebControls.Literal litUnlock;
        protected global::System.Web.UI.WebControls.Image imgResult;
        protected global::System.Web.UI.WebControls.Literal litResultName;
        protected global::System.Web.UI.WebControls.Literal litResultDesc;
        protected global::System.Web.UI.WebControls.Literal litCard1Title;
        protected global::System.Web.UI.WebControls.Literal litCard1Val;
        protected global::System.Web.UI.WebControls.Literal litCard2Title;
        protected global::System.Web.UI.WebControls.Literal litCard2Val;
        protected global::System.Web.UI.WebControls.Literal litCard3Title;
        protected global::System.Web.UI.WebControls.Literal litCard3Val;
        protected global::System.Web.UI.WebControls.Literal litResultBtn;
        protected global::System.Web.UI.WebControls.Literal litRetakeBtn;
    }
}
