//------------------------------------------------------------------------------
// <auto-generated>
//     ScienceBuddy – Student/PracticeLibrary.aspx designer declarations
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScienceBuddy.Student
{
    public partial class PracticeLibrary
    {
        // ── Page header ─────────────────────────────────────────
        protected global::System.Web.UI.WebControls.Literal litPageTitle;
        protected global::System.Web.UI.WebControls.Literal litTitle;
        protected global::System.Web.UI.WebControls.Literal litSubtitle;

        // ── AI Recommendation banner ────────────────────────────
        protected global::System.Web.UI.WebControls.Panel   pnlRecommend;
        protected global::System.Web.UI.WebControls.Literal litRecommendTitle;
        protected global::System.Web.UI.WebControls.Literal litRecommendText;

        // ── Filter dropdowns ────────────────────────────────────
        protected global::System.Web.UI.WebControls.DropDownList ddlLevel;
        protected global::System.Web.UI.WebControls.DropDownList ddlUnit;
        protected global::System.Web.UI.WebControls.DropDownList ddlSubtopic;
        protected global::System.Web.UI.WebControls.DropDownList ddlLanguage;

        // ── Quiz grid ───────────────────────────────────────────
        protected global::System.Web.UI.WebControls.Panel    pnlGrid;
        protected global::System.Web.UI.WebControls.Repeater rptQuizzes;

        // ── Empty state ─────────────────────────────────────────
        protected global::System.Web.UI.WebControls.Panel   pnlEmpty;
        protected global::System.Web.UI.WebControls.Literal litEmptyTitle;
        protected global::System.Web.UI.WebControls.Literal litEmptyDesc;
        protected global::System.Web.UI.WebControls.Literal litEmptyBtn;
    }
}
