//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScienceBuddy.Student
{
    public partial class ProgressReward
    {
        protected global::System.Web.UI.WebControls.Literal litPageTitle;
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
        protected global::System.Web.UI.WebControls.Literal litEmptyTitle;
        protected global::System.Web.UI.WebControls.Literal litEmptyDesc;
        protected global::System.Web.UI.WebControls.Literal litEmptyBtn;
        protected global::System.Web.UI.WebControls.Panel pnlMain;
        protected global::System.Web.UI.WebControls.Literal litHeroTitle;
        protected global::System.Web.UI.WebControls.Literal litHeroSubtitle;
        protected global::System.Web.UI.WebControls.Literal litStatXP;
        protected global::System.Web.UI.WebControls.Literal litStatXPLabel;
        protected global::System.Web.UI.WebControls.Literal litStatLessons;
        protected global::System.Web.UI.WebControls.Literal litStatLessonsLabel;
        protected global::System.Web.UI.WebControls.Literal litStatQuizzes;
        protected global::System.Web.UI.WebControls.Literal litStatQuizzesLabel;
        protected global::System.Web.UI.WebControls.Literal litStatBadges;
        protected global::System.Web.UI.WebControls.Literal litStatBadgesLabel;
        protected global::System.Web.UI.WebControls.Literal litWeeklyTitle;
        protected global::System.Web.UI.WebControls.Literal litWeeklyChart;
        protected global::System.Web.UI.WebControls.Literal litChartLegend;
        protected global::System.Web.UI.WebControls.Literal litQuizPerfTitle;
        protected global::System.Web.UI.WebControls.Panel pnlQuizPerf;
        protected global::System.Web.UI.WebControls.Literal litQuizPerfContent;
        protected global::System.Web.UI.WebControls.Panel pnlNoQuizPerf;
        protected global::System.Web.UI.WebControls.Literal litNoQuizPerf;
        protected global::System.Web.UI.WebControls.Literal litWeakTitle;
        protected global::System.Web.UI.WebControls.Panel pnlWeakTopics;
        protected global::System.Web.UI.WebControls.Literal litWeakTopicsContent;
        protected global::System.Web.UI.WebControls.Panel pnlNoWeakTopics;
        protected global::System.Web.UI.WebControls.Literal litNoWeakTopics;
        protected global::System.Web.UI.WebControls.Literal litBadgeTitle;
        protected global::System.Web.UI.WebControls.Panel pnlBadges;
        protected global::System.Web.UI.WebControls.Repeater rptBadges;
        protected global::System.Web.UI.WebControls.Panel pnlNoBadges;
        protected global::System.Web.UI.WebControls.Literal litNoBadges;
        protected global::System.Web.UI.WebControls.Literal litCertTitle;
        protected global::System.Web.UI.WebControls.Literal litCertContent;
        protected global::System.Web.UI.WebControls.Panel pnlAIHint;
        protected global::System.Web.UI.WebControls.Literal litAIHintTitle;
        protected global::System.Web.UI.WebControls.Literal litAIHintText;
    }
}
