//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScienceBuddy.Student
{
    public partial class QuizPage
    {
        protected global::System.Web.UI.WebControls.Literal litPageTitle;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Literal litErrorTitle;
        protected global::System.Web.UI.WebControls.Literal litErrorDesc;
        protected global::System.Web.UI.WebControls.Literal litErrorBtn;
        protected global::System.Web.UI.WebControls.Panel pnlQuiz;
        protected global::System.Web.UI.WebControls.Literal litQuizTitle;
        protected global::System.Web.UI.WebControls.Literal litQuizSub;
        protected global::System.Web.UI.WebControls.Literal litQCount;
        protected global::System.Web.UI.WebControls.Literal litQType;
        protected global::System.Web.UI.WebControls.Literal litProgressLabel;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl progressFill;
        protected global::System.Web.UI.WebControls.Literal litProgressCount;
        protected global::System.Web.UI.WebControls.Panel pnlValMsg;
        protected global::System.Web.UI.WebControls.Literal litValMsg;
        protected global::System.Web.UI.WebControls.Literal litQNum;
        protected global::System.Web.UI.WebControls.Panel pnlQDiff;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divDiff;
        protected global::System.Web.UI.WebControls.Literal litQDiff;
        protected global::System.Web.UI.WebControls.Literal litQText;
        protected global::System.Web.UI.WebControls.Image imgQuestion;
        protected global::System.Web.UI.WebControls.Panel pnlMCQ;
        protected global::System.Web.UI.WebControls.RadioButtonList rblMCQ;
        protected global::System.Web.UI.WebControls.Panel pnlTF;
        protected global::System.Web.UI.WebControls.RadioButtonList rblTF;
        protected global::System.Web.UI.WebControls.Panel pnlMulti;
        protected global::System.Web.UI.WebControls.Literal litMultiHint;
        protected global::System.Web.UI.WebControls.CheckBoxList cblMulti;
        protected global::System.Web.UI.WebControls.Panel pnlDrag;
        protected global::System.Web.UI.WebControls.Literal litDragHint;
        protected global::System.Web.UI.WebControls.Literal litDDPlaceholder;
        protected global::System.Web.UI.WebControls.Literal litDDChips;
        protected global::System.Web.UI.WebControls.Literal litDDResetBtn;
        protected global::System.Web.UI.WebControls.HiddenField hdnDDAnswer;
        protected global::System.Web.UI.WebControls.Button btnPrev;
        protected global::System.Web.UI.WebControls.Button btnNext;
        protected global::System.Web.UI.WebControls.Button btnSubmit;
    }
}
