//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScienceBuddy.Student
{
    public partial class QuizResultPage
    {
        protected global::System.Web.UI.WebControls.Literal litPageTitle;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Literal litErrorTitle;
        protected global::System.Web.UI.WebControls.Literal litError;
        protected global::System.Web.UI.WebControls.Literal litErrBtn;
        protected global::System.Web.UI.WebControls.Panel pnlResult;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divHero;
        protected global::System.Web.UI.WebControls.Literal litHeroIcon;
        protected global::System.Web.UI.WebControls.Literal litHeroTitle;
        protected global::System.Web.UI.WebControls.Literal litHeroSub;
        protected global::System.Web.UI.WebControls.Literal litScorePct;
        protected global::System.Web.UI.WebControls.Literal litStars;
        protected global::System.Web.UI.WebControls.Literal litStatCorrect;
        protected global::System.Web.UI.WebControls.Literal litStatCorrectLbl;
        protected global::System.Web.UI.WebControls.Literal litStatWrong;
        protected global::System.Web.UI.WebControls.Literal litStatWrongLbl;
        protected global::System.Web.UI.WebControls.Literal litStatTotal;
        protected global::System.Web.UI.WebControls.Literal litStatTotalLbl;
        protected global::System.Web.UI.WebControls.Literal litStatScore;
        protected global::System.Web.UI.WebControls.Literal litStatScoreLbl;
        protected global::System.Web.UI.WebControls.Literal litStatAttempt;
        protected global::System.Web.UI.WebControls.Literal litStatAttemptLbl;
        protected global::System.Web.UI.WebControls.Panel pnlMessage;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divMsgIcon;
        protected global::System.Web.UI.WebControls.Literal litMsgTitle;
        protected global::System.Web.UI.WebControls.Literal litMessage;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkReview;
        protected global::System.Web.UI.WebControls.Literal litReviewBtn;
        protected global::System.Web.UI.WebControls.Panel pnlRetry;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkRetry;
        protected global::System.Web.UI.WebControls.Literal litRetryBtn;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkBack;
        protected global::System.Web.UI.WebControls.Literal litBackBtn;
        protected global::System.Web.UI.WebControls.Literal litProgressBtn;
        protected global::System.Web.UI.WebControls.Literal litHistoryBtn;
    }
}
