//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScienceBuddy.Student
{
    public partial class QuizHistory
    {
        protected global::System.Web.UI.WebControls.Literal litPageTitle;
        protected global::System.Web.UI.WebControls.Literal litBackToPractice;
        protected global::System.Web.UI.WebControls.Literal litTitle;
        protected global::System.Web.UI.WebControls.Literal litSubtitle;
        protected global::System.Web.UI.WebControls.Literal litStatTotal;
        protected global::System.Web.UI.WebControls.Literal litStatTotalLbl;
        protected global::System.Web.UI.WebControls.Literal litStatPassed;
        protected global::System.Web.UI.WebControls.Literal litStatPassedLbl;
        protected global::System.Web.UI.WebControls.Literal litStatBest;
        protected global::System.Web.UI.WebControls.Literal litStatBestLbl;
        protected global::System.Web.UI.WebControls.Literal litStatLatest;
        protected global::System.Web.UI.WebControls.Literal litStatLatestLbl;
        protected global::System.Web.UI.WebControls.Literal litFType;
        protected global::System.Web.UI.WebControls.DropDownList ddlType;
        protected global::System.Web.UI.WebControls.Literal litFStatus;
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
        protected global::System.Web.UI.WebControls.Literal litFSort;
        protected global::System.Web.UI.WebControls.DropDownList ddlSort;
        protected global::System.Web.UI.WebControls.Literal litFSearch;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.Button btnFilter;
        protected global::System.Web.UI.WebControls.Panel pnlList;
        protected global::System.Web.UI.WebControls.Repeater rptHistory;
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
        protected global::System.Web.UI.WebControls.Literal litEmptyTitle;
        protected global::System.Web.UI.WebControls.Literal litEmptyDesc;
        protected global::System.Web.UI.WebControls.Literal litEmptyBtn;
    }
}
