//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScienceBuddy.Student
{
    public partial class RevisionPlan
    {
        protected global::System.Web.UI.WebControls.Literal litPageTitle;
        protected global::System.Web.UI.WebControls.Literal litHeroTitle;
        protected global::System.Web.UI.WebControls.Literal litHeroSub;
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
        protected global::System.Web.UI.WebControls.Literal litEmptyTitle;
        protected global::System.Web.UI.WebControls.Literal litEmptyDesc;
        protected global::System.Web.UI.WebControls.Literal litEmptyBtn;
        protected global::System.Web.UI.WebControls.Panel pnlPlan;
        protected global::System.Web.UI.WebControls.Panel pnlAlert;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divAlert;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl iAlertIcon;
        protected global::System.Web.UI.WebControls.Literal litAlert;
        protected global::System.Web.UI.WebControls.Literal litPlanTitle;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl spanStatus;
        protected global::System.Web.UI.WebControls.Literal litStatus;
        protected global::System.Web.UI.WebControls.Literal litDateRange;
        protected global::System.Web.UI.WebControls.Literal litRemaining;
        protected global::System.Web.UI.WebControls.Literal litParentLabel;
        protected global::System.Web.UI.WebControls.Literal litProgressLabel;
        protected global::System.Web.UI.WebControls.Literal litProgressPct;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divProgressBadge;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divProgressFill;
        protected global::System.Web.UI.WebControls.Literal litMilestones;
        protected global::System.Web.UI.WebControls.Literal litTaskCounts;
        protected global::System.Web.UI.WebControls.Literal litMotivate;
        protected global::System.Web.UI.WebControls.Literal litNextRewardLabel;
        protected global::System.Web.UI.WebControls.Literal litNextRewardImg;
        protected global::System.Web.UI.WebControls.Literal litNextReward;
        protected global::System.Web.UI.WebControls.Literal litFinalRewardLabel;
        protected global::System.Web.UI.WebControls.Literal litFinalRewardImg;
        protected global::System.Web.UI.WebControls.Literal litFinalReward;
        protected global::System.Web.UI.WebControls.Panel pnlSuccess;
        protected global::System.Web.UI.WebControls.Literal litSuccess;
        protected global::System.Web.UI.WebControls.Literal litTasksTitle;
        protected global::System.Web.UI.WebControls.LinkButton btnFilterPending;
        protected global::System.Web.UI.WebControls.LinkButton btnFilterCompleted;
        protected global::System.Web.UI.WebControls.LinkButton btnFilterAll;
        protected global::System.Web.UI.WebControls.Panel pnlTaskEmpty;
        protected global::System.Web.UI.WebControls.Literal litTaskEmpty;
        protected global::System.Web.UI.WebControls.Repeater rptTasks;
        protected global::System.Web.UI.WebControls.Literal litRewardsTitle;
        protected global::System.Web.UI.WebControls.Repeater rptRewards;
        protected global::System.Web.UI.WebControls.Literal litNavProgress;
        protected global::System.Web.UI.WebControls.Literal litNavLearning;
    }
}
