//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScienceBuddy.Student
{
    public partial class UnitDetails1
    {
        protected global::System.Web.UI.WebControls.Literal litPageTitle;
        protected global::System.Web.UI.WebControls.Panel pnlLocked;
        protected global::System.Web.UI.WebControls.Literal litLockedTitle;
        protected global::System.Web.UI.WebControls.Literal litLockedDesc;
        protected global::System.Web.UI.WebControls.Literal litLockedBtn;
        protected global::System.Web.UI.WebControls.Panel pnlMain;
        protected global::System.Web.UI.WebControls.Literal litBack;
        protected global::System.Web.UI.WebControls.Literal litUnitName;
        protected global::System.Web.UI.WebControls.Literal litUnitDesc;
        protected global::System.Web.UI.WebControls.Literal litHeroLevel;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl heroBar;
        protected global::System.Web.UI.WebControls.Literal litBarLbl;
        protected global::System.Web.UI.WebControls.Literal litBarPct;
        protected global::System.Web.UI.WebControls.Literal litPathLessons;
        protected global::System.Web.UI.WebControls.Literal litPathLessonsCt;
        protected global::System.Web.UI.WebControls.Literal litPathMats;
        protected global::System.Web.UI.WebControls.Literal litPathMatsCt;
        protected global::System.Web.UI.WebControls.Literal litPathLab;
        protected global::System.Web.UI.WebControls.Literal litPathLabCt;
        protected global::System.Web.UI.WebControls.Literal litPathQuiz;
        protected global::System.Web.UI.WebControls.Literal litPathQuizCt;
        protected global::System.Web.UI.WebControls.Panel pnlLessons;
        protected global::System.Web.UI.WebControls.Literal litLessonHd;
        protected global::System.Web.UI.WebControls.Repeater rptSubtopics;
        protected global::System.Web.UI.WebControls.Panel pnlMats;
        protected global::System.Web.UI.WebControls.Literal litMatHd;
        protected global::System.Web.UI.WebControls.Repeater rptMats;
        protected global::System.Web.UI.WebControls.Panel pnlMatsEmpty;
        protected global::System.Web.UI.WebControls.Literal litMatsEmpty;
        protected global::System.Web.UI.WebControls.Panel pnlLab;
        protected global::System.Web.UI.WebControls.Literal litLabHd;
        protected global::System.Web.UI.WebControls.Literal litLabTitle;
        protected global::System.Web.UI.WebControls.Literal litLabSub;
        protected global::System.Web.UI.WebControls.Literal litLabBtn;
        protected global::System.Web.UI.WebControls.Panel pnlLabEmpty;
        protected global::System.Web.UI.WebControls.Literal litLabEmpty;
        protected global::System.Web.UI.WebControls.Panel pnlQuiz;
        protected global::System.Web.UI.WebControls.Literal litQuizHd;
        protected global::System.Web.UI.WebControls.Literal litQuizTitle;
        protected global::System.Web.UI.WebControls.Literal litQuizSub;
        protected global::System.Web.UI.WebControls.Literal litQuizBtn;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkQuizStart;
        protected global::System.Web.UI.WebControls.Panel pnlQuizResult;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkQuizResult;
        protected global::System.Web.UI.WebControls.Literal litQuizResultBtn;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkQuizReview;
        protected global::System.Web.UI.WebControls.Literal litQuizReviewBtn;
        protected global::System.Web.UI.WebControls.Panel pnlQuizEmpty;
        protected global::System.Web.UI.WebControls.Literal litQuizEmpty;
    }
}
