//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ScienceBuddy.Admin
{
    public partial class CertificateManagement
    {
        protected global::System.Web.UI.WebControls.Literal litReady;
        protected global::System.Web.UI.WebControls.Literal litGenerated;
        protected global::System.Web.UI.WebControls.Literal litSent;
        protected global::System.Web.UI.WebControls.Literal litTotal;
        protected global::System.Web.UI.WebControls.Panel pnlCerts;
        protected global::System.Web.UI.WebControls.Repeater rptCerts;
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
        protected global::System.Web.UI.WebControls.Panel pnlEligible;
        protected global::System.Web.UI.WebControls.Repeater rptEligible;
        protected global::System.Web.UI.WebControls.Panel pnlNoEligible;
        // Certificate Preview Modal
        protected global::System.Web.UI.WebControls.Panel pnlModal;
        protected global::System.Web.UI.WebControls.Panel pnlIframe;
        protected global::System.Web.UI.WebControls.Literal litIframe;
        protected global::System.Web.UI.WebControls.Panel pnlInlineCert;
        protected global::System.Web.UI.WebControls.Button btnCloseModal;
        protected global::System.Web.UI.WebControls.HyperLink lnkDownload;
        protected global::System.Web.UI.WebControls.LinkButton btnModalSend;
        protected global::System.Web.UI.WebControls.HiddenField hfModalCertId;
        protected global::System.Web.UI.WebControls.HiddenField hfModalStudentUserId;
        protected global::System.Web.UI.WebControls.HiddenField hfModalStudentName;
        protected global::System.Web.UI.WebControls.HiddenField hfModalLevelName;
        protected global::System.Web.UI.WebControls.HiddenField hfCertUrl;
        // Toast
        protected global::System.Web.UI.WebControls.Panel pnlToast;
        protected global::System.Web.UI.WebControls.Literal litToast;
    }
}
