<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Dashboard.aspx.cs" Inherits="ScienceBuddy.Admin.Dashboard" MasterPageFile="~/Site.Master" Title="Admin Dashboard" %>
<asp:Content ID="cHead" ContentPlaceHolderID="HeadContent" runat="server">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css" />
<style>
:root{--db:#2563EB;--db-dark:#1D4ED8;--db-light:#EFF6FF;}

/* Hero - Premium gradient with glassmorphism */
.db-hero{background:linear-gradient(135deg,#1a237e 0%,#1565c0 30%,#2563EB 60%,#42a5f5 100%);border-radius:24px;padding:clamp(24px,4vw,48px) clamp(24px,4vw,48px);color:#fff;position:relative;overflow:hidden;margin-bottom:28px;box-shadow:0 20px 60px rgba(37,99,235,.3),inset 0 1px 0 rgba(255,255,255,.1);}
.db-hero::before{content:'';position:absolute;width:500px;height:500px;border-radius:50%;background:radial-gradient(circle,rgba(255,255,255,.08) 0%,transparent 70%);top:-200px;right:-100px;animation:float 8s ease-in-out infinite;}
.db-hero::after{content:'';position:absolute;width:300px;height:300px;border-radius:50%;background:radial-gradient(circle,rgba(255,255,255,.05) 0%,transparent 70%);bottom:-100px;left:50px;animation:float 6s ease-in-out infinite reverse;}
@keyframes float{0%,100%{transform:translateY(0)}50%{transform:translateY(-20px)}}
.db-hero-body{position:relative;z-index:1;display:flex;align-items:center;justify-content:space-between;gap:24px;flex-wrap:wrap;}
.db-hero-eyebrow{font-size:.7rem;font-weight:700;letter-spacing:2px;text-transform:uppercase;opacity:.8;margin-bottom:6px;display:flex;align-items:center;gap:6px;}
.db-hero-title{font-family:var(--font-primary);font-size:clamp(1.5rem,3vw,2.25rem);font-weight:900;line-height:1.15;margin-bottom:8px;text-shadow:0 2px 10px rgba(0,0,0,.1);}
.db-hero-sub{font-size:.9rem;opacity:.85;max-width:440px;line-height:1.6;}
.db-hero-chips{display:flex;gap:10px;flex-wrap:wrap;margin-top:16px;}
.db-hero-chip{background:rgba(255,255,255,.12);backdrop-filter:blur(10px);border:1px solid rgba(255,255,255,.2);border-radius:50px;padding:7px 16px;font-size:.78rem;font-weight:700;display:inline-flex;align-items:center;gap:6px;transition:background .2s;}
.db-hero-chip:hover{background:rgba(255,255,255,.2);}
.db-hero-actions{display:flex;gap:10px;flex-wrap:wrap;}
.db-hero-btn{padding:11px 22px;border-radius:12px;font-size:.8rem;font-weight:700;text-decoration:none;transition:all .25s;display:inline-flex;align-items:center;gap:7px;background:rgba(255,255,255,.12);backdrop-filter:blur(10px);color:#fff;border:1px solid rgba(255,255,255,.25);box-shadow:0 4px 15px rgba(0,0,0,.1);}
.db-hero-btn:hover{background:rgba(255,255,255,.22);transform:translateY(-2px);box-shadow:0 8px 25px rgba(0,0,0,.15);text-decoration:none;color:#fff;}
.db-hero-btn.primary{background:#fff;color:#1D4ED8;border-color:#fff;box-shadow:0 4px 20px rgba(255,255,255,.3);}
.db-hero-btn.primary:hover{background:#F0F9FF;color:#1D4ED8;transform:translateY(-2px);box-shadow:0 8px 30px rgba(255,255,255,.4);}

/* Summary Cards - Glassmorphism with depth */
.db-cards{display:grid;grid-template-columns:repeat(4,1fr);gap:20px;margin-bottom:32px;}
.db-card{background:var(--color-white);border-radius:20px;border:1px solid rgba(0,0,0,.06);box-shadow:0 4px 20px rgba(0,0,0,.04),0 1px 3px rgba(0,0,0,.06);padding:24px;transition:all .3s cubic-bezier(.4,0,.2,1);position:relative;overflow:hidden;min-height:200px;display:flex;flex-direction:column;}
.db-card:hover{transform:translateY(-6px);box-shadow:0 20px 40px rgba(0,0,0,.08),0 4px 12px rgba(0,0,0,.04);}
.db-card::before{content:'';position:absolute;top:0;left:0;right:0;height:4px;border-radius:20px 20px 0 0;}
.db-card::after{content:'';position:absolute;top:0;right:0;width:120px;height:120px;border-radius:50%;opacity:.04;pointer-events:none;}
.db-card.c1::before{background:linear-gradient(90deg,#1D4ED8,#60A5FA);}.db-card.c1::after{background:#2563EB;}
.db-card.c2::before{background:linear-gradient(90deg,#047857,#34D399);}.db-card.c2::after{background:#059669;}
.db-card.c3::before{background:linear-gradient(90deg,#B45309,#FBBF24);}.db-card.c3::after{background:#D97706;}
.db-card.c4::before{background:linear-gradient(90deg,#6D28D9,#A78BFA);}.db-card.c4::after{background:#7C3AED;}
.db-card-hdr{display:flex;align-items:center;justify-content:space-between;margin-bottom:20px;}
.db-card-ico{width:52px;height:52px;border-radius:14px;display:flex;align-items:center;justify-content:center;font-size:1.3rem;box-shadow:0 4px 12px rgba(0,0,0,.08);}
.db-card-title{font-size:.85rem;font-weight:700;color:var(--color-text-secondary);letter-spacing:.3px;}
.db-card-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px;flex:1;}
.db-card-val{font-family:var(--font-primary);font-size:2rem;font-weight:900;color:var(--color-text);line-height:1;}.db-card-lbl{font-size:.75rem;color:var(--color-text-muted);font-weight:600;margin-top:4px;}
.db-card-btn{margin-top:auto;padding-top:16px;display:inline-flex;align-items:center;gap:5px;font-size:.8rem;font-weight:700;color:var(--db);text-decoration:none;transition:all .2s;}.db-card-btn:hover{gap:10px;color:var(--db-dark);}

/* Quick Actions - Beautiful grid */
.db-qa{margin-bottom:32px;}
.db-qa-title{font-family:var(--font-primary);font-size:1.1rem;font-weight:800;color:var(--color-text);margin-bottom:16px;display:flex;align-items:center;gap:8px;}
.db-qa-grid{display:grid;grid-template-columns:repeat(6,1fr);gap:12px;}
.db-qa-item{background:var(--color-white);border-radius:16px;border:1px solid rgba(0,0,0,.06);padding:20px 12px;text-align:center;text-decoration:none;transition:all .3s cubic-bezier(.4,0,.2,1);display:flex;flex-direction:column;align-items:center;gap:10px;box-shadow:0 2px 8px rgba(0,0,0,.03);}
.db-qa-item:hover{transform:translateY(-4px);box-shadow:0 12px 24px rgba(0,0,0,.08);border-color:var(--db);text-decoration:none;}
.db-qa-ico{width:44px;height:44px;border-radius:12px;display:flex;align-items:center;justify-content:center;font-size:1.1rem;transition:transform .3s;}
.db-qa-item:hover .db-qa-ico{transform:scale(1.1);}
.db-qa-lbl{font-size:.72rem;font-weight:700;color:var(--color-text);line-height:1.3;}

/* Two column sections */
.db-row2{display:grid;grid-template-columns:1fr 1fr;gap:24px;margin-bottom:28px;}
.db-section{background:var(--color-white);border-radius:20px;border:1px solid rgba(0,0,0,.06);box-shadow:0 4px 20px rgba(0,0,0,.04);overflow:hidden;}
.db-sec-hdr{padding:16px 24px;border-bottom:1px solid rgba(0,0,0,.05);display:flex;align-items:center;justify-content:space-between;background:linear-gradient(180deg,rgba(0,0,0,.01) 0%,transparent 100%);}
.db-sec-title{font-family:var(--font-primary);font-size:.95rem;font-weight:800;color:var(--color-text);display:flex;align-items:center;gap:8px;}
.db-sec-body{padding:20px 24px;max-height:420px;overflow-y:auto;}

/* Activity timeline - Premium */
.db-log{display:flex;align-items:flex-start;gap:14px;padding:14px 0;border-bottom:1px solid rgba(0,0,0,.03);transition:background .15s;border-radius:8px;margin:0 -8px;padding-left:8px;padding-right:8px;}.db-log:last-child{border-bottom:none;}.db-log:hover{background:rgba(37,99,235,.02);}
.db-log-ico{width:36px;height:36px;border-radius:10px;display:flex;align-items:center;justify-content:center;font-size:.9rem;flex-shrink:0;box-shadow:0 2px 6px rgba(0,0,0,.06);}
.db-log-body{flex:1;min-width:0;}.db-log-action{font-weight:700;font-size:.84rem;color:var(--color-text);}.db-log-desc{font-size:.77rem;color:var(--color-text-muted);white-space:nowrap;overflow:hidden;text-overflow:ellipsis;margin-top:2px;}.db-log-time{font-size:.72rem;color:var(--color-text-muted);margin-top:4px;display:flex;align-items:center;gap:6px;flex-wrap:wrap;}

/* Notifications - Clean */
.db-notif{display:flex;gap:14px;padding:14px 0;border-bottom:1px solid rgba(0,0,0,.03);align-items:flex-start;transition:background .15s;border-radius:8px;margin:0 -8px;padding-left:8px;padding-right:8px;}.db-notif:last-child{border-bottom:none;}.db-notif:hover{background:rgba(37,99,235,.02);}
.db-notif-dot{width:10px;height:10px;border-radius:50%;margin-top:6px;flex-shrink:0;background:var(--db);box-shadow:0 0 0 3px rgba(37,99,235,.15);}.db-notif-dot.read{background:#CBD5E1;box-shadow:none;}
.db-notif-title{font-size:.84rem;font-weight:700;color:var(--color-text);}.db-notif-msg{font-size:.77rem;color:var(--color-text-muted);margin-top:2px;line-height:1.4;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden;}.db-notif-time{font-size:.7rem;color:var(--color-text-muted);margin-top:4px;display:flex;align-items:center;gap:4px;}

/* Empty states */
.db-empty{display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;padding:40px 20px;color:var(--color-text-muted);}.db-empty i{font-size:2.5rem;opacity:.3;margin-bottom:12px;}.db-empty-msg{font-size:.9rem;font-weight:600;color:var(--color-text-secondary);}

/* Health indicators */
.db-health{display:flex;gap:14px;flex-wrap:wrap;margin-top:8px;}.db-health-item{display:flex;align-items:center;gap:6px;font-size:.78rem;font-weight:600;color:var(--color-text-secondary);}.db-health-dot{width:9px;height:9px;border-radius:50%;background:#16A34A;box-shadow:0 0 0 2px rgba(22,163,74,.2);}

/* Link buttons */
.db-card-btn,.db-sec-hdr .db-card-btn{font-size:.78rem;font-weight:700;color:var(--db);text-decoration:none;display:inline-flex;align-items:center;gap:4px;transition:gap .2s,color .2s;}.db-card-btn:hover{gap:8px;color:var(--db-dark);}

/* Responsive */
@media(max-width:1279px){.db-cards{grid-template-columns:repeat(2,1fr);}.db-qa-grid{grid-template-columns:repeat(4,1fr);}}
@media(max-width:1023px){.db-row2{grid-template-columns:1fr;}}
@media(max-width:767px){.db-cards{grid-template-columns:1fr 1fr;}.db-qa-grid{grid-template-columns:repeat(3,1fr);}.db-hero-body{flex-direction:column;align-items:flex-start;}.db-hero-title{font-size:1.5rem;}}
@media(max-width:479px){.db-cards{grid-template-columns:1fr;}.db-qa-grid{grid-template-columns:repeat(2,1fr);}}
</style>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="<%: ResolveUrl("~/Scripts/admin-signout.js") %>"></script>
</asp:Content>
<asp:Content ID="cSidebar" ContentPlaceHolderID="SidebarMenu" runat="server">
<div class="sb-nav-section"><div class="sb-nav-section-label">Main</div><a href="<%: ResolveUrl("~/Admin/Dashboard.aspx") %>" class="sb-sidebar-item active"><i class="bi bi-speedometer2 item-icon"></i><span class="item-label">Dashboard</span></a></div>
<div class="sb-nav-section"><div class="sb-nav-section-label">User Management</div><a href="<%: ResolveUrl("~/Admin/StudentManagement.aspx") %>" class="sb-sidebar-item"><i class="bi bi-people item-icon"></i><span class="item-label">Students</span></a><a href="<%: ResolveUrl("~/Admin/ParentManagement.aspx") %>" class="sb-sidebar-item"><i class="bi bi-person-heart item-icon"></i><span class="item-label">Parents</span></a><a href="<%: ResolveUrl("~/Admin/TeacherManagement.aspx") %>" class="sb-sidebar-item"><i class="bi bi-person-badge item-icon"></i><span class="item-label">Teachers</span></a></div>
<div class="sb-nav-section"><div class="sb-nav-section-label">Learning Content</div><a href="<%: ResolveUrl("~/Admin/LessonManagement.aspx") %>" class="sb-sidebar-item"><i class="bi bi-book item-icon"></i><span class="item-label">Lessons</span></a><a href="<%: ResolveUrl("~/Admin/QuizManagement.aspx") %>" class="sb-sidebar-item"><i class="bi bi-patch-question item-icon"></i><span class="item-label">Quizzes</span></a><a href="<%: ResolveUrl("~/Admin/QuestionBank.aspx") %>" class="sb-sidebar-item"><i class="bi bi-question-circle item-icon"></i><span class="item-label">Question Bank</span></a><a href="<%: ResolveUrl("~/Admin/TeacherMaterials.aspx") %>" class="sb-sidebar-item"><i class="bi bi-file-earmark-text item-icon"></i><span class="item-label">Material Requests</span></a><a href="<%: ResolveUrl("~/Admin/LiveSessions.aspx") %>" class="sb-sidebar-item"><i class="bi bi-camera-video item-icon"></i><span class="item-label">Live Sessions</span></a><a href="<%: ResolveUrl("~/Admin/QuestionRequests.aspx") %>" class="sb-sidebar-item"><i class="bi bi-clipboard-check item-icon"></i><span class="item-label">Question Requests</span></a><a href="<%: ResolveUrl("~/Admin/CertificateManagement.aspx") %>" class="sb-sidebar-item"><i class="bi bi-award item-icon"></i><span class="item-label">Certificates</span></a></div>
<div class="sb-nav-section"><div class="sb-nav-section-label">Community</div><a href="<%: ResolveUrl("~/Admin/ForumDiscussions.aspx") %>" class="sb-sidebar-item"><i class="bi bi-chat-dots item-icon"></i><span class="item-label">Forum Discussions</span></a></div>
<div class="sb-nav-section"><div class="sb-nav-section-label">Gamification</div><a href="<%: ResolveUrl("~/Admin/GamificationManagement.aspx") %>" class="sb-sidebar-item"><i class="bi bi-trophy item-icon"></i><span class="item-label">Student Performance</span></a></div>
<div class="sb-nav-section"><div class="sb-nav-section-label">Configuration</div><a href="<%: ResolveUrl("~/Admin/SystemSettings.aspx") %>" class="sb-sidebar-item"><i class="bi bi-gear item-icon"></i><span class="item-label">System Settings</span></a></div>
<div class="sb-nav-section"><div class="sb-nav-section-label">Logs</div><a href="<%: ResolveUrl("~/Admin/SystemActivityLogs.aspx") %>" class="sb-sidebar-item"><i class="bi bi-clock-history item-icon"></i><span class="item-label">Activity Logs</span></a><a href="<%: ResolveUrl("~/Admin/LoginLogs.aspx") %>" class="sb-sidebar-item"><i class="bi bi-box-arrow-in-right item-icon"></i><span class="item-label">Login Logs</span></a><a href="<%: ResolveUrl("~/Admin/SuspiciousLogins.aspx") %>" class="sb-sidebar-item"><i class="bi bi-exclamation-triangle item-icon"></i><span class="item-label">Suspicious Logins</span></a></div>
<div class="sb-nav-section"><div class="sb-nav-section-label">Account</div><a href="<%: ResolveUrl("~/Admin/Notifications.aspx") %>" class="sb-sidebar-item"><i class="bi bi-bell item-icon"></i><span class="item-label">Notifications</span></a><a href="<%: ResolveUrl("~/Admin/Profile.aspx") %>" class="sb-sidebar-item"><i class="bi bi-person item-icon"></i><span class="item-label">My Profile</span></a><a href="javascript:;" class="sb-sidebar-item" onclick="showSignOutModal()"><i class="bi bi-box-arrow-right item-icon"></i><span class="item-label">Sign Out</span></a></div>
</asp:Content>
<asp:Content ID="cPageTitle" ContentPlaceHolderID="PageTitle" runat="server">Admin Dashboard</asp:Content>
<asp:Content ID="cMain" ContentPlaceHolderID="MainContentSidebar" runat="server">
<div class="db-hero"><div class="db-hero-body"><div><div class="db-hero-eyebrow"><i class="bi bi-shield-check"></i> <%= T("Administrator Console", "Konsol Pentadbir") %></div><div class="db-hero-title"><%= T("Welcome back,", "Selamat kembali,") %> <asp:Literal ID="litAdminName" runat="server" Text="Admin" />!</div><div class="db-hero-sub"><%= T("Manage users, monitor learning content, and keep ScienceBuddy running smoothly.", "Urus pengguna, pantau kandungan pembelajaran, dan pastikan ScienceBuddy berjalan lancar.") %></div><div class="db-hero-chips"><span class="db-hero-chip"><i class="bi bi-calendar3"></i> <asp:Literal ID="litDate" runat="server" /></span><span class="db-hero-chip"><i class="bi bi-hourglass-split"></i> <asp:Literal ID="litPendingRequests" runat="server" Text="0" /> <%= T("Pending", "Tertunggak") %></span></div></div><div class="db-hero-actions"><a href="<%: ResolveUrl("~/Admin/QuestionRequests.aspx") %>" class="db-hero-btn primary"><i class="bi bi-clipboard-check"></i> <%= T("Review", "Semak") %></a><a href="<%: ResolveUrl("~/Admin/StudentManagement.aspx") %>" class="db-hero-btn"><i class="bi bi-people"></i> <%= T("Users", "Pengguna") %></a><a href="<%: ResolveUrl("~/Admin/SystemSettings.aspx") %>" class="db-hero-btn"><i class="bi bi-gear"></i> <%= T("Settings", "Tetapan") %></a></div></div></div>
<div class="db-cards">
<div class="db-card c1"><div class="db-card-hdr"><div class="db-card-ico" style="background:#DBEAFE;color:#1D4ED8;"><i class="bi bi-people-fill"></i></div><div class="db-card-title"><%= T("Users", "Pengguna") %></div></div><div class="db-card-grid"><div><div class="db-card-val"><asp:Literal ID="litStudents" runat="server" Text="0" /></div><div class="db-card-lbl"><%= T("Students", "Pelajar") %></div></div><div><div class="db-card-val"><asp:Literal ID="litParents" runat="server" Text="0" /></div><div class="db-card-lbl"><%= T("Parents", "Ibu Bapa") %></div></div><div><div class="db-card-val"><asp:Literal ID="litTeachers" runat="server" Text="0" /></div><div class="db-card-lbl"><%= T("Teachers", "Guru") %></div></div></div><a href="<%: ResolveUrl("~/Admin/StudentManagement.aspx") %>" class="db-card-btn"><%= T("Manage", "Urus") %> <i class="bi bi-arrow-right"></i></a></div>
<div class="db-card c2"><div class="db-card-hdr"><div class="db-card-ico" style="background:#D1FAE5;color:#059669;"><i class="bi bi-collection-fill"></i></div><div class="db-card-title"><%= T("Content", "Kandungan") %></div></div><div class="db-card-grid"><div><div class="db-card-val"><asp:Literal ID="litLessons" runat="server" Text="0" /></div><div class="db-card-lbl"><%= T("Lessons", "Pelajaran") %></div></div><div><div class="db-card-val"><asp:Literal ID="litQuizzes" runat="server" Text="0" /></div><div class="db-card-lbl"><%= T("Quizzes", "Kuiz") %></div></div></div><a href="<%: ResolveUrl("~/Admin/LessonManagement.aspx") %>" class="db-card-btn"><%= T("Manage", "Urus") %> <i class="bi bi-arrow-right"></i></a></div>
<div class="db-card c3"><div class="db-card-hdr"><div class="db-card-ico" style="background:#FEF3C7;color:#D97706;"><i class="bi bi-hourglass-split"></i></div><div class="db-card-title"><%= T("Pending", "Tertunggak") %></div></div><div class="db-card-grid"><div><div class="db-card-val"><asp:Literal ID="litPendingQ" runat="server" Text="0" /></div><div class="db-card-lbl"><%= T("Questions", "Soalan") %></div></div><div><div class="db-card-val"><asp:Literal ID="litPendingM" runat="server" Text="0" /></div><div class="db-card-lbl"><%= T("Materials", "Bahan") %></div></div></div><a href="<%: ResolveUrl("~/Admin/QuestionRequests.aspx") %>" class="db-card-btn"><%= T("Review", "Semak") %> <i class="bi bi-arrow-right"></i></a></div>
<div class="db-card c4"><div class="db-card-hdr"><div class="db-card-ico" style="background:#EDE9FE;color:#7C3AED;"><i class="bi bi-activity"></i></div><div class="db-card-title"><%= T("System", "Sistem") %></div></div><div class="db-health"><div class="db-health-item"><div class="db-health-dot"></div>DB</div><div class="db-health-item"><div class="db-health-dot"></div>Auth</div><div class="db-health-item"><div class="db-health-dot"></div>Notif</div></div><a href="<%: ResolveUrl("~/Admin/SystemSettings.aspx") %>" class="db-card-btn"><%= T("Settings", "Tetapan") %> <i class="bi bi-arrow-right"></i></a></div>
</div>
<div class="db-qa"><div class="db-qa-title"><i class="bi bi-lightning-fill" style="color:#D97706;"></i> <%= T("Quick Actions", "Tindakan Pantas") %></div><div class="db-qa-grid"><a href="<%: ResolveUrl("~/Admin/StudentManagement.aspx") %>" class="db-qa-item"><div class="db-qa-ico" style="background:#DBEAFE;color:#2563EB;"><i class="bi bi-people"></i></div><div class="db-qa-lbl"><%= T("Students","Pelajar") %></div></a><a href="<%: ResolveUrl("~/Admin/QuestionRequests.aspx") %>" class="db-qa-item"><div class="db-qa-ico" style="background:#FEF3C7;color:#D97706;"><i class="bi bi-clipboard-check"></i></div><div class="db-qa-lbl"><%= T("Questions","Soalan") %></div></a><a href="<%: ResolveUrl("~/Admin/TeacherMaterials.aspx") %>" class="db-qa-item"><div class="db-qa-ico" style="background:#FEE2E2;color:#DC2626;"><i class="bi bi-file-earmark-text"></i></div><div class="db-qa-lbl"><%= T("Materials","Bahan") %></div></a><a href="<%: ResolveUrl("~/Admin/QuestionBank.aspx") %>" class="db-qa-item"><div class="db-qa-ico" style="background:#EDE9FE;color:#7C3AED;"><i class="bi bi-database"></i></div><div class="db-qa-lbl"><%= T("Question Bank","Bank Soalan") %></div></a><a href="<%: ResolveUrl("~/Admin/Notifications.aspx") %>" class="db-qa-item"><div class="db-qa-ico" style="background:#CFFAFE;color:#0891B2;"><i class="bi bi-bell"></i></div><div class="db-qa-lbl"><%= T("Notifications","Notifikasi") %></div></a><a href="<%: ResolveUrl("~/Admin/GamificationManagement.aspx") %>" class="db-qa-item"><div class="db-qa-ico" style="background:#D1FAE5;color:#059669;"><i class="bi bi-trophy"></i></div><div class="db-qa-lbl"><%= T("Gamification","Gamifikasi") %></div></a></div></div>
<div class="db-row2">
<div class="db-section"><div class="db-sec-hdr"><div class="db-sec-title"><i class="bi bi-hourglass-split" style="color:#D97706;"></i> <%= T("Pending Requests", "Permintaan Tertunggak") %></div><a href="<%: ResolveUrl("~/Admin/QuestionRequests.aspx") %>" class="db-card-btn"><%= T("View All", "Lihat Semua") %> <i class="bi bi-arrow-right"></i></a></div><div class="db-sec-body"><asp:Panel ID="pnlRequests" runat="server" Visible="false"><table class="sb-table" style="font-size:.8rem;"><thead><tr><th>Type</th><th><%= T("By","Oleh") %></th><th><%= T("Date","Tarikh") %></th><th></th></tr></thead><tbody><asp:Repeater ID="rptRequests" runat="server"><ItemTemplate><tr><td><span class="sb-badge sb-badge-secondary"><%# Eval("requestType") %></span></td><td><%# Eval("requestedBy") %></td><td style="color:var(--color-text-muted);"><%# Eval("requestedDate") %></td><td><a href="<%: ResolveUrl("~/Admin/QuestionRequests.aspx") %>" class="sb-btn sb-btn-primary sb-btn-xs"><%= T("Review","Semak") %></a></td></tr></ItemTemplate></asp:Repeater></tbody></table></asp:Panel><asp:Panel ID="pnlRequestsEmpty" runat="server"><div class="db-empty"><i class="bi bi-check-circle" style="color:#059669;"></i><div class="db-empty-msg"><%= T("No pending requests.","Tiada permintaan tertunggak.") %></div></div></asp:Panel></div></div>
<div class="db-section"><div class="db-sec-hdr"><div class="db-sec-title"><i class="bi bi-bell" style="color:#DC2626;"></i> <%= T("Recent Notifications","Notifikasi Terkini") %></div><a href="<%: ResolveUrl("~/Admin/Notifications.aspx") %>" class="db-card-btn"><%= T("View All","Lihat Semua") %> <i class="bi bi-arrow-right"></i></a></div><div class="db-sec-body"><asp:Panel ID="pnlNotifs" runat="server" Visible="false"><asp:Repeater ID="rptNotifs" runat="server"><ItemTemplate><div class="db-notif"><div class='db-notif-dot <%# Convert.ToBoolean(Eval("isRead")) ? "read" : "" %>'></div><div><div class="db-notif-title"><%# Eval("title") %></div><div class="db-notif-msg"><%# Eval("message") %></div><div class="db-notif-time"><i class="bi bi-clock"></i> <%# Eval("timeAgo") %></div></div></div></ItemTemplate></asp:Repeater></asp:Panel><asp:Panel ID="pnlNotifsEmpty" runat="server"><div class="db-empty"><i class="bi bi-bell-slash" style="color:#94A3B8;"></i><div class="db-empty-msg"><%= T("No notifications.","Tiada notifikasi.") %></div></div></asp:Panel></div></div>
</div>
<div class="db-section" style="margin-bottom:var(--space-xl);"><div class="db-sec-hdr"><div class="db-sec-title"><i class="bi bi-clock-history" style="color:#7C3AED;"></i> <%= T("Recent Activity","Aktiviti Terkini") %></div><a href="<%: ResolveUrl("~/Admin/SystemActivityLogs.aspx") %>" class="db-card-btn"><%= T("View All","Lihat Semua") %> <i class="bi bi-arrow-right"></i></a></div><div class="db-sec-body"><asp:Panel ID="pnlLogs" runat="server" Visible="false"><asp:Repeater ID="rptLogs" runat="server"><ItemTemplate><div class="db-log"><div class="db-log-ico" style='<%# Eval("iconStyle") %>'><i class='<%# Eval("iconClass") %>'></i></div><div class="db-log-body"><div class="db-log-action"><%# Eval("action") %></div><div class="db-log-desc"><%# Eval("description") %></div><div class="db-log-time"><i class="bi bi-person"></i> <%# Eval("username") %> &middot; <%# Eval("timeAgo") %> <%# BuildStatusBadge(Convert.ToString(Eval("status"))) %></div></div></div></ItemTemplate></asp:Repeater></asp:Panel><asp:Panel ID="pnlLogsEmpty" runat="server"><div class="db-empty"><i class="bi bi-clock-history" style="color:#94A3B8;"></i><div class="db-empty-msg"><%= T("No recent activity.","Tiada aktiviti terkini.") %></div></div></asp:Panel></div></div>
</asp:Content>
