//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScienceBuddy.Admin
{
    public partial class Dashboard
    {
        protected global::System.Web.UI.WebControls.Literal litAdminName;
        protected global::System.Web.UI.WebControls.Literal litDate;
        protected global::System.Web.UI.WebControls.Literal litPendingRequests;
        protected global::System.Web.UI.WebControls.Literal litStudents;
        protected global::System.Web.UI.WebControls.Literal litParents;
        protected global::System.Web.UI.WebControls.Literal litTeachers;
        protected global::System.Web.UI.WebControls.Literal litLessons;
        protected global::System.Web.UI.WebControls.Literal litQuizzes;
        protected global::System.Web.UI.WebControls.Literal litQuestions;
        protected global::System.Web.UI.WebControls.Literal litMaterials;
        protected global::System.Web.UI.WebControls.Literal litPendingQ;
        protected global::System.Web.UI.WebControls.Literal litPendingM;
        protected global::System.Web.UI.WebControls.Literal litForumReports;
        protected global::System.Web.UI.WebControls.Panel pnlRequests;
        protected global::System.Web.UI.WebControls.Repeater rptRequests;
        protected global::System.Web.UI.WebControls.Panel pnlRequestsEmpty;
        protected global::System.Web.UI.WebControls.Panel pnlNotifs;
        protected global::System.Web.UI.WebControls.Repeater rptNotifs;
        protected global::System.Web.UI.WebControls.Panel pnlNotifsEmpty;
        protected global::System.Web.UI.WebControls.Panel pnlLogs;
        protected global::System.Web.UI.WebControls.Repeater rptLogs;
        protected global::System.Web.UI.WebControls.Panel pnlLogsEmpty;
    }
}
