<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ForumDiscussions.aspx.cs"
    Inherits="ScienceBuddy.Admin.ForumDiscussions" MasterPageFile="~/Site.Master"
    Title="Forum Discussions" %>

<asp:Content ID="cHead" ContentPlaceHolderID="HeadContent" runat="server">
    <link href="<%: ResolveUrl("~/Content/Admin.css") %>" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css" />
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="<%: ResolveUrl("~/Scripts/admin-signout.js") %>"></script>
</asp:Content>
<asp:Content ID="cSidebar" ContentPlaceHolderID="SidebarMenu" runat="server">
<div class="sb-nav-section"><div class="sb-nav-section-label">Main</div><a href="<%: ResolveUrl("~/Admin/Dashboard.aspx") %>" class="sb-sidebar-item"><i class="bi bi-speedometer2 item-icon"></i><span class="item-label">Dashboard</span></a></div>
<div class="sb-nav-section"><div class="sb-nav-section-label">User Management</div><a href="<%: ResolveUrl("~/Admin/StudentManagement.aspx") %>" class="sb-sidebar-item"><i class="bi bi-people item-icon"></i><span class="item-label">Students</span></a><a href="<%: ResolveUrl("~/Admin/ParentManagement.aspx") %>" class="sb-sidebar-item"><i class="bi bi-person-heart item-icon"></i><span class="item-label">Parents</span></a><a href="<%: ResolveUrl("~/Admin/TeacherManagement.aspx") %>" class="sb-sidebar-item"><i class="bi bi-person-badge item-icon"></i><span class="item-label">Teachers</span></a><a href="<%: ResolveUrl("~/Admin/TeacherCertificateApproval.aspx") %>" class="sb-sidebar-item"><i class="bi bi-patch-check item-icon"></i><span class="item-label">Teacher Certificate Approval</span></a></div>
<div class="sb-nav-section"><div class="sb-nav-section-label">Learning Content</div><a href="<%: ResolveUrl("~/Admin/LessonManagement.aspx") %>" class="sb-sidebar-item"><i class="bi bi-book item-icon"></i><span class="item-label">Lessons</span></a><a href="<%: ResolveUrl("~/Admin/QuizManagement.aspx") %>" class="sb-sidebar-item"><i class="bi bi-patch-question item-icon"></i><span class="item-label">Quizzes</span></a><a href="<%: ResolveUrl("~/Admin/QuestionBank.aspx") %>" class="sb-sidebar-item"><i class="bi bi-question-circle item-icon"></i><span class="item-label">Question Bank</span></a><a href="<%: ResolveUrl("~/Admin/TeacherMaterials.aspx") %>" class="sb-sidebar-item"><i class="bi bi-file-earmark-text item-icon"></i><span class="item-label">Material Requests</span></a><a href="<%: ResolveUrl("~/Admin/LiveSessions.aspx") %>" class="sb-sidebar-item"><i class="bi bi-camera-video item-icon"></i><span class="item-label">Live Sessions</span></a><a href="<%: ResolveUrl("~/Admin/QuestionRequests.aspx") %>" class="sb-sidebar-item"><i class="bi bi-clipboard-check item-icon"></i><span class="item-label">Question Requests</span></a><a href="<%: ResolveUrl("~/Admin/CertificateManagement.aspx") %>" class="sb-sidebar-item"><i class="bi bi-award item-icon"></i><span class="item-label">Certificates</span></a></div>
<div class="sb-nav-section"><div class="sb-nav-section-label">Community</div><a href="<%: ResolveUrl("~/Admin/ForumDiscussions.aspx") %>" class="sb-sidebar-item active"><i class="bi bi-chat-dots item-icon"></i><span class="item-label">Forum Discussions</span></a></div>
<div class="sb-nav-section"><div class="sb-nav-section-label">Gamification</div><a href="<%: ResolveUrl("~/Admin/GamificationManagement.aspx") %>" class="sb-sidebar-item"><i class="bi bi-trophy item-icon"></i><span class="item-label">Student Performance</span></a></div>
<div class="sb-nav-section"><div class="sb-nav-section-label">Configuration</div><a href="<%: ResolveUrl("~/Admin/SystemSettings.aspx") %>" class="sb-sidebar-item"><i class="bi bi-gear item-icon"></i><span class="item-label">System Settings</span></a></div>
<div class="sb-nav-section"><div class="sb-nav-section-label">Logs</div><a href="<%: ResolveUrl("~/Admin/SystemActivityLogs.aspx") %>" class="sb-sidebar-item"><i class="bi bi-clock-history item-icon"></i><span class="item-label">Activity Logs</span></a><a href="<%: ResolveUrl("~/Admin/LoginLogs.aspx") %>" class="sb-sidebar-item"><i class="bi bi-box-arrow-in-right item-icon"></i><span class="item-label">Login Logs</span></a><a href="<%: ResolveUrl("~/Admin/SuspiciousLogins.aspx") %>" class="sb-sidebar-item"><i class="bi bi-exclamation-triangle item-icon"></i><span class="item-label">Suspicious Logins</span></a></div>
<div class="sb-nav-section"><div class="sb-nav-section-label">Account</div><a href="<%: ResolveUrl("~/Admin/Notifications.aspx") %>" class="sb-sidebar-item"><i class="bi bi-bell item-icon"></i><span class="item-label">Notifications</span></a><a href="<%: ResolveUrl("~/Admin/Profile.aspx") %>" class="sb-sidebar-item"><i class="bi bi-person item-icon"></i><span class="item-label">My Profile</span></a><a href="javascript:;" class="sb-sidebar-item" onclick="showSignOutModal()"><i class="bi bi-box-arrow-right item-icon"></i><span class="item-label">Sign Out</span></a></div>
</asp:Content>
<asp:Content ID="cPageTitle" ContentPlaceHolderID="PageTitle" runat="server"><%= T("Forum Discussions", "Perbincangan Forum") %></asp:Content>
<asp:Content ID="cMain" ContentPlaceHolderID="MainContentSidebar" runat="server">
<div class="ad-forum-discussions-hdr"><div><div class="ad-forum-discussions-hdr-title"><i class="bi bi-chat-dots-fill" style="color:var(--ad-forum-discussions-accent);"></i> <%= T("Forum Discussions", "Perbincangan Forum") %></div><div class="ad-forum-discussions-hdr-sub"><%= T("Monitor and moderate all community discussions in ScienceBuddy.", "Pantau dan moderasi semua perbincangan komuniti dalam ScienceBuddy.") %></div></div></div>
<div class="ad-forum-discussions-stats">
<div class="ad-forum-discussions-stat s1"><div class="ad-forum-discussions-stat-ico" style="background:#F5F3FF;color:#8B5CF6;"><i class="bi bi-chat-square-text-fill"></i></div><div><div class="ad-forum-discussions-stat-val"><asp:Literal ID="litTotal" runat="server" Text="0" /></div><div class="ad-forum-discussions-stat-lbl"><%= T("Total Discussions", "Jumlah Perbincangan") %></div></div></div>
<div class="ad-forum-discussions-stat s2"><div class="ad-forum-discussions-stat-ico" style="background:#DBEAFE;color:#2563EB;"><i class="bi bi-globe"></i></div><div><div class="ad-forum-discussions-stat-val"><asp:Literal ID="litPublic" runat="server" Text="0" /></div><div class="ad-forum-discussions-stat-lbl"><%= T("Public", "Awam") %></div></div></div>
<div class="ad-forum-discussions-stat s3"><div class="ad-forum-discussions-stat-ico" style="background:#D1FAE5;color:#059669;"><i class="bi bi-lock-fill"></i></div><div><div class="ad-forum-discussions-stat-val"><asp:Literal ID="litPrivate" runat="server" Text="0" /></div><div class="ad-forum-discussions-stat-lbl"><%= T("Private", "Persendirian") %></div></div></div>
<div class="ad-forum-discussions-stat s4"><div class="ad-forum-discussions-stat-ico" style="background:#FEF3C7;color:#D97706;"><i class="bi bi-calendar-check"></i></div><div><div class="ad-forum-discussions-stat-val"><asp:Literal ID="litToday" runat="server" Text="0" /></div><div class="ad-forum-discussions-stat-lbl"><%= T("Today", "Hari Ini") %></div></div></div>
</div>
<div class="ad-forum-discussions-toolbar"><div class="ad-forum-discussions-search"><i class="bi bi-search"></i><asp:TextBox ID="txtSearch" runat="server" CssClass="form-control" /></div>
<asp:DropDownList ID="ddlType" runat="server" CssClass="ad-forum-discussions-filter"><asp:ListItem Value="" Text="All Types" /><asp:ListItem Value="Public" Text="Public" /><asp:ListItem Value="Private" Text="Private" /></asp:DropDownList>
<asp:DropDownList ID="ddlSort" runat="server" CssClass="ad-forum-discussions-filter"><asp:ListItem Value="newest" Text="Newest" /><asp:ListItem Value="oldest" Text="Oldest" /></asp:DropDownList>
<asp:Button ID="btnSearch" runat="server" Text="Search" CssClass="sb-btn sb-btn-primary sb-btn-sm" OnClick="btnSearch_Click" />
<asp:Button ID="btnReset" runat="server" Text="Reset" CssClass="sb-btn sb-btn-ghost sb-btn-sm" OnClick="btnReset_Click" /></div>
<div class="ad-forum-discussions-grid"><asp:Repeater ID="rptForums" runat="server"><ItemTemplate>
<div class="ad-forum-discussions-card"><div class="ad-forum-discussions-card-top"><span class="ad-forum-discussions-card-id"><%# Eval("forumId") %></span><span class='<%# Eval("typeCls") %>'><%# Eval("discussionType") %></span></div>
<div class="ad-forum-discussions-card-title"><%# HttpUtility.HtmlEncode(Eval("title")) %></div>
<div class="ad-forum-discussions-card-msg"><%# HttpUtility.HtmlEncode(Eval("messagePreview")) %></div>
<div class="ad-forum-discussions-card-meta"><span><i class="bi bi-person"></i> <%# Eval("username") %></span><span><i class="bi bi-tag"></i> <%# Eval("role") %></span><span><i class="bi bi-calendar3"></i> <%# Eval("createdAt") %></span></div>
<div class="ad-forum-discussions-card-actions">
<a href="javascript:;" class="ad-forum-discussions-abtn ad-forum-discussions-abtn-view" data-json='<%# HttpUtility.HtmlAttributeEncode(Eval("jsonData").ToString()) %>' onclick="viewForum(JSON.parse(this.getAttribute('data-json')))"><i class="bi bi-eye"></i> <%= T("View","Lihat") %></a>
<a href="javascript:;" class="ad-forum-discussions-abtn ad-forum-discussions-abtn-delete" onclick="deleteForum('<%# Eval("forumId") %>','<%# Eval("createdByUserId") %>')"><i class="bi bi-trash"></i> <%= T("Delete","Padam") %></a>
</div></div>
</ItemTemplate></asp:Repeater></div>
<asp:Panel ID="pnlEmpty" runat="server" Visible="false"><div class="ad-forum-discussions-empty"><i class="bi bi-chat-square-text"></i><div style="font-size:1rem;font-weight:600;color:var(--color-text-secondary);"><%= T("No discussions found.", "Tiada perbincangan dijumpai.") %></div></div></asp:Panel>
<div class="ad-forum-discussions-overlay" id="fdModal"><div class="ad-forum-discussions-modal"><div class="ad-forum-discussions-modal-hdr"><span class="ad-forum-discussions-modal-title"><i class="bi bi-chat-dots" style="color:var(--ad-forum-discussions-accent);"></i> <%= T("Discussion Details","Butiran Perbincangan") %></span><button class="ad-forum-discussions-modal-close" onclick="document.getElementById('fdModal').classList.remove('active')"><i class="bi bi-x-lg"></i></button></div><div class="ad-forum-discussions-modal-body" id="fdModalBody"></div></div></div>
<script>
function viewForum(d){var h='';h+='<div class="ad-forum-discussions-detail"><div class="ad-forum-discussions-detail-label">Forum ID</div><div class="ad-forum-discussions-detail-value">'+d.id+'</div></div>';h+='<div class="ad-forum-discussions-detail"><div class="ad-forum-discussions-detail-label"><%= T("Title","Tajuk") %></div><div class="ad-forum-discussions-detail-value">'+d.title+'</div></div>';h+='<div class="ad-forum-discussions-detail"><div class="ad-forum-discussions-detail-label"><%= T("Message","Mesej") %></div><div class="ad-forum-discussions-detail-value" style="white-space:pre-wrap;">'+d.message+'</div></div>';h+='<div class="ad-forum-discussions-detail"><div class="ad-forum-discussions-detail-label"><%= T("Author","Penulis") %></div><div class="ad-forum-discussions-detail-value">'+d.username+' ('+d.role+')</div></div>';h+='<div class="ad-forum-discussions-detail"><div class="ad-forum-discussions-detail-label"><%= T("Type","Jenis") %></div><div class="ad-forum-discussions-detail-value">'+d.type+'</div></div>';h+='<div class="ad-forum-discussions-detail"><div class="ad-forum-discussions-detail-label"><%= T("Created","Dicipta") %></div><div class="ad-forum-discussions-detail-value">'+d.date+'</div></div>';document.getElementById('fdModalBody').innerHTML=h;document.getElementById('fdModal').classList.add('active');
fetch(window.location.pathname + (window.location.pathname.indexOf('.aspx') === -1 ? '.aspx' : '') + '?handler=ForumAction&action=view&forumId='+d.id,{method:'POST',headers:{'X-Requested-With':'XMLHttpRequest'}});}
function deleteForum(fId,uid){Swal.fire({title:'<%= T("Delete Discussion?","Padam Perbincangan?") %>',text:'<%= T("This discussion will be permanently removed.","Perbincangan ini akan dipadam secara kekal.") %>',icon:'warning',showCancelButton:true,confirmButtonText:'<%= T("Delete","Padam") %>',confirmButtonColor:'#DC2626',cancelButtonText:'<%= T("Cancel","Batal") %>'}).then(function(r){if(!r.isConfirmed)return;fetch(window.location.pathname + (window.location.pathname.indexOf('.aspx') === -1 ? '.aspx' : '') + '?handler=ForumAction&action=delete&forumId='+fId+'&uid='+uid,{method:'POST',headers:{'X-Requested-With':'XMLHttpRequest'}}).then(function(r){return r.json();}).then(function(d){if(d.success){Swal.fire({icon:'success',title:'<%= T("Deleted!","Dipadam!") %>',timer:2000,timerProgressBar:true}).then(function(){location.reload();});}else Swal.fire({icon:'error',title:'Error',text:d.msg});});});}
</script>
</asp:Content>
