//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ScienceBuddy.Admin
{
    public partial class GamificationManagement
    {
        protected global::System.Web.UI.WebControls.LinkButton tabOverview;
        protected global::System.Web.UI.WebControls.LinkButton tabXP;
        protected global::System.Web.UI.WebControls.LinkButton tabBadges;
        protected global::System.Web.UI.WebControls.LinkButton tabStudents;
        protected global::System.Web.UI.WebControls.Panel pnlOverview;
        protected global::System.Web.UI.WebControls.Literal litRules;
        protected global::System.Web.UI.WebControls.Literal litTotalXP;
        protected global::System.Web.UI.WebControls.Literal litCerts;
        protected global::System.Web.UI.WebControls.Literal litActiveStudents;
        protected global::System.Web.UI.WebControls.Repeater rptXPActions;
        protected global::System.Web.UI.WebControls.Panel pnlLeaderboard;
        protected global::System.Web.UI.WebControls.Repeater rptLeaderboard;
        protected global::System.Web.UI.WebControls.Panel pnlNoLeaderboard;
        protected global::System.Web.UI.WebControls.Panel pnlXPTab;
        protected global::System.Web.UI.WebControls.Repeater rptXPTab;
        protected global::System.Web.UI.WebControls.Panel pnlBadgesTab;
        protected global::System.Web.UI.WebControls.Repeater rptBadges;
        protected global::System.Web.UI.WebControls.Panel pnlStudentsTab;
        protected global::System.Web.UI.WebControls.Repeater rptStudentRewards;
    }
}
