//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ScienceBuddy.Admin
{
    public partial class LiveSessions
    {
        protected global::System.Web.UI.WebControls.Literal litTotalSessions;
        protected global::System.Web.UI.WebControls.Literal litUpcoming;
        protected global::System.Web.UI.WebControls.Literal litCompleted;
        protected global::System.Web.UI.WebControls.Literal litTeachers;
        protected global::System.Web.UI.WebControls.Literal litAttendance;
        protected global::System.Web.UI.WebControls.Literal litAvgAttendance;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
        protected global::System.Web.UI.WebControls.DropDownList ddlTeacher;
        protected global::System.Web.UI.WebControls.DropDownList ddlUnit;
        protected global::System.Web.UI.WebControls.Button btnSearch;
        protected global::System.Web.UI.WebControls.Button btnReset;
        protected global::System.Web.UI.WebControls.Panel pnlSessions;
        protected global::System.Web.UI.WebControls.Repeater rptSessions;
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
        protected global::System.Web.UI.WebControls.Panel pnlModal;
        protected global::System.Web.UI.WebControls.Literal litMTitle;
        protected global::System.Web.UI.WebControls.Literal litMDesc;
        protected global::System.Web.UI.WebControls.Literal litMTeacher;
        protected global::System.Web.UI.WebControls.Literal litMUnit;
        protected global::System.Web.UI.WebControls.Literal litMSchedule;
        protected global::System.Web.UI.WebControls.Literal litMLink;
        protected global::System.Web.UI.WebControls.Literal litMStatus;
        protected global::System.Web.UI.WebControls.Literal litMCount;
        protected global::System.Web.UI.WebControls.Panel pnlParticipants;
        protected global::System.Web.UI.WebControls.Repeater rptParticipants;
        protected global::System.Web.UI.WebControls.Panel pnlNoParticipants;
        protected global::System.Web.UI.WebControls.Button btnCloseModal;
    }
}
