//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ScienceBuddy.Admin
{
    public partial class LoginLogs
    {
        protected global::System.Web.UI.WebControls.Literal litSuccess;
        protected global::System.Web.UI.WebControls.Literal litFailed;
        protected global::System.Web.UI.WebControls.Literal litLocked;
        protected global::System.Web.UI.WebControls.Literal litSuspicious;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.DropDownList ddlAction;
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
        protected global::System.Web.UI.WebControls.Button btnSearch;
        protected global::System.Web.UI.WebControls.Button btnReset;
        protected global::System.Web.UI.WebControls.Panel pnlLogs;
        protected global::System.Web.UI.WebControls.Repeater rptLogs;
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
        protected global::System.Web.UI.WebControls.Panel pnlModal;
        protected global::System.Web.UI.WebControls.Literal litMLogId;
        protected global::System.Web.UI.WebControls.Literal litMUser;
        protected global::System.Web.UI.WebControls.Literal litMAction;
        protected global::System.Web.UI.WebControls.Literal litMDesc;
        protected global::System.Web.UI.WebControls.Literal litMStatus;
        protected global::System.Web.UI.WebControls.Literal litMDate;
        protected global::System.Web.UI.WebControls.Button btnCloseModal;
    }
}
