//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScienceBuddy.Admin
{
    public partial class Notifications
    {
        protected global::System.Web.UI.WebControls.DropDownList ddlRecipient;
        protected global::System.Web.UI.WebControls.Panel pnlIndividual;
        protected global::System.Web.UI.WebControls.DropDownList ddlUser;
        protected global::System.Web.UI.WebControls.TextBox txtTitleEN;
        protected global::System.Web.UI.WebControls.TextBox txtTitleBM;
        protected global::System.Web.UI.WebControls.TextBox txtMsgEN;
        protected global::System.Web.UI.WebControls.TextBox txtMsgBM;
        protected global::System.Web.UI.WebControls.Button btnSend;
        protected global::System.Web.UI.WebControls.Label lblSendMsg;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.DropDownList ddlFilter;
        protected global::System.Web.UI.WebControls.Button btnSearch;
        protected global::System.Web.UI.WebControls.Button btnReset;
        protected global::System.Web.UI.WebControls.Panel pnlSent;
        protected global::System.Web.UI.WebControls.Repeater rptSent;
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
        protected global::System.Web.UI.WebControls.Panel pnlToast;
        protected global::System.Web.UI.WebControls.Literal litToast;
        protected global::System.Web.UI.WebControls.Panel pnlModal;
        protected global::System.Web.UI.WebControls.Literal litMNotifId;
        protected global::System.Web.UI.WebControls.Literal litMId;
        protected global::System.Web.UI.WebControls.Literal litMRecipientName;
        protected global::System.Web.UI.WebControls.Literal litMRecipientUsername;
        protected global::System.Web.UI.WebControls.Literal litMRecipientRole;
        protected global::System.Web.UI.WebControls.Literal litMStatus;
        protected global::System.Web.UI.WebControls.Literal litMDateSent;
        protected global::System.Web.UI.WebControls.Literal litMIconTitle;
        protected global::System.Web.UI.WebControls.Literal litMTitleBM;
        protected global::System.Web.UI.WebControls.Literal litMMsgEN;
        protected global::System.Web.UI.WebControls.Literal litMMsgBM;
        protected global::System.Web.UI.WebControls.Button btnCloseModal;
    }
}
