//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScienceBuddy.Admin
{
    public partial class ParentManagement
    {
        protected global::System.Web.UI.WebControls.Literal litTotal;
        protected global::System.Web.UI.WebControls.Literal litLinked;
        protected global::System.Web.UI.WebControls.Literal litDiscuss;
        protected global::System.Web.UI.WebControls.Literal litActive;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
        protected global::System.Web.UI.WebControls.DropDownList ddlLang;
        protected global::System.Web.UI.WebControls.DropDownList ddlSort;
        protected global::System.Web.UI.WebControls.Button btnSearch;
        protected global::System.Web.UI.WebControls.Button btnReset;
        protected global::System.Web.UI.WebControls.Panel pnlParents;
        protected global::System.Web.UI.WebControls.Repeater rptParents;
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
        // Profile modal
        protected global::System.Web.UI.WebControls.Panel pnlProfileModal;
        protected global::System.Web.UI.WebControls.Literal litModalInitials;
        protected global::System.Web.UI.WebControls.Literal litModalName;
        protected global::System.Web.UI.WebControls.Literal litModalUsername;
        protected global::System.Web.UI.WebControls.Literal litModalChildren;
        protected global::System.Web.UI.WebControls.Literal litModalForums;
        protected global::System.Web.UI.WebControls.Literal litModalLang;
        protected global::System.Web.UI.WebControls.Literal litModalEmail;
        protected global::System.Web.UI.WebControls.Literal litModalPhone;
        protected global::System.Web.UI.WebControls.Literal litModalStatus;
        protected global::System.Web.UI.WebControls.Button btnCloseProfile;
        // Children modal
        protected global::System.Web.UI.WebControls.Panel pnlChildrenModal;
        protected global::System.Web.UI.WebControls.LinkButton lnkCloseChildren;
        protected global::System.Web.UI.WebControls.Panel pnlChildrenList;
        protected global::System.Web.UI.WebControls.Repeater rptChildren;
        protected global::System.Web.UI.WebControls.Panel pnlNoChildren;
    }
}
