<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ParentDetails.aspx.cs"
    Inherits="ScienceBuddy.Admin.ParentDetails" MasterPageFile="~/Site.Master"
    Title="Parent Details" %>

<asp:Content ID="cHead" ContentPlaceHolderID="HeadContent" runat="server">
    <link href="<%: ResolveUrl("~/Content/Admin.css") %>" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css" />
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="<%: ResolveUrl("~/Scripts/signout.js") %>"></script>
</asp:Content>

<asp:Content ID="cSidebar" ContentPlaceHolderID="SidebarMenu" runat="server">
    <div class="sb-nav-section"><div class="sb-nav-section-label"><%= T("Main", "Utama") %></div><a href="<%: ResolveUrl("~/Admin/Dashboard.aspx") %>" class="sb-sidebar-item"><i class="bi bi-speedometer2 item-icon"></i><span class="item-label"><%= T("Dashboard", "Papan Pemuka") %></span></a></div>
    <div class="sb-nav-section"><div class="sb-nav-section-label"><%= T("User Management", "Pengurusan Pengguna") %></div><a href="<%: ResolveUrl("~/Admin/StudentManagement.aspx") %>" class="sb-sidebar-item"><i class="bi bi-people item-icon"></i><span class="item-label"><%= T("Students", "Pelajar") %></span></a><a href="<%: ResolveUrl("~/Admin/ParentManagement.aspx") %>" class="sb-sidebar-item active"><i class="bi bi-person-heart item-icon"></i><span class="item-label"><%= T("Parents", "Ibu Bapa") %></span></a><a href="<%: ResolveUrl("~/Admin/TeacherManagement.aspx") %>" class="sb-sidebar-item"><i class="bi bi-person-badge item-icon"></i><span class="item-label"><%= T("Teachers", "Guru") %></span></a><a href="<%: ResolveUrl("~/Admin/TeacherCertificateApproval.aspx") %>" class="sb-sidebar-item"><i class="bi bi-patch-check item-icon"></i><span class="item-label"><%= T("Teacher Certificate Approval", "Kelulusan Sijil Guru") %></span></a></div>
    <div class="sb-nav-section"><div class="sb-nav-section-label"><%= T("Learning Content", "Kandungan Pembelajaran") %></div><a href="<%: ResolveUrl("~/Admin/LessonManagement.aspx") %>" class="sb-sidebar-item"><i class="bi bi-book item-icon"></i><span class="item-label"><%= T("Lessons", "Pelajaran") %></span></a><a href="<%: ResolveUrl("~/Admin/QuizManagement.aspx") %>" class="sb-sidebar-item"><i class="bi bi-patch-question item-icon"></i><span class="item-label"><%= T("Quizzes", "Kuiz") %></span></a><a href="<%: ResolveUrl("~/Admin/QuestionBank.aspx") %>" class="sb-sidebar-item"><i class="bi bi-question-circle item-icon"></i><span class="item-label"><%= T("Question Bank", "Bank Soalan") %></span></a><a href="<%: ResolveUrl("~/Admin/TeacherMaterials.aspx") %>" class="sb-sidebar-item"><i class="bi bi-file-earmark-text item-icon"></i><span class="item-label"><%= T("Material Requests", "Permintaan Bahan") %></span></a><a href="<%: ResolveUrl("~/Admin/LiveSessions.aspx") %>" class="sb-sidebar-item"><i class="bi bi-camera-video item-icon"></i><span class="item-label"><%= T("Live Sessions", "Sesi Langsung") %></span></a><a href="<%: ResolveUrl("~/Admin/QuestionRequests.aspx") %>" class="sb-sidebar-item"><i class="bi bi-clipboard-check item-icon"></i><span class="item-label"><%= T("Quiz Requests", "Permintaan Kuiz") %></span></a><a href="<%: ResolveUrl("~/Admin/CertificateManagement.aspx") %>" class="sb-sidebar-item"><i class="bi bi-award item-icon"></i><span class="item-label"><%= T("Certificates", "Sijil") %></span></a></div>
    <div class="sb-nav-section"><div class="sb-nav-section-label"><%= T("Community", "Komuniti") %></div><a href="<%: ResolveUrl("~/Admin/ForumDiscussions.aspx") %>" class="sb-sidebar-item"><i class="bi bi-chat-dots item-icon"></i><span class="item-label"><%= T("Forum Discussions", "Perbincangan Forum") %></span></a></div>
    <div class="sb-nav-section"><div class="sb-nav-section-label"><%= T("Gamification", "Gamifikasi") %></div><a href="<%: ResolveUrl("~/Admin/GamificationManagement.aspx") %>" class="sb-sidebar-item"><i class="bi bi-trophy item-icon"></i><span class="item-label"><%= T("Student Performance", "Prestasi Pelajar") %></span></a></div>
    <div class="sb-nav-section"><div class="sb-nav-section-label"><%= T("Configuration", "Konfigurasi") %></div><a href="<%: ResolveUrl("~/Admin/SystemSettings.aspx") %>" class="sb-sidebar-item"><i class="bi bi-gear item-icon"></i><span class="item-label"><%= T("System Settings", "Tetapan Sistem") %></span></a></div>
    <div class="sb-nav-section"><div class="sb-nav-section-label"><%= T("Logs", "Log") %></div><a href="<%: ResolveUrl("~/Admin/SystemActivityLogs.aspx") %>" class="sb-sidebar-item"><i class="bi bi-clock-history item-icon"></i><span class="item-label"><%= T("Activity Logs", "Log Aktiviti") %></span></a><a href="<%: ResolveUrl("~/Admin/LoginLogs.aspx") %>" class="sb-sidebar-item"><i class="bi bi-box-arrow-in-right item-icon"></i><span class="item-label"><%= T("Login Logs", "Log Log Masuk") %></span></a><a href="<%: ResolveUrl("~/Admin/SuspiciousLogins.aspx") %>" class="sb-sidebar-item"><i class="bi bi-exclamation-triangle item-icon"></i><span class="item-label"><%= T("Suspicious Logins", "Log Masuk Mencurigakan") %></span></a></div>
    <div class="sb-nav-section"><div class="sb-nav-section-label"><%= T("Account", "Akaun") %></div><a href="<%: ResolveUrl("~/Admin/Notifications.aspx") %>" class="sb-sidebar-item"><i class="bi bi-bell item-icon"></i><span class="item-label"><%= T("Notifications", "Notifikasi") %></span></a><a href="<%: ResolveUrl("~/Admin/Profile.aspx") %>" class="sb-sidebar-item"><i class="bi bi-person item-icon"></i><span class="item-label"><%= T("My Profile", "Profil Saya") %></span></a><a href="javascript:;" class="sb-sidebar-item" onclick="showSignOutModal()"><i class="bi bi-box-arrow-right item-icon"></i><span class="item-label"><%= T("Sign Out", "Log Keluar") %></span></a></div>
</asp:Content>

<asp:Content ID="cPageTitle" ContentPlaceHolderID="PageTitle" runat="server">Parent Details</asp:Content>
<asp:Content ID="cMain" ContentPlaceHolderID="MainContentSidebar" runat="server">
<a href="<%: ResolveUrl("~/Admin/ParentManagement.aspx") %>" class="ad-parent-details-back"><i class="bi bi-arrow-left"></i> <%= T("Back to Parents", "Kembali ke Ibu Bapa") %></a>
<div class="ad-parent-details-profile">
    <div class="ad-parent-details-avatar"><asp:Literal ID="litInitials" runat="server" /></div>
    <div class="ad-parent-details-info"><div class="ad-parent-details-name"><asp:Literal ID="litName" runat="server" /></div><div class="ad-parent-details-meta"><span><i class="bi bi-hash"></i> <asp:Literal ID="litParentId" runat="server" /></span><span><i class="bi bi-person"></i> <asp:Literal ID="litUsername" runat="server" /></span><span><i class="bi bi-envelope"></i> <asp:Literal ID="litEmail" runat="server" /></span><span><asp:Literal ID="litStatusBadge" runat="server" /></span></div></div>
    <div class="ad-parent-details-quick"><div class="ad-parent-details-quick-item"><div class="ad-parent-details-quick-val"><asp:Literal ID="litChildren" runat="server" Text="0" /></div><div class="ad-parent-details-quick-lbl"><%= T("Children","Anak") %></div></div></div>
</div>
<div class="ad-parent-details-tabs">
    <div class="ad-parent-details-tab active" onclick="switchTab('profile')"><i class="bi bi-person"></i> <%= T("Profile","Profil") %></div>
    <div class="ad-parent-details-tab" onclick="switchTab('account')"><i class="bi bi-gear"></i> <%= T("Account","Akaun") %></div>
    <div class="ad-parent-details-tab" onclick="switchTab('activity')"><i class="bi bi-clock-history"></i> <%= T("Activity","Aktiviti") %></div>
</div>
<div class="ad-parent-details-panel active" id="tab-profile"><asp:Literal ID="litProfileFields" runat="server" /><div class="ad-parent-details-actions"><a href="javascript:;" class="ad-parent-details-btn ad-parent-details-btn-primary" onclick="editProfile()"><i class="bi bi-pencil"></i> <%= T("Edit Profile","Sunting Profil") %></a></div></div>
<div class="ad-parent-details-panel" id="tab-account"><asp:Literal ID="litAccountFields" runat="server" /><div class="ad-parent-details-actions"><a href="javascript:;" class="ad-parent-details-btn ad-parent-details-btn-success" id="btnActivate" onclick="changeStatus('Active')"><i class="bi bi-check-circle"></i> <%= T("Activate","Aktifkan") %></a><a href="javascript:;" class="ad-parent-details-btn ad-parent-details-btn-warning" id="btnBlock" onclick="changeStatus('Blocked')"><i class="bi bi-slash-circle"></i> <%= T("Block","Sekat") %></a><a href="javascript:;" class="ad-parent-details-btn" onclick="resetPassword()"><i class="bi bi-key"></i> <%= T("Reset Password","Tetapkan Semula Kata Laluan") %></a></div></div>
<div class="ad-parent-details-panel" id="tab-activity"><asp:Literal ID="litActivityLog" runat="server" /></div>
<asp:HiddenField ID="hfParentId" runat="server" /><asp:HiddenField ID="hfUserId" runat="server" /><asp:HiddenField ID="hfStatus" runat="server" />
<script>
var parentId=document.getElementById('<%= hfParentId.ClientID %>').value;
var basePath=window.location.pathname;
var currentStatus=document.getElementById('<%= hfStatus.ClientID %>').value;
var userEmail='<%= litEmail.Text %>';
function switchTab(t){document.querySelectorAll('.ad-parent-details-tab').forEach(function(x){x.classList.remove('active');});document.querySelectorAll('.ad-parent-details-panel').forEach(function(p){p.classList.remove('active');});event.currentTarget.classList.add('active');document.getElementById('tab-'+t).classList.add('active');}
function editProfile(){Swal.fire({title:'<%= T("Edit Profile","Sunting Profil") %>',html:'<div style="text-align:left;"><label style="font-size:.75rem;font-weight:600;display:block;margin-bottom:4px;">Name</label><input id="sN" class="swal2-input" style="width:100%;margin:0 0 12px;"/><label style="font-size:.75rem;font-weight:600;display:block;margin-bottom:4px;">Email</label><input id="sE" class="swal2-input" style="width:100%;margin:0 0 12px;"/><label style="font-size:.75rem;font-weight:600;display:block;margin-bottom:4px;">Phone</label><input id="sP" class="swal2-input" style="width:100%;margin:0;"/></div>',showCancelButton:true,confirmButtonText:'<%= T("Save","Simpan") %>',confirmButtonColor:'#059669',didOpen:function(){fetch(basePath+'?handler=ParentCRUD&action=get&parentId='+parentId,{method:'POST'}).then(function(r){return r.json();}).then(function(d){if(d.success){document.getElementById('sN').value=d.data.name;document.getElementById('sE').value=d.data.email;document.getElementById('sP').value=d.data.phone;}});}}).then(function(r){if(!r.isConfirmed)return;fetch(basePath+'?handler=ParentCRUD&action=edit&parentId='+parentId+'&name='+encodeURIComponent(document.getElementById('sN').value)+'&email='+encodeURIComponent(document.getElementById('sE').value)+'&phone='+encodeURIComponent(document.getElementById('sP').value),{method:'POST'}).then(function(r){return r.json();}).then(function(d){if(d.success){Swal.fire({icon:'success',title:'<%= T("Updated!","Dikemas Kini!") %>',timer:2000,timerProgressBar:true}).then(function(){location.reload();});}else Swal.fire({icon:'error',title:'Error',text:d.msg});});});}
function changeStatus(s){if(s==='Active'&&currentStatus==='Active')return;if(s==='Blocked'&&currentStatus==='Blocked')return;
var isBlock=s==='Blocked';
var titleText=isBlock?'<%= T("Block Account & Send Email","Sekat Akaun & Hantar E-mel") %>':'<%= T("Activate Account & Send Email","Aktifkan Akaun & Hantar E-mel") %>';
var subjectText=isBlock?'<%= T("Your ScienceBuddy Account Has Been Blocked","Akaun ScienceBuddy Anda Telah Disekat") %>':'<%= T("Your ScienceBuddy Account Has Been Reactivated","Akaun ScienceBuddy Anda Telah Diaktifkan Semula") %>';
var iconColor=isBlock?'#DC2626':'#059669';
var htmlContent='<div style="text-align:left;font-size:.875rem;"><div style="background:#F8FAFC;border:1px solid #E2E8F0;border-radius:12px;padding:16px 20px;margin-bottom:16px;"><div style="display:flex;align-items:center;gap:8px;margin-bottom:12px;color:#64748B;font-size:.75rem;font-weight:700;text-transform:uppercase;letter-spacing:.5px;"><i class="bi bi-envelope-fill" style="color:'+iconColor+';"></i> <%= T("Email Notification","Notifikasi E-mel") %></div><div style="margin-bottom:10px;"><span style="font-size:.7rem;font-weight:600;color:#94A3B8;"><%= T("TO","KEPADA") %></span><div style="font-size:.85rem;font-weight:600;color:#334155;padding:6px 12px;background:#fff;border:1px solid #E2E8F0;border-radius:8px;margin-top:2px;">'+userEmail+'</div></div><div style="margin-bottom:10px;"><span style="font-size:.7rem;font-weight:600;color:#94A3B8;"><%= T("SUBJECT","SUBJEK") %></span><div style="font-size:.85rem;font-weight:600;color:#334155;padding:6px 12px;background:#fff;border:1px solid #E2E8F0;border-radius:8px;margin-top:2px;">'+subjectText+'</div></div><div><span style="font-size:.7rem;font-weight:600;color:#94A3B8;"><%= T("REASON / MESSAGE","ALASAN / MESEJ") %></span></div></div><textarea id="swalReasonInput" placeholder="<%= T("Type the reason here... This will be included in the email sent to the user.","Taip alasan di sini... Ini akan disertakan dalam e-mel yang dihantar kepada pengguna.") %>" style="width:100%;min-height:100px;padding:12px 16px;border:1.5px solid #E2E8F0;border-radius:10px;font-size:.875rem;font-family:inherit;resize:vertical;transition:border-color .2s;outline:none;" onfocus="this.style.borderColor=\''+iconColor+'\'" onblur="this.style.borderColor=\'#E2E8F0\'"></textarea><div style="margin-top:12px;padding:10px 14px;background:'+(isBlock?'#FEF2F2':'#ECFDF5')+';border-radius:8px;display:flex;align-items:center;gap:8px;font-size:.75rem;color:'+(isBlock?'#991B1B':'#065F46')+';"><i class="bi bi-info-circle-fill"></i> <%= T("A styled email will be sent to the user immediately after confirmation.","E-mel yang bergaya akan dihantar kepada pengguna sejurus selepas pengesahan.") %></div></div>';
Swal.fire({title:titleText,html:htmlContent,icon:null,showCancelButton:true,confirmButtonText:isBlock?'<i class="bi bi-send-fill"></i> <%= T("Block & Send Email","Sekat & Hantar E-mel") %>':'<i class="bi bi-send-fill"></i> <%= T("Activate & Send Email","Aktifkan & Hantar E-mel") %>',cancelButtonText:'<%= T("Cancel","Batal") %>',confirmButtonColor:iconColor,width:520,preConfirm:function(){return document.getElementById('swalReasonInput').value;}}).then(function(r){if(!r.isConfirmed)return;var reason=r.value||'';fetch(basePath+'?handler=ParentCRUD&action=changeStatus&parentId='+parentId+'&newStatus='+s+'&reason='+encodeURIComponent(reason),{method:'POST'}).then(function(r){return r.json();}).then(function(d){if(d.success)Swal.fire({icon:'success',title:'<%= T("Status Changed!","Status Ditukar!") %>',html:'<div style="text-align:left;font-size:.85rem;margin-top:12px;"><div style="background:#ECFDF5;border:1px solid #A7F3D0;border-radius:10px;padding:14px 18px;"><div style="display:flex;align-items:center;gap:8px;margin-bottom:8px;"><i class="bi bi-envelope-check-fill" style="color:#059669;font-size:1.1rem;"></i><strong style="color:#065F46;"><%= T("Email Sent Successfully","E-mel Berjaya Dihantar") %></strong></div><div style="font-size:.8rem;color:#334155;"><strong><%= T("To:","Kepada:") %></strong> '+(d.emailSent||'-')+'</div><div style="font-size:.8rem;color:#64748B;margin-top:4px;"><strong><%= T("Subject:","Subjek:") %></strong> '+(d.emailStatus==='Blocked'?'<%= T("Your ScienceBuddy Account Has Been Blocked","Akaun ScienceBuddy Anda Telah Disekat") %>':'<%= T("Your ScienceBuddy Account Has Been Reactivated","Akaun ScienceBuddy Anda Telah Diaktifkan Semula") %>')+'</div></div></div>',confirmButtonColor:'#2563EB'}).then(function(){location.reload();});else Swal.fire({icon:'error',title:'Error',text:d.msg});});});}
if(currentStatus==='Active'){document.getElementById('btnActivate').classList.add('ad-details-btn-disabled');}
if(currentStatus==='Blocked'){document.getElementById('btnBlock').classList.add('ad-details-btn-disabled');}function resetPassword(){Swal.fire({title:'<%= T("Reset Password?","Tetapkan Semula?") %>',icon:'question',showCancelButton:true,confirmButtonColor:'#059669'}).then(function(r){if(!r.isConfirmed)return;fetch(basePath+'?handler=ParentCRUD&action=resetPw&parentId='+parentId,{method:'POST'}).then(function(r){return r.json();}).then(function(d){if(d.success)Swal.fire({icon:'success',title:'<%= T("Reset!","Ditetapkan Semula!") %>',text:'New: '+d.newPw,confirmButtonColor:'#059669'});});});}
</script>
</asp:Content>
