<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ParentDetails.aspx.cs"
    Inherits="ScienceBuddy.Admin.ParentDetails" MasterPageFile="~/Site.Master"
    Title="Parent Details" %>

<asp:Content ID="cHead" ContentPlaceHolderID="HeadContent" runat="server">
    <link href="<%: ResolveUrl("~/Content/Admin.css") %>" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css" />
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="<%: ResolveUrl("~/Scripts/admin-signout.js") %>"></script>
</asp:Content>

<asp:Content ID="cSidebar" ContentPlaceHolderID="SidebarMenu" runat="server">
    <div class="sb-nav-section"><div class="sb-nav-section-label">Main</div><a href="<%: ResolveUrl("~/Admin/Dashboard.aspx") %>" class="sb-sidebar-item"><i class="bi bi-speedometer2 item-icon"></i><span class="item-label">Dashboard</span></a></div>
    <div class="sb-nav-section"><div class="sb-nav-section-label">User Management</div><a href="<%: ResolveUrl("~/Admin/StudentManagement.aspx") %>" class="sb-sidebar-item"><i class="bi bi-people item-icon"></i><span class="item-label">Students</span></a><a href="<%: ResolveUrl("~/Admin/ParentManagement.aspx") %>" class="sb-sidebar-item active"><i class="bi bi-person-heart item-icon"></i><span class="item-label">Parents</span></a><a href="<%: ResolveUrl("~/Admin/TeacherManagement.aspx") %>" class="sb-sidebar-item"><i class="bi bi-person-badge item-icon"></i><span class="item-label">Teachers</span></a></div>
    <div class="sb-nav-section"><div class="sb-nav-section-label">Learning Content</div><a href="<%: ResolveUrl("~/Admin/LessonManagement.aspx") %>" class="sb-sidebar-item"><i class="bi bi-book item-icon"></i><span class="item-label">Lessons</span></a><a href="<%: ResolveUrl("~/Admin/QuizManagement.aspx") %>" class="sb-sidebar-item"><i class="bi bi-patch-question item-icon"></i><span class="item-label">Quizzes</span></a><a href="<%: ResolveUrl("~/Admin/QuestionBank.aspx") %>" class="sb-sidebar-item"><i class="bi bi-question-circle item-icon"></i><span class="item-label">Question Bank</span></a><a href="<%: ResolveUrl("~/Admin/TeacherMaterials.aspx") %>" class="sb-sidebar-item"><i class="bi bi-file-earmark-text item-icon"></i><span class="item-label">Material Requests</span></a><a href="<%: ResolveUrl("~/Admin/LiveSessions.aspx") %>" class="sb-sidebar-item"><i class="bi bi-camera-video item-icon"></i><span class="item-label">Live Sessions</span></a><a href="<%: ResolveUrl("~/Admin/QuestionRequests.aspx") %>" class="sb-sidebar-item"><i class="bi bi-clipboard-check item-icon"></i><span class="item-label">Question Requests</span></a><a href="<%: ResolveUrl("~/Admin/CertificateManagement.aspx") %>" class="sb-sidebar-item"><i class="bi bi-award item-icon"></i><span class="item-label">Certificates</span></a></div>
    <div class="sb-nav-section"><div class="sb-nav-section-label">Community</div><a href="<%: ResolveUrl("~/Admin/ForumDiscussions.aspx") %>" class="sb-sidebar-item"><i class="bi bi-chat-dots item-icon"></i><span class="item-label">Forum Discussions</span></a></div>
    <div class="sb-nav-section"><div class="sb-nav-section-label">Gamification</div><a href="<%: ResolveUrl("~/Admin/GamificationManagement.aspx") %>" class="sb-sidebar-item"><i class="bi bi-trophy item-icon"></i><span class="item-label">Student Performance</span></a></div>
    <div class="sb-nav-section"><div class="sb-nav-section-label">Configuration</div><a href="<%: ResolveUrl("~/Admin/SystemSettings.aspx") %>" class="sb-sidebar-item"><i class="bi bi-gear item-icon"></i><span class="item-label">System Settings</span></a></div>
    <div class="sb-nav-section"><div class="sb-nav-section-label">Logs</div><a href="<%: ResolveUrl("~/Admin/SystemActivityLogs.aspx") %>" class="sb-sidebar-item"><i class="bi bi-clock-history item-icon"></i><span class="item-label">Activity Logs</span></a><a href="<%: ResolveUrl("~/Admin/LoginLogs.aspx") %>" class="sb-sidebar-item"><i class="bi bi-box-arrow-in-right item-icon"></i><span class="item-label">Login Logs</span></a><a href="<%: ResolveUrl("~/Admin/SuspiciousLogins.aspx") %>" class="sb-sidebar-item"><i class="bi bi-exclamation-triangle item-icon"></i><span class="item-label">Suspicious Logins</span></a></div>
    <div class="sb-nav-section"><div class="sb-nav-section-label">Account</div><a href="<%: ResolveUrl("~/Admin/Notifications.aspx") %>" class="sb-sidebar-item"><i class="bi bi-bell item-icon"></i><span class="item-label">Notifications</span></a><a href="<%: ResolveUrl("~/Admin/Profile.aspx") %>" class="sb-sidebar-item"><i class="bi bi-person item-icon"></i><span class="item-label">My Profile</span></a><a href="javascript:;" class="sb-sidebar-item" onclick="showSignOutModal()"><i class="bi bi-box-arrow-right item-icon"></i><span class="item-label">Sign Out</span></a></div>
</asp:Content>

<asp:Content ID="cPageTitle" ContentPlaceHolderID="PageTitle" runat="server">Parent Details</asp:Content>
<asp:Content ID="cMain" ContentPlaceHolderID="MainContentSidebar" runat="server">
<a href="<%: ResolveUrl("~/Admin/ParentManagement.aspx") %>" class="ad-parent-details-back"><i class="bi bi-arrow-left"></i> <%= T("Back to Parents", "Kembali ke Ibu Bapa") %></a>
<div class="ad-parent-details-profile">
    <div class="ad-parent-details-avatar"><asp:Literal ID="litInitials" runat="server" /></div>
    <div class="ad-parent-details-info"><div class="ad-parent-details-name"><asp:Literal ID="litName" runat="server" /></div><div class="ad-parent-details-meta"><span><i class="bi bi-hash"></i> <asp:Literal ID="litParentId" runat="server" /></span><span><i class="bi bi-person"></i> <asp:Literal ID="litUsername" runat="server" /></span><span><i class="bi bi-envelope"></i> <asp:Literal ID="litEmail" runat="server" /></span><span><asp:Literal ID="litStatusBadge" runat="server" /></span></div></div>
    <div class="ad-parent-details-quick"><div class="ad-parent-details-quick-item"><div class="ad-parent-details-quick-val"><asp:Literal ID="litChildren" runat="server" Text="0" /></div><div class="ad-parent-details-quick-lbl"><%= T("Children","Anak") %></div></div></div>
</div>
<div class="ad-parent-details-tabs">
    <div class="ad-parent-details-tab active" onclick="switchTab('profile')"><i class="bi bi-person"></i> <%= T("Profile","Profil") %></div>
    <div class="ad-parent-details-tab" onclick="switchTab('account')"><i class="bi bi-gear"></i> <%= T("Account","Akaun") %></div>
    <div class="ad-parent-details-tab" onclick="switchTab('activity')"><i class="bi bi-clock-history"></i> <%= T("Activity","Aktiviti") %></div>
</div>
<div class="ad-parent-details-panel active" id="tab-profile"><asp:Literal ID="litProfileFields" runat="server" /><div class="ad-parent-details-actions"><a href="javascript:;" class="ad-parent-details-btn ad-parent-details-btn-primary" onclick="editProfile()"><i class="bi bi-pencil"></i> <%= T("Edit Profile","Sunting Profil") %></a></div></div>
<div class="ad-parent-details-panel" id="tab-account"><asp:Literal ID="litAccountFields" runat="server" /><div class="ad-parent-details-actions"><a href="javascript:;" class="ad-parent-details-btn ad-parent-details-btn-success" onclick="changeStatus('Active')"><i class="bi bi-check-circle"></i> <%= T("Activate","Aktifkan") %></a><a href="javascript:;" class="ad-parent-details-btn ad-parent-details-btn-warning" onclick="changeStatus('Blocked')"><i class="bi bi-slash-circle"></i> <%= T("Block","Sekat") %></a><a href="javascript:;" class="ad-parent-details-btn ad-parent-details-btn-danger" onclick="archiveUser()"><i class="bi bi-archive"></i> <%= T("Archive","Arkib") %></a><a href="javascript:;" class="ad-parent-details-btn" onclick="resetPassword()"><i class="bi bi-key"></i> <%= T("Reset Password","Tetapkan Semula Kata Laluan") %></a></div></div>
<div class="ad-parent-details-panel" id="tab-activity"><asp:Literal ID="litActivityLog" runat="server" /></div>
<asp:HiddenField ID="hfParentId" runat="server" /><asp:HiddenField ID="hfUserId" runat="server" />
<script>
var parentId=document.getElementById('<%= hfParentId.ClientID %>').value;
var basePath=window.location.pathname;
function switchTab(t){document.querySelectorAll('.ad-parent-details-tab').forEach(function(x){x.classList.remove('active');});document.querySelectorAll('.ad-parent-details-panel').forEach(function(p){p.classList.remove('active');});event.currentTarget.classList.add('active');document.getElementById('tab-'+t).classList.add('active');}
function editProfile(){Swal.fire({title:'<%= T("Edit Profile","Sunting Profil") %>',html:'<div style="text-align:left;"><label style="font-size:.75rem;font-weight:600;display:block;margin-bottom:4px;">Name</label><input id="sN" class="swal2-input" style="width:100%;margin:0 0 12px;"/><label style="font-size:.75rem;font-weight:600;display:block;margin-bottom:4px;">Email</label><input id="sE" class="swal2-input" style="width:100%;margin:0 0 12px;"/><label style="font-size:.75rem;font-weight:600;display:block;margin-bottom:4px;">Phone</label><input id="sP" class="swal2-input" style="width:100%;margin:0;"/></div>',showCancelButton:true,confirmButtonText:'<%= T("Save","Simpan") %>',confirmButtonColor:'#059669',didOpen:function(){fetch(basePath+'?handler=ParentCRUD&action=get&parentId='+parentId,{method:'POST'}).then(function(r){return r.json();}).then(function(d){if(d.success){document.getElementById('sN').value=d.data.name;document.getElementById('sE').value=d.data.email;document.getElementById('sP').value=d.data.phone;}});}}).then(function(r){if(!r.isConfirmed)return;fetch(basePath+'?handler=ParentCRUD&action=edit&parentId='+parentId+'&name='+encodeURIComponent(document.getElementById('sN').value)+'&email='+encodeURIComponent(document.getElementById('sE').value)+'&phone='+encodeURIComponent(document.getElementById('sP').value),{method:'POST'}).then(function(r){return r.json();}).then(function(d){if(d.success){Swal.fire({icon:'success',title:'<%= T("Updated!","Dikemas Kini!") %>',timer:2000,timerProgressBar:true}).then(function(){location.reload();});}else Swal.fire({icon:'error',title:'Error',text:d.msg});});});}
function changeStatus(s){Swal.fire({title:'<%= T("Change Status?","Tukar Status?") %>',input:'textarea',inputPlaceholder:'<%= T("Reason...","Alasan...") %>',showCancelButton:true,confirmButtonText:s,confirmButtonColor:s==='Active'?'#059669':'#D97706'}).then(function(r){if(!r.isConfirmed)return;fetch(basePath+'?handler=ParentCRUD&action=changeStatus&parentId='+parentId+'&newStatus='+s+'&reason='+encodeURIComponent(r.value||''),{method:'POST'}).then(function(r){return r.json();}).then(function(d){if(d.success)Swal.fire({icon:'success',title:'<%= T("Done!","Selesai!") %>',timer:2000,timerProgressBar:true}).then(function(){location.reload();});else Swal.fire({icon:'error',title:'Error',text:d.msg});});});}
function archiveUser(){Swal.fire({title:'<%= T("Archive?","Arkibkan?") %>',icon:'warning',showCancelButton:true,confirmButtonText:'<%= T("Archive","Arkib") %>',confirmButtonColor:'#DC2626'}).then(function(r){if(!r.isConfirmed)return;fetch(basePath+'?handler=ParentCRUD&action=archive&parentId='+parentId,{method:'POST'}).then(function(r){return r.json();}).then(function(d){if(d.success)Swal.fire({icon:'success',title:'<%= T("Archived!","Diarkibkan!") %>',timer:2000,timerProgressBar:true}).then(function(){window.location.href='<%: ResolveUrl("~/Admin/ParentManagement.aspx") %>';});});});}
function resetPassword(){Swal.fire({title:'<%= T("Reset Password?","Tetapkan Semula?") %>',icon:'question',showCancelButton:true,confirmButtonColor:'#059669'}).then(function(r){if(!r.isConfirmed)return;fetch(basePath+'?handler=ParentCRUD&action=resetPw&parentId='+parentId,{method:'POST'}).then(function(r){return r.json();}).then(function(d){if(d.success)Swal.fire({icon:'success',title:'<%= T("Reset!","Ditetapkan Semula!") %>',text:'New: '+d.newPw,confirmButtonColor:'#059669'});});});}
</script>
</asp:Content>
