<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ParentDetails.aspx.cs"
    Inherits="ScienceBuddy.Admin.ParentDetails" MasterPageFile="~/Site.Master"
    Title="Parent Details" %>

<asp:Content ID="cHead" ContentPlaceHolderID="HeadContent" runat="server">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css" />
<style>
:root{--pd:#059669;--pd-light:#ECFDF5;}
.sd-back{display:inline-flex;align-items:center;gap:6px;font-size:.875rem;font-weight:600;color:var(--color-text-secondary);text-decoration:none;margin-bottom:var(--space-lg);transition:color .2s;}.sd-back:hover{color:var(--pd);}
.sd-profile{background:var(--color-white);border-radius:var(--border-radius-xl);border:1.5px solid var(--border-color);box-shadow:var(--shadow-sm);padding:var(--space-xl);display:flex;align-items:center;gap:var(--space-xl);margin-bottom:var(--space-xl);flex-wrap:wrap;}
.sd-avatar{width:80px;height:80px;border-radius:50%;background:linear-gradient(135deg,#059669,#10B981);display:flex;align-items:center;justify-content:center;font-size:1.75rem;font-weight:800;color:#fff;flex-shrink:0;}
.sd-info{flex:1;min-width:200px;}.sd-name{font-family:var(--font-primary);font-size:1.5rem;font-weight:800;color:var(--color-text);}
.sd-meta{display:flex;gap:var(--space-md);flex-wrap:wrap;margin-top:6px;font-size:.8rem;color:var(--color-text-muted);}.sd-meta span{display:flex;align-items:center;gap:4px;}
.sd-quick{display:flex;gap:var(--space-md);flex-wrap:wrap;}.sd-quick-item{text-align:center;padding:var(--space-sm) var(--space-md);background:var(--color-surface-alt);border-radius:var(--border-radius);min-width:70px;}
.sd-quick-val{font-family:var(--font-primary);font-size:1.25rem;font-weight:800;color:var(--color-text);}.sd-quick-lbl{font-size:.7rem;color:var(--color-text-muted);font-weight:600;}
.sd-tabs{display:flex;gap:4px;margin-bottom:var(--space-lg);border-bottom:2px solid var(--border-color);padding-bottom:0;}
.sd-tab{padding:10px 20px;font-size:.875rem;font-weight:600;color:var(--color-text-secondary);cursor:pointer;border-bottom:2px solid transparent;margin-bottom:-2px;transition:all .2s;border-radius:var(--border-radius) var(--border-radius) 0 0;}.sd-tab:hover{color:var(--pd);background:var(--pd-light);}.sd-tab.active{color:var(--pd);border-bottom-color:var(--pd);background:var(--pd-light);}
.sd-panel{display:none;background:var(--color-white);border-radius:var(--border-radius-xl);border:1.5px solid var(--border-color);box-shadow:var(--shadow-sm);padding:var(--space-xl);}.sd-panel.active{display:block;}
.sd-field{display:flex;align-items:center;padding:12px 0;border-bottom:1px solid #F1F5F9;}.sd-field:last-child{border-bottom:none;}.sd-field-label{width:160px;font-size:.8rem;font-weight:600;color:var(--color-text-muted);text-transform:uppercase;letter-spacing:.5px;flex-shrink:0;}.sd-field-value{font-size:.9rem;font-weight:600;color:var(--color-text);flex:1;}
.sd-actions{display:flex;gap:var(--space-sm);flex-wrap:wrap;margin-top:var(--space-lg);}
.sd-btn{padding:8px 18px;border-radius:var(--border-radius);font-size:.8rem;font-weight:700;cursor:pointer;border:1.5px solid var(--border-color);transition:all .2s;display:inline-flex;align-items:center;gap:6px;text-decoration:none;background:var(--color-white);color:var(--color-text-secondary);}.sd-btn:hover{transform:translateY(-1px);box-shadow:var(--shadow-sm);}
.sd-btn-primary{background:linear-gradient(135deg,#059669,#10B981);color:#fff;border:none;box-shadow:0 2px 8px rgba(5,150,105,.25);}
.sd-btn-danger{border-color:#DC2626;color:#DC2626;}.sd-btn-warning{border-color:#D97706;color:#D97706;}.sd-btn-success{border-color:#059669;color:#059669;}
.sd-log-item{display:flex;align-items:flex-start;gap:var(--space-md);padding:12px 0;border-bottom:1px solid #F1F5F9;}.sd-log-item:last-child{border-bottom:none;}
.sd-log-ico{width:32px;height:32px;border-radius:var(--border-radius);display:flex;align-items:center;justify-content:center;font-size:.9rem;flex-shrink:0;background:var(--pd-light);color:var(--pd);}
.sd-log-body{flex:1;}.sd-log-action{font-weight:700;font-size:.85rem;color:var(--color-text);}.sd-log-desc{font-size:.78rem;color:var(--color-text-muted);margin-top:2px;}.sd-log-time{font-size:.7rem;color:var(--color-text-muted);margin-top:3px;}
@media(max-width:767px){.sd-profile{flex-direction:column;align-items:flex-start;}.sd-tabs{overflow-x:auto;}.sd-field{flex-direction:column;align-items:flex-start;gap:4px;}.sd-field-label{width:auto;}}
</style>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="<%: ResolveUrl("~/Scripts/admin-signout.js") %>"></script>
</asp:Content>

<asp:Content ID="cSidebar" ContentPlaceHolderID="SidebarMenu" runat="server">
    <div class="sb-nav-section"><div class="sb-nav-section-label">Main</div><a href="<%: ResolveUrl("~/Admin/Dashboard.aspx") %>" class="sb-sidebar-item"><i class="bi bi-speedometer2 item-icon"></i><span class="item-label">Dashboard</span></a></div>
    <div class="sb-nav-section"><div class="sb-nav-section-label">User Management</div><a href="<%: ResolveUrl("~/Admin/StudentManagement.aspx") %>" class="sb-sidebar-item"><i class="bi bi-people item-icon"></i><span class="item-label">Students</span></a><a href="<%: ResolveUrl("~/Admin/ParentManagement.aspx") %>" class="sb-sidebar-item active"><i class="bi bi-person-heart item-icon"></i><span class="item-label">Parents</span></a><a href="<%: ResolveUrl("~/Admin/TeacherManagement.aspx") %>" class="sb-sidebar-item"><i class="bi bi-person-badge item-icon"></i><span class="item-label">Teachers</span></a></div>
    <div class="sb-nav-section"><div class="sb-nav-section-label">Learning Content</div><a href="<%: ResolveUrl("~/Admin/LessonManagement.aspx") %>" class="sb-sidebar-item"><i class="bi bi-book item-icon"></i><span class="item-label">Lessons</span></a><a href="<%: ResolveUrl("~/Admin/QuizManagement.aspx") %>" class="sb-sidebar-item"><i class="bi bi-patch-question item-icon"></i><span class="item-label">Quizzes</span></a><a href="<%: ResolveUrl("~/Admin/QuestionBank.aspx") %>" class="sb-sidebar-item"><i class="bi bi-question-circle item-icon"></i><span class="item-label">Question Bank</span></a><a href="<%: ResolveUrl("~/Admin/TeacherMaterials.aspx") %>" class="sb-sidebar-item"><i class="bi bi-file-earmark-text item-icon"></i><span class="item-label">Material Requests</span></a><a href="<%: ResolveUrl("~/Admin/LiveSessions.aspx") %>" class="sb-sidebar-item"><i class="bi bi-camera-video item-icon"></i><span class="item-label">Live Sessions</span></a><a href="<%: ResolveUrl("~/Admin/QuestionRequests.aspx") %>" class="sb-sidebar-item"><i class="bi bi-clipboard-check item-icon"></i><span class="item-label">Question Requests</span></a><a href="<%: ResolveUrl("~/Admin/CertificateManagement.aspx") %>" class="sb-sidebar-item"><i class="bi bi-award item-icon"></i><span class="item-label">Certificates</span></a></div>
    <div class="sb-nav-section"><div class="sb-nav-section-label">Community</div><a href="<%: ResolveUrl("~/Admin/ForumDiscussions.aspx") %>" class="sb-sidebar-item"><i class="bi bi-chat-dots item-icon"></i><span class="item-label">Forum Discussions</span></a></div>
    <div class="sb-nav-section"><div class="sb-nav-section-label">Gamification</div><a href="<%: ResolveUrl("~/Admin/GamificationManagement.aspx") %>" class="sb-sidebar-item"><i class="bi bi-trophy item-icon"></i><span class="item-label">Student Performance</span></a></div>
    <div class="sb-nav-section"><div class="sb-nav-section-label">Configuration</div><a href="<%: ResolveUrl("~/Admin/SystemSettings.aspx") %>" class="sb-sidebar-item"><i class="bi bi-gear item-icon"></i><span class="item-label">System Settings</span></a></div>
    <div class="sb-nav-section"><div class="sb-nav-section-label">Logs</div><a href="<%: ResolveUrl("~/Admin/SystemActivityLogs.aspx") %>" class="sb-sidebar-item"><i class="bi bi-clock-history item-icon"></i><span class="item-label">Activity Logs</span></a><a href="<%: ResolveUrl("~/Admin/LoginLogs.aspx") %>" class="sb-sidebar-item"><i class="bi bi-box-arrow-in-right item-icon"></i><span class="item-label">Login Logs</span></a><a href="<%: ResolveUrl("~/Admin/SuspiciousLogins.aspx") %>" class="sb-sidebar-item"><i class="bi bi-exclamation-triangle item-icon"></i><span class="item-label">Suspicious Logins</span></a></div>
    <div class="sb-nav-section"><div class="sb-nav-section-label">Account</div><a href="<%: ResolveUrl("~/Admin/Notifications.aspx") %>" class="sb-sidebar-item"><i class="bi bi-bell item-icon"></i><span class="item-label">Notifications</span></a><a href="<%: ResolveUrl("~/Admin/Profile.aspx") %>" class="sb-sidebar-item"><i class="bi bi-person item-icon"></i><span class="item-label">My Profile</span></a><a href="javascript:;" class="sb-sidebar-item" onclick="showSignOutModal()"><i class="bi bi-box-arrow-right item-icon"></i><span class="item-label">Sign Out</span></a></div>
</asp:Content>

<asp:Content ID="cPageTitle" ContentPlaceHolderID="PageTitle" runat="server">Parent Details</asp:Content>
<asp:Content ID="cMain" ContentPlaceHolderID="MainContentSidebar" runat="server">
<a href="<%: ResolveUrl("~/Admin/ParentManagement.aspx") %>" class="sd-back"><i class="bi bi-arrow-left"></i> <%= T("Back to Parents", "Kembali ke Ibu Bapa") %></a>
<div class="sd-profile">
    <div class="sd-avatar"><asp:Literal ID="litInitials" runat="server" /></div>
    <div class="sd-info"><div class="sd-name"><asp:Literal ID="litName" runat="server" /></div><div class="sd-meta"><span><i class="bi bi-hash"></i> <asp:Literal ID="litParentId" runat="server" /></span><span><i class="bi bi-person"></i> <asp:Literal ID="litUsername" runat="server" /></span><span><i class="bi bi-envelope"></i> <asp:Literal ID="litEmail" runat="server" /></span><span><asp:Literal ID="litStatusBadge" runat="server" /></span></div></div>
    <div class="sd-quick"><div class="sd-quick-item"><div class="sd-quick-val"><asp:Literal ID="litChildren" runat="server" Text="0" /></div><div class="sd-quick-lbl"><%= T("Children","Anak") %></div></div></div>
</div>
<div class="sd-tabs">
    <div class="sd-tab active" onclick="switchTab('profile')"><i class="bi bi-person"></i> <%= T("Profile","Profil") %></div>
    <div class="sd-tab" onclick="switchTab('account')"><i class="bi bi-gear"></i> <%= T("Account","Akaun") %></div>
    <div class="sd-tab" onclick="switchTab('activity')"><i class="bi bi-clock-history"></i> <%= T("Activity","Aktiviti") %></div>
</div>
<div class="sd-panel active" id="tab-profile"><asp:Literal ID="litProfileFields" runat="server" /><div class="sd-actions"><a href="javascript:;" class="sd-btn sd-btn-primary" onclick="editProfile()"><i class="bi bi-pencil"></i> <%= T("Edit Profile","Sunting Profil") %></a></div></div>
<div class="sd-panel" id="tab-account"><asp:Literal ID="litAccountFields" runat="server" /><div class="sd-actions"><a href="javascript:;" class="sd-btn sd-btn-success" onclick="changeStatus('Active')"><i class="bi bi-check-circle"></i> <%= T("Activate","Aktifkan") %></a><a href="javascript:;" class="sd-btn sd-btn-warning" onclick="changeStatus('Blocked')"><i class="bi bi-slash-circle"></i> <%= T("Block","Sekat") %></a><a href="javascript:;" class="sd-btn sd-btn-danger" onclick="archiveUser()"><i class="bi bi-archive"></i> <%= T("Archive","Arkib") %></a><a href="javascript:;" class="sd-btn" onclick="resetPassword()"><i class="bi bi-key"></i> <%= T("Reset Password","Tetapkan Semula Kata Laluan") %></a></div></div>
<div class="sd-panel" id="tab-activity"><asp:Literal ID="litActivityLog" runat="server" /></div>
<asp:HiddenField ID="hfParentId" runat="server" /><asp:HiddenField ID="hfUserId" runat="server" />
<script>
var parentId=document.getElementById('<%= hfParentId.ClientID %>').value;
var basePath=window.location.pathname;
function switchTab(t){document.querySelectorAll('.sd-tab').forEach(function(x){x.classList.remove('active');});document.querySelectorAll('.sd-panel').forEach(function(p){p.classList.remove('active');});event.currentTarget.classList.add('active');document.getElementById('tab-'+t).classList.add('active');}
function editProfile(){Swal.fire({title:'<%= T("Edit Profile","Sunting Profil") %>',html:'<div style="text-align:left;"><label style="font-size:.75rem;font-weight:600;display:block;margin-bottom:4px;">Name</label><input id="sN" class="swal2-input" style="width:100%;margin:0 0 12px;"/><label style="font-size:.75rem;font-weight:600;display:block;margin-bottom:4px;">Email</label><input id="sE" class="swal2-input" style="width:100%;margin:0 0 12px;"/><label style="font-size:.75rem;font-weight:600;display:block;margin-bottom:4px;">Phone</label><input id="sP" class="swal2-input" style="width:100%;margin:0;"/></div>',showCancelButton:true,confirmButtonText:'<%= T("Save","Simpan") %>',confirmButtonColor:'#059669',didOpen:function(){fetch(basePath+'?handler=ParentCRUD&action=get&parentId='+parentId,{method:'POST'}).then(function(r){return r.json();}).then(function(d){if(d.success){document.getElementById('sN').value=d.data.name;document.getElementById('sE').value=d.data.email;document.getElementById('sP').value=d.data.phone;}});}}).then(function(r){if(!r.isConfirmed)return;fetch(basePath+'?handler=ParentCRUD&action=edit&parentId='+parentId+'&name='+encodeURIComponent(document.getElementById('sN').value)+'&email='+encodeURIComponent(document.getElementById('sE').value)+'&phone='+encodeURIComponent(document.getElementById('sP').value),{method:'POST'}).then(function(r){return r.json();}).then(function(d){if(d.success){Swal.fire({icon:'success',title:'<%= T("Updated!","Dikemas Kini!") %>',timer:2000,timerProgressBar:true}).then(function(){location.reload();});}else Swal.fire({icon:'error',title:'Error',text:d.msg});});});}
function changeStatus(s){Swal.fire({title:'<%= T("Change Status?","Tukar Status?") %>',input:'textarea',inputPlaceholder:'<%= T("Reason...","Alasan...") %>',showCancelButton:true,confirmButtonText:s,confirmButtonColor:s==='Active'?'#059669':'#D97706'}).then(function(r){if(!r.isConfirmed)return;fetch(basePath+'?handler=ParentCRUD&action=changeStatus&parentId='+parentId+'&newStatus='+s+'&reason='+encodeURIComponent(r.value||''),{method:'POST'}).then(function(r){return r.json();}).then(function(d){if(d.success)Swal.fire({icon:'success',title:'<%= T("Done!","Selesai!") %>',timer:2000,timerProgressBar:true}).then(function(){location.reload();});else Swal.fire({icon:'error',title:'Error',text:d.msg});});});}
function archiveUser(){Swal.fire({title:'<%= T("Archive?","Arkibkan?") %>',icon:'warning',showCancelButton:true,confirmButtonText:'<%= T("Archive","Arkib") %>',confirmButtonColor:'#DC2626'}).then(function(r){if(!r.isConfirmed)return;fetch(basePath+'?handler=ParentCRUD&action=archive&parentId='+parentId,{method:'POST'}).then(function(r){return r.json();}).then(function(d){if(d.success)Swal.fire({icon:'success',title:'<%= T("Archived!","Diarkibkan!") %>',timer:2000,timerProgressBar:true}).then(function(){window.location.href='<%: ResolveUrl("~/Admin/ParentManagement.aspx") %>';});});});}
function resetPassword(){Swal.fire({title:'<%= T("Reset Password?","Tetapkan Semula?") %>',icon:'question',showCancelButton:true,confirmButtonColor:'#059669'}).then(function(r){if(!r.isConfirmed)return;fetch(basePath+'?handler=ParentCRUD&action=resetPw&parentId='+parentId,{method:'POST'}).then(function(r){return r.json();}).then(function(d){if(d.success)Swal.fire({icon:'success',title:'<%= T("Reset!","Ditetapkan Semula!") %>',text:'New: '+d.newPw,confirmButtonColor:'#059669'});});});}
</script>
</asp:Content>
