//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScienceBuddy.Admin
{
    public partial class Settings
    {
        protected global::System.Web.UI.WebControls.Literal litLang;
    }
}
