//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScienceBuddy.Admin
{
    public partial class StudentManagement
    {
        protected global::System.Web.UI.WebControls.Literal litTotal;
        protected global::System.Web.UI.WebControls.Literal litAvgXP;
        protected global::System.Web.UI.WebControls.Literal litHighLevel;
        protected global::System.Web.UI.WebControls.Literal litActive;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.DropDownList ddlLevel;
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
        protected global::System.Web.UI.WebControls.DropDownList ddlLang;
        protected global::System.Web.UI.WebControls.DropDownList ddlSort;
        protected global::System.Web.UI.WebControls.Button btnSearch;
        protected global::System.Web.UI.WebControls.Button btnReset;
        protected global::System.Web.UI.WebControls.Panel pnlStudents;
        protected global::System.Web.UI.WebControls.Repeater rptStudents;
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
        // Modal
        protected global::System.Web.UI.WebControls.Panel pnlModal;
        protected global::System.Web.UI.WebControls.Literal litMInitials;
        protected global::System.Web.UI.WebControls.Literal litMName;
        protected global::System.Web.UI.WebControls.Literal litMUsername;
        protected global::System.Web.UI.WebControls.Literal litMLessons;
        protected global::System.Web.UI.WebControls.Literal litMXP;
        protected global::System.Web.UI.WebControls.Literal litMQuizzes;
        protected global::System.Web.UI.WebControls.Literal litMBadges;
        protected global::System.Web.UI.WebControls.Literal litMEmail;
        protected global::System.Web.UI.WebControls.Literal litMPhone;
        protected global::System.Web.UI.WebControls.Literal litMLevel;
        protected global::System.Web.UI.WebControls.Literal litMPersonality;
        protected global::System.Web.UI.WebControls.Literal litMLangVal;
        protected global::System.Web.UI.WebControls.Literal litMStatus;
        protected global::System.Web.UI.WebControls.Literal litMXPPct;
        protected global::System.Web.UI.WebControls.Button btnCloseModal;
    }
}
