//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ScienceBuddy.Admin
{
    public partial class SuspiciousLogins
    {
        protected global::System.Web.UI.WebControls.Literal litSuspicious;
        protected global::System.Web.UI.WebControls.Literal litBlocked;
        protected global::System.Web.UI.WebControls.Literal litFailed;
        protected global::System.Web.UI.WebControls.Literal litResolved;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
        protected global::System.Web.UI.WebControls.Button btnSearch;
        protected global::System.Web.UI.WebControls.Button btnReset;
        protected global::System.Web.UI.WebControls.Panel pnlLogs;
        protected global::System.Web.UI.WebControls.Repeater rptLogs;
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
    }
}
