//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ScienceBuddy.Admin
{
    public partial class SystemActivityLogs
    {
        protected global::System.Web.UI.WebControls.Literal litTotal;
        protected global::System.Web.UI.WebControls.Literal litTotalTrend;
        protected global::System.Web.UI.WebControls.Literal litToday;
        protected global::System.Web.UI.WebControls.Literal litTodayTrend;
        protected global::System.Web.UI.WebControls.Literal litSuccess;
        protected global::System.Web.UI.WebControls.Literal litSuccessTrend;
        protected global::System.Web.UI.WebControls.Literal litWarn;
        protected global::System.Web.UI.WebControls.Literal litWarnTrend;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
        protected global::System.Web.UI.WebControls.DropDownList ddlAction;
        protected global::System.Web.UI.WebControls.Button btnSearch;
        protected global::System.Web.UI.WebControls.Button btnReset;
        protected global::System.Web.UI.WebControls.Panel pnlTimeline;
        protected global::System.Web.UI.WebControls.Repeater rptLogs;
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
        protected global::System.Web.UI.WebControls.Panel pnlModal;
        protected global::System.Web.UI.WebControls.Literal litMLogId;
        protected global::System.Web.UI.WebControls.Literal litMUserId;
        protected global::System.Web.UI.WebControls.Literal litMAction;
        protected global::System.Web.UI.WebControls.Literal litMDesc;
        protected global::System.Web.UI.WebControls.Literal litMStatus;
        protected global::System.Web.UI.WebControls.Literal litMDateTime;
        protected global::System.Web.UI.WebControls.Button btnCloseModal;
    }
}
