//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ScienceBuddy.Admin
{
    public partial class TeacherManagement
    {
        protected global::System.Web.UI.WebControls.Literal litTotal;
        protected global::System.Web.UI.WebControls.Literal litActive;
        protected global::System.Web.UI.WebControls.Literal litLessons;
        protected global::System.Web.UI.WebControls.Literal litQuizzes;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
        protected global::System.Web.UI.WebControls.DropDownList ddlLang;
        protected global::System.Web.UI.WebControls.DropDownList ddlSort;
        protected global::System.Web.UI.WebControls.Button btnSearch;
        protected global::System.Web.UI.WebControls.Button btnReset;
        protected global::System.Web.UI.WebControls.Panel pnlTeachers;
        protected global::System.Web.UI.WebControls.Repeater rptTeachers;
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
        protected global::System.Web.UI.WebControls.Panel pnlProfileModal;
        protected global::System.Web.UI.WebControls.Literal litMInitials;
        protected global::System.Web.UI.WebControls.Literal litMName;
        protected global::System.Web.UI.WebControls.Literal litMUsername;
        protected global::System.Web.UI.WebControls.Literal litMMaterials;
        protected global::System.Web.UI.WebControls.Literal litMQuizzes;
        protected global::System.Web.UI.WebControls.Literal litMSessions;
        protected global::System.Web.UI.WebControls.Literal litMPending;
        protected global::System.Web.UI.WebControls.Literal litMEmail;
        protected global::System.Web.UI.WebControls.Literal litMPhone;
        protected global::System.Web.UI.WebControls.Literal litMQual;
        protected global::System.Web.UI.WebControls.Literal litMStatus;
        protected global::System.Web.UI.WebControls.Literal litMLang;
        protected global::System.Web.UI.WebControls.Literal litMDate;
        protected global::System.Web.UI.WebControls.Button btnCloseProfile;
        protected global::System.Web.UI.WebControls.Panel pnlContentModal;
        protected global::System.Web.UI.WebControls.LinkButton lnkCloseContent;
        protected global::System.Web.UI.WebControls.Panel pnlContentList;
        protected global::System.Web.UI.WebControls.Repeater rptContent;
        protected global::System.Web.UI.WebControls.Panel pnlNoContent;
    }
}
