//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScienceBuddy.Parent
{
    public partial class ChildProgress
    {
        protected global::System.Web.UI.WebControls.DropDownList ddlSidebarChild;
        protected global::System.Web.UI.WebControls.Panel pnlMessage;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divMessage;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl iMsgIcon;
        protected global::System.Web.UI.WebControls.Button btnCloseMsg;
        protected global::System.Web.UI.WebControls.Panel pnlNoChild;
        protected global::System.Web.UI.WebControls.Literal litNoChildMsg;
        protected global::System.Web.UI.WebControls.Panel pnlContent;
        protected global::System.Web.UI.WebControls.Literal litHeroTitle;
        protected global::System.Web.UI.WebControls.Literal litHeroSub;
        protected global::System.Web.UI.WebControls.Literal litMonthlySummary;
        protected global::System.Web.UI.WebControls.Literal litHeatmapTitle;
        protected global::System.Web.UI.WebControls.DropDownList ddlMonth;
        protected global::System.Web.UI.WebControls.Panel pnlHeatmapDays;
        protected global::System.Web.UI.WebControls.HiddenField hidSelectedDate;
        protected global::System.Web.UI.WebControls.Button btnDayClick;
        protected global::System.Web.UI.WebControls.Panel pnlDailyModal;
        protected global::System.Web.UI.WebControls.Literal litDailyTitle;
        protected global::System.Web.UI.WebControls.Button btnCloseDailyModal;
        protected global::System.Web.UI.WebControls.Panel pnlDailyActivities;
        protected global::System.Web.UI.WebControls.Panel pnlDailyEmpty;
        protected global::System.Web.UI.WebControls.Literal litDailyEmpty;
        protected global::System.Web.UI.WebControls.Literal litCoachTitle;
        protected global::System.Web.UI.WebControls.Image imgFox;
        protected global::System.Web.UI.WebControls.Literal litCoachMessage;
        protected global::System.Web.UI.WebControls.Panel pnlCoachTip;
        protected global::System.Web.UI.WebControls.Literal litCoachTip;
        protected global::System.Web.UI.WebControls.Panel pnlAddStudyPlanBtn;
        protected global::System.Web.UI.WebControls.Literal litAddToPlanBtn;
        protected global::System.Web.UI.WebControls.Panel pnlTaskModal;
        protected global::System.Web.UI.WebControls.Literal litTaskModalTitle;
        protected global::System.Web.UI.WebControls.Literal litTaskModalSub;
        protected global::System.Web.UI.WebControls.Literal litLblTaskName;
        protected global::System.Web.UI.WebControls.TextBox txtTaskName;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTaskName;
        protected global::System.Web.UI.WebControls.Literal litLblSuggestedAction;
        protected global::System.Web.UI.WebControls.TextBox txtSuggestedAction;
        protected global::System.Web.UI.WebControls.Literal litBtnCancel;
        protected global::System.Web.UI.WebControls.Button btnAddTask;
        protected global::System.Web.UI.WebControls.Literal litUnreadBadge;

        // Science Power Map controls
        protected global::System.Web.UI.WebControls.Panel pnlPowerMap;
        protected global::System.Web.UI.WebControls.Literal litPowerMapTitle;
        protected global::System.Web.UI.WebControls.Literal litPowerMapSvg;
        protected global::System.Web.UI.WebControls.Literal litExplorerType;
        protected global::System.Web.UI.WebControls.Literal litSuperpower;
        protected global::System.Web.UI.WebControls.Literal litPowerUp;
        protected global::System.Web.UI.WebControls.Panel pnlPowerMapAdvice;
        protected global::System.Web.UI.WebControls.Literal litPowerMapAdvice;
        protected global::System.Web.UI.WebControls.Literal litPowerMapFooter;
        protected global::System.Web.UI.WebControls.Literal litSkillDataScript;

    }
}