//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScienceBuddy.Parent
{
    public partial class ChildProfile
    {
        protected global::System.Web.UI.WebControls.Panel pnlNoChild;
        protected global::System.Web.UI.WebControls.Literal litNoChildMsg;
        protected global::System.Web.UI.WebControls.Literal litNoChildLink;
        protected global::System.Web.UI.WebControls.Panel pnlProfile;
        protected global::System.Web.UI.WebControls.Literal litInitials;
        protected global::System.Web.UI.WebControls.Literal litName;
        protected global::System.Web.UI.WebControls.Literal litNickname;
        protected global::System.Web.UI.WebControls.Literal litLevel;
        protected global::System.Web.UI.WebControls.Literal litRelationship;
        protected global::System.Web.UI.WebControls.Literal litPathTitle;
        protected global::System.Web.UI.WebControls.Panel pnlUnits;
        protected global::System.Web.UI.WebControls.Panel pnlNoUnits;
        protected global::System.Web.UI.WebControls.Literal litNoUnits;
        protected global::System.Web.UI.WebControls.Literal litRecentTitle;
        protected global::System.Web.UI.WebControls.Panel pnlRecent;
        protected global::System.Web.UI.WebControls.Panel pnlNoRecent;
        protected global::System.Web.UI.WebControls.Literal litNoRecent;
        protected global::System.Web.UI.WebControls.Literal litAchieveTitle;
        protected global::System.Web.UI.WebControls.Literal litXP;
        protected global::System.Web.UI.WebControls.Literal litXPLabel;
        protected global::System.Web.UI.WebControls.Literal litBadgeCount;
        protected global::System.Web.UI.WebControls.Literal litBadgeCountLabel;
        protected global::System.Web.UI.WebControls.Panel pnlLatestBadge;
        protected global::System.Web.UI.WebControls.Literal litLatestBadge;
    }
}
