//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScienceBuddy.Parent
{
    public partial class EnrolledModules
    {
        protected global::System.Web.UI.WebControls.Panel pnlNoChild;
        protected global::System.Web.UI.WebControls.DropDownList ddlSidebarChild;
        protected global::System.Web.UI.WebControls.Literal litNoChild;
        protected global::System.Web.UI.WebControls.Panel pnlContent;
        protected global::System.Web.UI.WebControls.Literal litHeroTitle;
        protected global::System.Web.UI.WebControls.Literal litHeroSub;
        protected global::System.Web.UI.WebControls.Literal litHeroChild;
        protected global::System.Web.UI.WebControls.Literal litSumUnits;
        protected global::System.Web.UI.WebControls.Literal litSumUnitsLabel;
        protected global::System.Web.UI.WebControls.Literal litSumLessons;
        protected global::System.Web.UI.WebControls.Literal litSumLessonsLabel;
        protected global::System.Web.UI.WebControls.Literal litSumCompleted;
        protected global::System.Web.UI.WebControls.Literal litSumCompletedLabel;
        protected global::System.Web.UI.WebControls.Literal litSumProgress;
        protected global::System.Web.UI.WebControls.Literal litSumProgressLabel;
        protected global::System.Web.UI.WebControls.LinkButton lnkAll;
        protected global::System.Web.UI.WebControls.LinkButton lnkInProgress;
        protected global::System.Web.UI.WebControls.LinkButton lnkCompleted;
        protected global::System.Web.UI.WebControls.LinkButton lnkNotStarted;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.Panel pnlJourneyMap;
        protected global::System.Web.UI.WebControls.Panel pnlUnits;
        protected global::System.Web.UI.WebControls.Panel pnlNoUnits;
        protected global::System.Web.UI.WebControls.Literal litNoUnits;
    }
}
