//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScienceBuddy.Parent
{
    public partial class LinkChildAccount
    {
        protected global::System.Web.UI.WebControls.Panel pnlMessage;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divMsg;
        protected global::System.Web.UI.WebControls.Literal litTitle;
        protected global::System.Web.UI.WebControls.Literal litSub;
        protected global::System.Web.UI.WebControls.Literal litLblCode;
        protected global::System.Web.UI.WebControls.TextBox txtCode;
        protected global::System.Web.UI.WebControls.Literal litLblRelationship;
        protected global::System.Web.UI.WebControls.DropDownList ddlRelationship;
        protected global::System.Web.UI.WebControls.Button btnLink;
        protected global::System.Web.UI.WebControls.Literal litLinkedTitle;
        protected global::System.Web.UI.WebControls.Panel pnlLinkedList;
        protected global::System.Web.UI.WebControls.Panel pnlNoLinked;
        protected global::System.Web.UI.WebControls.Literal litNoLinked;
        protected global::System.Web.UI.WebControls.HiddenField hidUnlinkArg;
        protected global::System.Web.UI.WebControls.Panel pnlUnlinkModal;
        protected global::System.Web.UI.WebControls.Literal litModalTitle;
        protected global::System.Web.UI.WebControls.Literal litModalMsg;
        protected global::System.Web.UI.WebControls.Button btnCancelUnlink;
        protected global::System.Web.UI.WebControls.Button btnConfirmUnlink;
    }
}
