//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScienceBuddy.Parent
{
    public partial class ParentDashboard
    {
        /// <summary>
        /// ddlSidebarChild — sidebar child switcher dropdown.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlSidebarChild;

        /// <summary>
        /// pnlMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlMessage;

        /// <summary>
        /// divMessage control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divMessage;

        // ── New hero controls ─────────────────────────────────────────

        /// <summary>litHeroEyebrow — "My Child's Science Journey" label.</summary>
        protected global::System.Web.UI.WebControls.Literal litHeroEyebrow;

        /// <summary>litHeroGreeting — "Hi, [Parent Name]!"</summary>
        protected global::System.Web.UI.WebControls.Literal litHeroGreeting;

        /// <summary>pnlHeroViewing — shown when a child is selected.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlHeroViewing;

        /// <summary>litHeroViewing — "Currently viewing: [Child Name]"</summary>
        protected global::System.Web.UI.WebControls.Literal litHeroViewing;

        /// <summary>litHeroLevel — level pill text.</summary>
        protected global::System.Web.UI.WebControls.Literal litHeroLevel;

        /// <summary>litHeroXP — XP pill text.</summary>
        protected global::System.Web.UI.WebControls.Literal litHeroXP;

        /// <summary>pnlHeroBadges — badges pill, shown only when count > 0.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlHeroBadges;

        /// <summary>litHeroBadges — badges pill text.</summary>
        protected global::System.Web.UI.WebControls.Literal litHeroBadges;

        // (ddlHeroChildren removed — child switching moved to sidebar)

        /// <summary>pnlHeroNoChild — shown when no child linked.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlHeroNoChild;

        /// <summary>litHeroNoChild — no child message inside hero.</summary>
        protected global::System.Web.UI.WebControls.Literal litHeroNoChild;

        /// <summary>litHeroLinkChild — "Link New Child" button text (shown when child is linked).</summary>
        protected global::System.Web.UI.WebControls.Literal litHeroLinkChild;

        /// <summary>litHeroLinkChildNoChild — "Link New Child" button text (shown when no child linked).</summary>
        protected global::System.Web.UI.WebControls.Literal litHeroLinkChildNoChild;

        // ── Kept hero controls (still referenced in SetLabels) ────────

        /// <summary>
        /// pnlNoChild control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoChild;

        /// <summary>
        /// litNoChildMsg control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litNoChildMsg;

        /// <summary>
        /// litLinkChildBtn control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litLinkChildBtn;

        /// <summary>
        /// pnlDashboard control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlDashboard;

        /// <summary>litSelectChildLabel — removed (duplicate selector gone).</summary>
        // removed: litSelectChildLabel, ddlChildren, litChildInitials, litChildName,
        //          litChildMeta, litChildLevel, litChildLevelLabel, litChildXP, litChildXPLabel

        // (litHeroDdlLabel removed — child switching moved to sidebar)

        // ── Child Snapshot card controls ──────────────────────────────
        /// <summary>litSnapshotTitle — "Child Snapshot"</summary>
        protected global::System.Web.UI.WebControls.Literal litSnapshotTitle;

        /// <summary>litSnapshotSub — subtitle line.</summary>
        protected global::System.Web.UI.WebControls.Literal litSnapshotSub;

        /// <summary>litSnapInitials — child avatar initials.</summary>
        protected global::System.Web.UI.WebControls.Literal litSnapInitials;

        /// <summary>litSnapName — child full name + nickname.</summary>
        protected global::System.Web.UI.WebControls.Literal litSnapName;

        /// <summary>litSnapRel — relationship label.</summary>
        protected global::System.Web.UI.WebControls.Literal litSnapRel;

        /// <summary>litSnapStatus — learning status badge text.</summary>
        protected global::System.Web.UI.WebControls.Literal litSnapStatus;

        /// <summary>pnlSnapActivity — container for activity rows.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlSnapActivity;

        /// <summary>pnlSnapLesson — latest lesson row.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlSnapLesson;

        /// <summary>litSnapLessonLabel — "Latest Lesson" label.</summary>
        protected global::System.Web.UI.WebControls.Literal litSnapLessonLabel;

        /// <summary>litSnapLessonTitle — lesson title text.</summary>
        protected global::System.Web.UI.WebControls.Literal litSnapLessonTitle;

        /// <summary>litSnapLessonDate — lesson completed date.</summary>
        protected global::System.Web.UI.WebControls.Literal litSnapLessonDate;

        /// <summary>pnlSnapQuiz — latest quiz row.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlSnapQuiz;

        /// <summary>litSnapQuizLabel — "Latest Quiz" label.</summary>
        protected global::System.Web.UI.WebControls.Literal litSnapQuizLabel;

        /// <summary>litSnapQuizTitle — quiz title text.</summary>
        protected global::System.Web.UI.WebControls.Literal litSnapQuizTitle;

        /// <summary>litSnapQuizMeta — quiz percentage + status.</summary>
        protected global::System.Web.UI.WebControls.Literal litSnapQuizMeta;

        /// <summary>pnlSnapNoActivity — empty state when no activity.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlSnapNoActivity;

        /// <summary>litSnapNoActivity — "No recent activity yet."</summary>
        protected global::System.Web.UI.WebControls.Literal litSnapNoActivity;

        /// <summary>litSnapBtnProfile — "View Profile" button text.</summary>
        protected global::System.Web.UI.WebControls.Literal litSnapBtnProfile;

        /// <summary>litSnapBtnProgress — "View Progress" button text.</summary>
        protected global::System.Web.UI.WebControls.Literal litSnapBtnProgress;

        /// <summary>litSnapBtnReport — "Report Card" button text.</summary>
        protected global::System.Web.UI.WebControls.Literal litSnapBtnReport;

        // ── Summary cards (3 pastel cards) ──────────────────────────

        /// <summary>litProgressValue — overall progress percentage.</summary>
        protected global::System.Web.UI.WebControls.Literal litProgressValue;

        /// <summary>litProgressLabel — "Lessons completed" label.</summary>
        protected global::System.Web.UI.WebControls.Literal litProgressLabel;

        /// <summary>litQuizScoreValue — average quiz score value.</summary>
        protected global::System.Web.UI.WebControls.Literal litQuizScoreValue;

        /// <summary>litQuizScoreLabel — quiz score label.</summary>
        protected global::System.Web.UI.WebControls.Literal litQuizScoreLabel;

        /// <summary>litBadgeValue — total badges count.</summary>
        protected global::System.Web.UI.WebControls.Literal litBadgeValue;

        /// <summary>litBadgeLabel — "Badges collected" label.</summary>
        protected global::System.Web.UI.WebControls.Literal litBadgeLabel;

        // ── Forum section controls ─────────────────────────────────

        /// <summary>litForumTitle — "Forum" heading.</summary>
        protected global::System.Web.UI.WebControls.Literal litForumTitle;

        /// <summary>litForumSub — forum subtitle.</summary>
        protected global::System.Web.UI.WebControls.Literal litForumSub;

        /// <summary>lnkTabPublic — Public tab button.</summary>
        protected global::System.Web.UI.WebControls.LinkButton lnkTabPublic;

        /// <summary>litTabPublic — "Public" tab text.</summary>
        protected global::System.Web.UI.WebControls.Literal litTabPublic;

        /// <summary>lnkTabPrivate — Student-Parent tab button.</summary>
        protected global::System.Web.UI.WebControls.LinkButton lnkTabPrivate;

        /// <summary>litTabPrivate — "Student-Parent" tab text.</summary>
        protected global::System.Web.UI.WebControls.Literal litTabPrivate;

        /// <summary>ddlForumTag — tag filter dropdown.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlForumTag;

        /// <summary>ddlForumSort — sort dropdown (Latest/Oldest).</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlForumSort;

        /// <summary>txtForumSearch — search textbox.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtForumSearch;

        /// <summary>pnlForumPosts — container for forum post cards.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlForumPosts;

        /// <summary>pnlNoForumPosts — empty state panel.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoForumPosts;

        /// <summary>litNoForumMsg — "No discussions yet."</summary>
        protected global::System.Web.UI.WebControls.Literal litNoForumMsg;

        /// <summary>litGoToForum — "Go to Forum" button text.</summary>
        protected global::System.Web.UI.WebControls.Literal litGoToForum;

        // ── Lower section: Study Plan + Recent Activities ────────────

        /// <summary>litStudyPlanTitle — study plan card title.</summary>
        protected global::System.Web.UI.WebControls.Literal litStudyPlanTitle;

        /// <summary>pnlStudyPlanCard — shown when study plan exists.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlStudyPlanCard;

        /// <summary>pnlSPTaskList — container for dynamically rendered task rows.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlSPTaskList;

        /// <summary>pnlNoStudyPlan — empty state for study plan.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoStudyPlan;

        /// <summary>litNoStudyPlanMsg — "No study plan yet."</summary>
        protected global::System.Web.UI.WebControls.Literal litNoStudyPlanMsg;

        /// <summary>litRecentActivitiesTitle — "Recent Activities" heading.</summary>
        protected global::System.Web.UI.WebControls.Literal litRecentActivitiesTitle;

        /// <summary>pnlRecentActivities — container for timeline items.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlRecentActivities;

        /// <summary>pnlNoActivities — empty state for activities.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoActivities;

        /// <summary>litNoActivitiesMsg — "No recent activities yet."</summary>
        protected global::System.Web.UI.WebControls.Literal litNoActivitiesMsg;
    }
}
